import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { escapeRegex, lineAtValueOffset } from "../engine.mjs";

const LIST_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "passive-participles.json");

const BE_FORMS = new Set(["am", "is", "are", "was", "were", "be", "been", "being"]);

const FILLERS = new Set([
  "not",
  "never",
  "also",
  "already",
  "then",
  "now",
  "just",
  "still",
  "yet",
  "once",
  "only",
  "so",
  "thus",
  "again",
  "even",
]);

const WINDOW = 3;

function isFiller(word) {
  return FILLERS.has(word) || word.endsWith("ly");
}

const PARTICIPLES = loadParticiples();

function loadParticiples() {
  const { participles } = JSON.parse(readFileSync(LIST_PATH, "utf8"));
  return new Set(participles.map((p) => p.toLowerCase()));
}

const PARTICIPLE_RE = new RegExp(
  `\\b(?:${[...PARTICIPLES]
    .sort((a, b) => b.length - a.length)
    .map(escapeRegex)
    .join("|")})\\b`,
  "gi",
);

function words(text) {
  const tokens = [];
  for (const m of text.matchAll(/[\w'-]+/g)) tokens.push({ word: m[0], index: m.index });
  return tokens;
}

function beBefore(before) {
  let fillers = 0;
  for (let k = before.length - 1; k >= 0; k--) {
    const w = before[k].word.toLowerCase();
    if (BE_FORMS.has(w)) return before[k];
    if (fillers < WINDOW && isFiller(w)) {
      fillers++;
      continue;
    }
    return null;
  }
  return null;
}

// Measured near 99% precision over 1,412 flags in 177 docs, which let a candidate warning ship.
// An attributive participle ("are measured facts") over-flags: this route carries no POS tag.
export const passiveVoice = {
  name: "passive-voice",
  severity: "warning",
  check(_proseNodes, ctx) {
    const violations = [];
    for (const block of ctx.blocks) {
      const value = block.value;
      PARTICIPLE_RE.lastIndex = 0;
      let m;
      while ((m = PARTICIPLE_RE.exec(value)) !== null) {
        const before = words(value.slice(0, m.index));
        const be = beBefore(before);
        if (!be) continue;
        const span = value.slice(be.index, m.index + m[0].length).replace(/\s+/g, " ").trim();
        violations.push({
          line: lineAtValueOffset(value, block.startLine, be.index),
          message: `a passive verb form "${span}" — prefer the active voice, or confirm the passive is intentional`,
        });
      }
    }
    return violations;
  },
  fixtures: {
    mustFlag: [
      "The job was completed by the worker.",
      "The tokens are generated at build time.",
      "Each rule is measured against the fixture corpus.",
      "The docs have been rewritten this week.",
      "The report was recently generated by the nightly job.",
      "The stale file is not removed until the next run.",
    ],
    mustNotFlag: [
      "The worker completed the job on time.",
      "The build is ready for a review.",
      "The report is a completed draft.",
      "The team measured the cost last week.",
      "Run `is completed` in the shell to check it.",
      "```sh\necho was completed the job\n```",
      "> The vendor said the work was completed for us.",
      "| Step | Note |\n| --- | --- |\n| ship | was completed |",
    ],
  },
};
