// Command web is the only listener in the deployment: it serves the
// operator UI, applies database migrations on startup, and is the
// container docker compose's healthcheck watches (ADR-0001, §4.2).
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/pressly/goose/v3"

	"github.com/winniel123/verge-asm/db/migrations"
	"github.com/winniel123/verge-asm/internal/auth"
	"github.com/winniel123/verge-asm/internal/db"
	"github.com/winniel123/verge-asm/internal/env"
	"github.com/winniel123/verge-asm/internal/pgdb"
	"github.com/winniel123/verge-asm/internal/queue"
)

func main() {
	healthcheck := flag.Bool("healthcheck", false, "check that the running instance is healthy, then exit")
	seedFixtures := flag.String("seed-fixtures", "", "dev-only: reseed the open-span corpus from the given design fixtures file, then exit (requires VERGE_DEV)")
	flag.Parse()

	listenAddr := env.OrDefault("VERGE_LISTEN_ADDR", ":8080")

	if *healthcheck {
		if err := checkHealth(listenAddr); err != nil {
			log.Fatalf("web: healthcheck: %v", err)
		}
		return
	}

	// The fixture loader is a dev-only escape hatch (#525): it wipes and reseeds the
	// span corpus so the pixel-parity harness has a deterministic instance. Refuse it
	// outside an explicit VERGE_DEV build so it can never fire against a real estate.
	if *seedFixtures != "" && !isTruthy(env.OrDefault("VERGE_DEV", "")) {
		log.Fatalf("web: -seed-fixtures is dev-only; set VERGE_DEV=1 to allow it")
	}

	databaseURL, err := env.Require("DATABASE_URL")
	if err != nil {
		log.Fatalf("web: %v", err)
	}

	if err := migrateUp(databaseURL); err != nil {
		log.Fatalf("web: migrate: %v", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	pool, err := pgdb.Connect(ctx, databaseURL)
	if err != nil {
		log.Fatalf("web: connect: %v", err)
	}
	defer pool.Close()

	if *seedFixtures != "" {
		if err := seedInventoryFixtures(ctx, pool, *seedFixtures); err != nil {
			log.Fatalf("web: seed-fixtures: %v", err)
		}
		if err := seedDevOperator(ctx, pool); err != nil {
			log.Fatalf("web: seed-fixtures: %v", err)
		}
		// The fixtures.json admin + viewer the ErrorPage capture states sign in as
		// (screen 2, #534). Idempotent and dev-only, like the operator above.
		if err := seedDevFixtureAccounts(ctx, pool); err != nil {
			log.Fatalf("web: seed-fixtures: %v", err)
		}
		log.Printf("web: seeded inventory fixtures from %s (%d open spans); dev operator %q + %d fixture accounts ready", *seedFixtures, len(inventoryFixtureSpans), devSeedUsername, len(devFixtureAccounts))
		return
	}

	queries := db.New(pool)

	// The session signing key is generated by web into its own volume and
	// never touches Postgres (§4.3): a database dump does not leak it.
	key, err := auth.LoadOrCreateKey(env.OrDefault("VERGE_STATE_DIR", "/app/state"))
	if err != nil {
		log.Fatalf("web: session key: %v", err)
	}

	setupToken, err := bootstrapSetupToken(ctx, queries)
	if err != nil {
		log.Fatalf("web: setup token: %v", err)
	}

	web := newServer(queries, key, setupToken, time.Now)
	// VERGE_DEV unlocks the pixel-parity harness affordances (dev /dev/* routes and the
	// deterministic 500 incident id). It is the same gate -seed-fixtures rides; a real
	// deployment never sets it, so no /dev route is registered and incident ids stay random.
	web.devMode = isTruthy(env.OrDefault("VERGE_DEV", ""))
	web.secureCookies = isTruthy(env.OrDefault("VERGE_SECURE_COOKIES", ""))
	// The trusted origin for the OIDC callback redirect_uri (#293); empty falls back to
	// the request host.
	web.externalURL = env.OrDefault("VERGE_EXTERNAL_URL", "")
	// The on-demand scan trigger (#252) enqueues through the same queue Dispatcher
	// the worker's CLI -trigger path uses. Web has no listener of its own — the
	// running worker claims the enqueued jobs off the pg_notify the fan-out sends —
	// so web only needs to insert the Dispatch and its jobs, which the Dispatcher
	// over this pool does.
	web.dispatcher = queue.NewDispatcher(pool, time.Now, log.New(os.Stderr, "", log.LstdFlags))
	// Explicit timeouts guard the only internet-facing listener against
	// Slowloris-style slow-request DoS (gosec G112). The operator UI serves
	// bounded request/response bodies with no long-lived streaming or SSE, so
	// finite write/idle deadlines are safe.
	srv := &http.Server{
		Addr:              listenAddr,
		Handler:           web.handler(),
		ReadHeaderTimeout: 10 * time.Second,
		ReadTimeout:       15 * time.Second,
		WriteTimeout:      30 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("web: shutdown: %v", err)
		}
	}()

	log.Printf("web: listening on %s", listenAddr)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("web: serve: %v", err)
	}
}

// bootstrapSetupToken opens the first-run setup window when no accounts exist.
// The token is the operator's VERGE_SETUP_TOKEN if set (the one config that may
// live in the environment because it must exist before the database has an
// admin, §5.1), otherwise a generated one written to the logs. It returns ""
// once an account exists, which keeps setup closed and the token single-use.
func bootstrapSetupToken(ctx context.Context, q *db.Queries) (string, error) {
	n, err := q.CountAccounts(ctx)
	if err != nil {
		return "", fmt.Errorf("count accounts: %w", err)
	}
	if n > 0 {
		return "", nil
	}

	token := env.OrDefault("VERGE_SETUP_TOKEN", "")
	if token == "" {
		if token, err = auth.NewSetupToken(); err != nil {
			return "", err
		}
	}
	log.Printf("web: no accounts yet — open /setup with this single-use token: %s", token)
	return token, nil
}

// isTruthy reads the common affirmative spellings of a boolean env value.
func isTruthy(v string) bool {
	switch strings.ToLower(strings.TrimSpace(v)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func migrateUp(databaseURL string) error {
	sqlDB, err := pgdb.OpenStdlib(databaseURL)
	if err != nil {
		return err
	}
	defer sqlDB.Close()

	goose.SetBaseFS(migrations.FS)
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("web: set goose dialect: %w", err)
	}
	if err := goose.Up(sqlDB, "."); err != nil {
		return fmt.Errorf("web: apply migrations: %w", err)
	}
	return nil
}

func checkHealth(listenAddr string) error {
	_, port, err := net.SplitHostPort(listenAddr)
	if err != nil {
		return fmt.Errorf("parse listen addr %q: %w", listenAddr, err)
	}

	client := http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get("http://127.0.0.1:" + port + "/healthz")
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("healthz returned %d", resp.StatusCode)
	}
	return nil
}

