// Command web is the only listener in the deployment: it serves the
// operator UI, applies database migrations on startup, and is the
// container docker compose's healthcheck watches (ADR-0001, §4.2).
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/pressly/goose/v3"

	"github.com/winniel123/verge-asm/db/migrations"
	"github.com/winniel123/verge-asm/internal/auth"
	"github.com/winniel123/verge-asm/internal/db"
	"github.com/winniel123/verge-asm/internal/env"
	"github.com/winniel123/verge-asm/internal/pgdb"
	"github.com/winniel123/verge-asm/internal/queue"
)

func main() {
	healthcheck := flag.Bool("healthcheck", false, "check that the running instance is healthy, then exit")
	flag.Parse()

	listenAddr := env.OrDefault("VERGE_LISTEN_ADDR", ":8080")

	if *healthcheck {
		if err := checkHealth(listenAddr); err != nil {
			log.Fatalf("web: healthcheck: %v", err)
		}
		return
	}

	databaseURL, err := env.Require("DATABASE_URL")
	if err != nil {
		log.Fatalf("web: %v", err)
	}

	if err := migrateUp(databaseURL); err != nil {
		log.Fatalf("web: migrate: %v", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	pool, err := pgdb.Connect(ctx, databaseURL)
	if err != nil {
		log.Fatalf("web: connect: %v", err)
	}
	defer pool.Close()

	queries := db.New(pool)

	// The session signing key is generated by web into its own volume and
	// never touches Postgres (§4.3): a database dump does not leak it.
	key, err := auth.LoadOrCreateKey(env.OrDefault("VERGE_STATE_DIR", "/app/state"))
	if err != nil {
		log.Fatalf("web: session key: %v", err)
	}

	setupToken, err := bootstrapSetupToken(ctx, queries)
	if err != nil {
		log.Fatalf("web: setup token: %v", err)
	}

	web := newServer(queries, key, setupToken, time.Now)
	web.secureCookies = isTruthy(env.OrDefault("VERGE_SECURE_COOKIES", ""))
	// The on-demand scan trigger (#252) enqueues through the same queue Dispatcher
	// the worker's CLI -trigger path uses. Web has no listener of its own — the
	// running worker claims the enqueued jobs off the pg_notify the fan-out sends —
	// so web only needs to insert the Dispatch and its jobs, which the Dispatcher
	// over this pool does.
	web.dispatcher = queue.NewDispatcher(pool, time.Now, log.New(os.Stderr, "", log.LstdFlags))
	srv := &http.Server{Addr: listenAddr, Handler: web.handler()}

	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("web: shutdown: %v", err)
		}
	}()

	log.Printf("web: listening on %s", listenAddr)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("web: serve: %v", err)
	}
}

// bootstrapSetupToken opens the first-run setup window when no accounts exist.
// The token is the operator's VERGE_SETUP_TOKEN if set (the one config that may
// live in the environment because it must exist before the database has an
// admin, §5.1), otherwise a generated one written to the logs. It returns ""
// once an account exists, which keeps setup closed and the token single-use.
func bootstrapSetupToken(ctx context.Context, q *db.Queries) (string, error) {
	n, err := q.CountAccounts(ctx)
	if err != nil {
		return "", fmt.Errorf("count accounts: %w", err)
	}
	if n > 0 {
		return "", nil
	}

	token := env.OrDefault("VERGE_SETUP_TOKEN", "")
	if token == "" {
		if token, err = auth.NewSetupToken(); err != nil {
			return "", err
		}
	}
	log.Printf("web: no accounts yet — open /setup with this single-use token: %s", token)
	return token, nil
}

// isTruthy reads the common affirmative spellings of a boolean env value.
func isTruthy(v string) bool {
	switch strings.ToLower(strings.TrimSpace(v)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func migrateUp(databaseURL string) error {
	sqlDB, err := pgdb.OpenStdlib(databaseURL)
	if err != nil {
		return err
	}
	defer sqlDB.Close()

	goose.SetBaseFS(migrations.FS)
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("web: set goose dialect: %w", err)
	}
	if err := goose.Up(sqlDB, "."); err != nil {
		return fmt.Errorf("web: apply migrations: %w", err)
	}
	return nil
}

func checkHealth(listenAddr string) error {
	_, port, err := net.SplitHostPort(listenAddr)
	if err != nil {
		return fmt.Errorf("parse listen addr %q: %w", listenAddr, err)
	}

	client := http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get("http://127.0.0.1:" + port + "/healthz")
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("healthz returned %d", resp.StatusCode)
	}
	return nil
}

