package strip

import (
	"errors"
	"strings"
	"testing"

	"github.com/winniel123/verge-asm/internal/commentlint/rule"
	"github.com/winniel123/verge-asm/internal/commentlint/verify"
)

type fixture struct {
	name string
	src  string
	want string
}

var fixtures = []fixture{
	{
		name: "a marker-free exported docstring goes",
		src: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"func F() {}\n",
		want: "package p\n" +
			"\n" +
			"func F() {}\n",
	},
	{
		name: "a cited docstring stays",
		src: "package p\n" +
			"\n" +
			"// F reports the estate (ADR-0127).\n" +
			"func F() {}\n",
		want: "package p\n" +
			"\n" +
			"// F reports the estate (ADR-0127).\n" +
			"func F() {}\n",
	},
	{
		name: "one citation withholds all five lines",
		src: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"// The second line adds nothing.\n" +
			"// The third line cites ADR-0127.\n" +
			"// The fourth line adds nothing.\n" +
			"// The fifth line adds nothing.\n" +
			"func F() {}\n",
		want: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"// The second line adds nothing.\n" +
			"// The third line cites ADR-0127.\n" +
			"// The fourth line adds nothing.\n" +
			"// The fifth line adds nothing.\n" +
			"func F() {}\n",
	},
	{
		name: "a package doc and an exported-other docstring stay",
		src: "// Package p serves the estate.\n" +
			"package p\n" +
			"\n" +
			"// reports the estate.\n" +
			"func F() {}\n",
		want: "// Package p serves the estate.\n" +
			"package p\n" +
			"\n" +
			"// reports the estate.\n" +
			"func F() {}\n",
	},
	{
		name: "no trailing comment is deleted",
		src: "package p\n" +
			"\n" +
			"func F() int {\n" +
			"\treturn 1 // ports census\n" +
			"}\n",
		want: "package p\n" +
			"\n" +
			"func F() int {\n" +
			"\treturn 1 // ports census\n" +
			"}\n",
	},
	{
		name: "the delete collapses the double blank line it would leave",
		src: "package p\n" +
			"\n" +
			"func F() {\n" +
			"\t_ = 1\n" +
			"\n" +
			"\t// ports census\n" +
			"\n" +
			"\t_ = 2\n" +
			"}\n",
		want: "package p\n" +
			"\n" +
			"func F() {\n" +
			"\t_ = 1\n" +
			"\n" +
			"\t_ = 2\n" +
			"}\n",
	},
	{
		name: "the delete leaves a single blank line alone",
		src: "package p\n" +
			"\n" +
			"func F() {\n" +
			"\t_ = 1\n" +
			"\t// ports census\n" +
			"\n" +
			"\t_ = 2\n" +
			"}\n",
		want: "package p\n" +
			"\n" +
			"func F() {\n" +
			"\t_ = 1\n" +
			"\n" +
			"\t_ = 2\n" +
			"}\n",
	},
	{
		name: "gofmt runs on the result",
		src: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"func F()  int  { return 1 }\n",
		want: "package p\n" +
			"\n" +
			"func F() int { return 1 }\n",
	},
	{
		name: "a banner and commented-out code go",
		src: "package p\n" +
			"\n" +
			"// ==================\n" +
			"func F() {\n" +
			"\t// n := 1\n" +
			"\t_ = 1\n" +
			"}\n",
		want: "package p\n" +
			"\n" +
			"func F() {\n" +
			"\t_ = 1\n" +
			"}\n",
	},
	{
		name: "a group opener over exported members stays",
		src: "package p\n" +
			"\n" +
			"// the estate codes the proposer reads for every zone\n" +
			"const (\n" +
			"\tA = 1\n" +
			")\n",
		want: "package p\n" +
			"\n" +
			"// the estate codes the proposer reads for every zone\n" +
			"const (\n" +
			"\tA = 1\n" +
			")\n",
	},
	{
		name: "a Deprecated paragraph withholds its docstring",
		src: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"//\n" +
			"// Deprecated: use G instead.\n" +
			"func F() {}\n",
		want: "package p\n" +
			"\n" +
			"// F reports the estate.\n" +
			"//\n" +
			"// Deprecated: use G instead.\n" +
			"func F() {}\n",
	},
	{
		name: "a directive and a generated header stay",
		src: "// Code generated by sqlc. DO NOT EDIT.\n" +
			"\n" +
			"package p\n" +
			"\n" +
			"//nolint:gosec\n" +
			"func F() {}\n",
		want: "// Code generated by sqlc. DO NOT EDIT.\n" +
			"\n" +
			"package p\n" +
			"\n" +
			"//nolint:gosec\n" +
			"func F() {}\n",
	},
}

func TestFileDeleteSemantics(t *testing.T) {
	for _, f := range fixtures {
		t.Run(f.name, func(t *testing.T) {
			res, err := File("p.go", []byte(f.src))
			if err != nil {
				t.Fatalf("File: %v", err)
			}
			if got := string(res.Source); got != f.want {
				t.Errorf("got:\n%q\nwant:\n%q", got, f.want)
			}
		})
	}
}

func TestStripOutputVerifiesAgainstItsInput(t *testing.T) {
	// The §6.8 property test. A pass that moved a non-comment token would fail
	// ruling 15 on the sweep PR.
	for _, f := range fixtures {
		t.Run(f.name, func(t *testing.T) {
			res, err := File("p.go", []byte(f.src))
			if err != nil {
				t.Fatalf("File: %v", err)
			}
			base := func(string) ([]byte, error) { return []byte(f.src), nil }
			head := func(string) ([]byte, error) { return res.Source, nil }
			report := verify.Run([]string{"p.go"}, false, base, head)
			if report.Exit() != 0 {
				t.Errorf("verify rejected the strip output: %+v", report.Findings)
			}
		})
	}
}

func TestFileRefusesANonGoPath(t *testing.T) {
	// §6.4 keeps the delete pass at Go in v1. A `strip` that silently does
	// nothing is how a sweep agent believes a slice is done.
	cases := []struct {
		path string
		src  string
	}{
		{"db/queries/scan.sql", "-- name: X :one\nSELECT 1;\n"},
		{"docs-site/scripts/doclint.mjs", "// the note\nexport const a = 1;\n"},
		{"docs-site/src/pipeline/toc.ts", "// the note\nexport const a = 1;\n"},
		{"design-system/components/display/Card.d.ts", "// the note\nexport type A = 1;\n"},
		{"docs-site/src/ds/Icon.jsx", "// the note\nconst a = <p>x</p>;\n"},
	}
	for _, c := range cases {
		t.Run(c.path, func(t *testing.T) {
			_, err := File(c.path, []byte(c.src))
			var usage *UsageError
			if !errors.As(err, &usage) {
				t.Fatalf("File on %s returned %v, want a usage error", c.path, err)
			}
		})
	}
}

func TestResidueRecordsEveryDeclinedBlock(t *testing.T) {
	src := "// Package p serves the estate.\n" +
		"package p\n" +
		"\n" +
		"// F reports the estate (ADR-0127).\n" +
		"func F() int {\n" +
		"\treturn 1 // ports census\n" +
		"}\n" +
		"\n" +
		"// g reports the estate.\n" +
		"func g() {}\n"

	res, err := File("p.go", []byte(src))
	if err != nil {
		t.Fatalf("File: %v", err)
	}
	if len(res.Deleted) != 1 || res.Deleted[0].Class != rule.DocstringUnexported {
		t.Fatalf("deleted is %+v, want the one unexported docstring", res.Deleted)
	}

	want := []Record{
		{File: "p.go", StartLine: 1, EndLine: 1, Class: rule.PackageDoc},
		{File: "p.go", StartLine: 4, EndLine: 4, Class: rule.DocstringExportedConventional, Signal: "citation"},
		{File: "p.go", StartLine: 6, EndLine: 6, Class: rule.ShortLabel, Trailing: true},
	}
	if len(res.Residue) != len(want) {
		t.Fatalf("residue is %+v, want %d records", res.Residue, len(want))
	}
	for i, w := range want {
		if res.Residue[i] != w {
			t.Errorf("residue %d is %+v, want %+v", i, res.Residue[i], w)
		}
	}
}

func TestFileLeavesAnUnchangedFileByte4Byte(t *testing.T) {
	src := "package p\r\n\r\n// F reports the estate (ADR-0127).\r\nfunc F()  {}\r\n"
	res, err := File("p.go", []byte(src))
	if err != nil {
		t.Fatalf("File: %v", err)
	}
	if res.Changed() {
		t.Fatal("the pass reported a change it did not make")
	}
	if string(res.Source) != src {
		t.Errorf("an unchanged file was reformatted: %q", res.Source)
	}
	if strings.Contains(string(res.Source), "func F() {}") {
		t.Error("gofmt ran on a file the pass did not change")
	}
}
