package auth

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
)

// keyFile is the basename, inside the state directory, of the session signing
// key. The directory is the web-only volume (docker-compose web-state:/app/state).
const keyFile = "session.key"

// keyLen is the signing-key length in bytes: 256 bits, matching HMAC-SHA256.
const keyLen = 32

// LoadOrCreateKey returns the session signing key held in dir, creating it on
// first boot. The key is generated by web and written to its own volume; it is
// never persisted to Postgres, so a database dump does not disclose it and a
// database restore does not silently rotate it (v1 spec §4.3).
//
// The file is written 0600. dir is created if absent. A key of the wrong
// length is treated as corruption and reported rather than used.
func LoadOrCreateKey(dir string) ([]byte, error) {
	path := filepath.Join(dir, keyFile)

	key, err := os.ReadFile(path) // #nosec G304 (session-key file: constant basename under operator-configured state dir, not request input)
	switch {
	case err == nil:
		if len(key) != keyLen {
			return nil, fmt.Errorf("auth: session key %s is %d bytes, want %d", path, len(key), keyLen)
		}
		return key, nil
	case !os.IsNotExist(err):
		return nil, fmt.Errorf("auth: read session key: %w", err)
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("auth: create state dir: %w", err)
	}
	key = make([]byte, keyLen)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("auth: generate session key: %w", err)
	}
	if err := os.WriteFile(path, key, 0o600); err != nil {
		return nil, fmt.Errorf("auth: write session key: %w", err)
	}
	return key, nil
}

// RotateKey generates a fresh session signing key, overwrites the key file in
// dir with it, and returns the new key. It is the deliberate counterpart to
// LoadOrCreateKey's never-rotate posture: a restore (ADR-0124) regenerates the
// session key so the restored instance never carries a prior instance's signing
// key, and every session signed under the old key lapses — a named guarantee of
// the restore, not an incidental side effect.
//
// The write mirrors LoadOrCreateKey: dir is created if absent, the file is
// 0600, and only a full-length key is ever written. The caller must swap the
// process's in-memory key (and any derived sub-keys) to the returned value, so
// the running process stops honouring cookies signed under the old key at once
// rather than only after a restart.
func RotateKey(dir string) ([]byte, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("auth: create state dir: %w", err)
	}
	key := make([]byte, keyLen)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("auth: generate session key: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, keyFile), key, 0o600); err != nil {
		return nil, fmt.Errorf("auth: write session key: %w", err)
	}
	return key, nil
}
