package auth

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
)

// keyFile is the basename, inside the state directory, of the session signing
// key. The directory is the web-only volume (docker-compose web-state:/app/state).
const keyFile = "session.key"

// keyLen is the signing-key length in bytes: 256 bits, matching HMAC-SHA256.
const keyLen = 32

// LoadOrCreateKey returns the session signing key held in dir, creating it on
// first boot. The key is generated by web and written to its own volume; it is
// never persisted to Postgres, so a database dump does not disclose it and a
// database restore does not silently rotate it (v1 spec §4.3).
//
// The file is written 0600. dir is created if absent. A key of the wrong
// length is treated as corruption and reported rather than used.
func LoadOrCreateKey(dir string) ([]byte, error) {
	path := filepath.Join(dir, keyFile)

	key, err := os.ReadFile(path)
	switch {
	case err == nil:
		if len(key) != keyLen {
			return nil, fmt.Errorf("auth: session key %s is %d bytes, want %d", path, len(key), keyLen)
		}
		return key, nil
	case !os.IsNotExist(err):
		return nil, fmt.Errorf("auth: read session key: %w", err)
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("auth: create state dir: %w", err)
	}
	key = make([]byte, keyLen)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("auth: generate session key: %w", err)
	}
	if err := os.WriteFile(path, key, 0o600); err != nil {
		return nil, fmt.Errorf("auth: write session key: %w", err)
	}
	return key, nil
}
