package rule

import (
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/winniel123/verge-asm/internal/commentlint/screen"
	"github.com/winniel123/verge-asm/internal/commentlint/surface"
)

func lex(t *testing.T, src string) surface.Result {
	t.Helper()
	res, err := surface.Go{}.Lex([]byte(src))
	if err != nil {
		t.Fatalf("Lex: %v", err)
	}
	return res
}

func firstBlock(t *testing.T, src string) surface.Block {
	t.Helper()
	res := lex(t, src)
	if len(res.Blocks) == 0 {
		t.Fatalf("the source holds no own-line block: %q", src)
	}
	return res.Blocks[0]
}

func TestClassifyFollowsThePrecedenceOrder(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want Class
	}{
		{
			name: "a generated header outranks every other class",
			src:  "// Code generated by sqlc. DO NOT EDIT.\npackage p\n",
			want: GeneratedHeader,
		},
		{
			name: "a directive outranks the declaration position",
			src:  "package p\n\n//go:build linux\n\nfunc F() {}\n",
			want: Directive,
		},
		{
			name: "a gosec waiver is a directive, not a short label",
			src:  "package p\n\nfunc F() {\n\t// #nosec G115 (QR version 1..40)\n\t_ = 1\n}\n",
			want: Directive,
		},
		{
			name: "a TODO opener outranks the declaration position",
			src:  "package p\n\n// TODO: drop the shim\nfunc F() {}\n",
			want: Todo,
		},
		{
			name: "commented-out code outranks the declaration position",
			src:  "package p\n\n// x := compute()\nfunc F() {}\n",
			want: CommentedOutCode,
		},
		{
			name: "a banner outranks the declaration position",
			src:  "package p\n\n// ----------------\nfunc F() {}\n",
			want: SectionDivider,
		},
		{
			name: "a package clause takes package-doc",
			src:  "// Package p serves the estate.\npackage p\n",
			want: PackageDoc,
		},
		{
			name: "an exported docstring opening with its identifier is conventional",
			src:  "package p\n\n// F reports the estate.\nfunc F() {}\n",
			want: DocstringExportedConventional,
		},
		{
			name: "an exported docstring opening elsewhere is other",
			src:  "package p\n\n// reports the estate.\nfunc F() {}\n",
			want: DocstringExportedOther,
		},
		{
			name: "an unexported docstring is its own class",
			src:  "package p\n\n// f reports the estate.\nfunc f() {}\n",
			want: DocstringUnexported,
		},
		{
			name: "a struct field takes the unexported class",
			src:  "package p\n\ntype T struct {\n\t// holds the count\n\tn int\n}\n",
			want: DocstringUnexported,
		},
		{
			name: "a const group opener declares no identifier",
			src:  "package p\n\n// one two three four five six seven\nconst (\n\tA = 1\n)\n",
			want: ProseOther,
		},
		{
			name: "an import spec doc declares no identifier",
			src:  "package p\n\nimport (\n\t// one two three four five six seven\n\t\"os\"\n)\n",
			want: ProseOther,
		},
		{
			name: "a body citation is its own class",
			src:  "package p\n\nfunc F() {\n\t// ADR-0127 pins this\n\t_ = 1\n}\n",
			want: Citation,
		},
		{
			name: "a body external spec is its own class",
			src:  "package p\n\nfunc F() {\n\t// the wire format is RFC3339\n\t_ = 1\n}\n",
			want: ExternalSpec,
		},
		{
			name: "a body reason is a why note",
			src:  "package p\n\nfunc F() {\n\t// the read sits here because the guard runs first\n\t_ = 1\n}\n",
			want: WhyNote,
		},
		{
			name: "a body history marker is change narration",
			src:  "package p\n\nfunc F() {\n\t// the worker previously owned this\n\t_ = 1\n}\n",
			want: ChangeNarration,
		},
		{
			name: "the loose set alone is step narration",
			src:  "package p\n\nfunc F() {\n\t// the queue drains now\n\t_ = 1\n}\n",
			want: StepNarration,
		},
		{
			name: "a six-word body line is a short label",
			src:  "package p\n\nfunc F() {\n\t// ports census\n\t_ = 1\n}\n",
			want: ShortLabel,
		},
		{
			name: "a seven-word body line is prose",
			src:  "package p\n\nfunc F() {\n\t// one two three four five six seven\n\t_ = 1\n}\n",
			want: ProseOther,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := Classify(firstBlock(t, c.src)); got != c.want {
				t.Errorf("Classify is %q, want %q", got, c.want)
			}
		})
	}
}

func TestCommentedOutCodeNeedsAParseAndACodeToken(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"prose that parses as an expression", "package p\n\nfunc F() {\n\t// see the note above\n\t_ = 1\n}\n", false},
		{"an assignment payload", "package p\n\nfunc F() {\n\t// n := len(rows)\n\t_ = 1\n}\n", true},
		{"a return payload", "package p\n\nfunc F() {\n\t// return nil, err\n\t_ = 1\n}\n", true},
		{"prose carrying a brace literal", "package p\n\nfunc F() {\n\t// the {scan} placeholder is expanded here\n\t_ = 1\n}\n", false},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := Classify(firstBlock(t, c.src)) == CommentedOutCode
			if got != c.want {
				t.Errorf("commented-out-code is %t, want %t", got, c.want)
			}
		})
	}
}

func TestDeletableAppliesTheScreenBlockWide(t *testing.T) {
	fiveLines := "package p\n" +
		"\n" +
		"// F reports the estate.\n" +
		"// The second line adds nothing.\n" +
		"// The third line cites ADR-0127.\n" +
		"// The fourth line adds nothing.\n" +
		"// The fifth line adds nothing.\n" +
		"func F() {}\n"

	b := firstBlock(t, fiveLines)
	if b.Lines() != 5 {
		t.Fatalf("the block holds %d lines, want 5", b.Lines())
	}
	class, signal, ok := Deletable(b)
	if ok {
		t.Error("a citation on line three did not withhold the block")
	}
	if class != DocstringExportedConventional {
		t.Errorf("class is %q, want %q", class, DocstringExportedConventional)
	}
	if signal != "citation" {
		t.Errorf("signal is %q, want citation", signal)
	}
}

func TestDeletableSet(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"a marker-free exported docstring", "package p\n\n// F reports the estate.\nfunc F() {}\n", true},
		{"a marker-free unexported docstring", "package p\n\n// f reports the estate.\nfunc f() {}\n", true},
		{"an own-line short label", "package p\n\nfunc F() {\n\t// ports census\n\t_ = 1\n}\n", true},
		{"a banner", "package p\n\n// =================\nfunc F() {}\n", true},
		{"commented-out code", "package p\n\nfunc F() {\n\t// n := 1\n\t_ = 1\n}\n", true},
		{"a package doc", "// Package p serves the estate.\npackage p\n", false},
		{"a group opener over exported members", "package p\n\n// the estate codes the proposer reads for every zone\nconst (\n\tA = 1\n)\n", false},
		{"a docstring carrying a Deprecated paragraph", "package p\n\n// F reports the estate.\n//\n// Deprecated: use G instead.\nfunc F() {}\n", false},
		{"an exported docstring opening elsewhere", "package p\n\n// reports the estate.\nfunc F() {}\n", false},
		{"a banner carrying a citation", "package p\n\n// ===== ADR-0127 =====\nfunc F() {}\n", false},
		{"a docstring carrying a reason", "package p\n\n// F avoids the second read.\nfunc F() {}\n", false},
		{"body prose", "package p\n\nfunc F() {\n\t// one two three four five six seven\n\t_ = 1\n}\n", false},
		{"a short own-line gosec waiver", "package p\n\nfunc F() {\n\t// #nosec G115 (QR 1..40)\n\t_ = 1\n}\n", false},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if _, _, got := Deletable(firstBlock(t, c.src)); got != c.want {
				t.Errorf("Deletable is %t, want %t", got, c.want)
			}
		})
	}
}

func TestAWaiverTailIsWithheldFromTheDeletePass(t *testing.T) {
	src := "package p\n" +
		"\n" +
		"// #nosec G101 -- keys are table names paired with prose\n" +
		"// explaining each exclusion.\n" +
		"var x = 1\n"
	res := lex(t, src)
	if len(res.Blocks) != 2 {
		t.Fatalf("the source holds %d block(s), want 2: %+v", len(res.Blocks), res.Blocks)
	}
	tail := res.Blocks[1]
	if !tail.WaiverTail {
		t.Fatal("the wrapped half is not marked a waiver tail")
	}
	class, signal, deletable := Deletable(tail)
	if deletable {
		t.Errorf("the wrapped half of a waiver deletes, class %q", class)
	}
	if signal != screen.SignalToolMarker {
		t.Errorf("signal is %q, want %q", signal, screen.SignalToolMarker)
	}
}

func rules(t *testing.T, src string, testFile bool) []string {
	t.Helper()
	var out []string
	for _, f := range Lint(lex(t, src), testFile) {
		out = append(out, f.Rule)
	}
	sort.Strings(out)
	return out
}

func TestLintReportsTheFlagSetByRuleID(t *testing.T) {
	cases := []struct {
		name     string
		src      string
		testFile bool
		want     []string
	}{
		{
			name: "a declaration docstring reports its class and the ratchet",
			src:  "package p\n\n// F reports the estate.\nfunc F() {}\n",
			want: []string{"docstring-exported-conventional", "go-decl-comment"},
		},
		{
			name: "a package doc is never flagged",
			src:  "// Package p serves the estate.\npackage p\n",
			want: nil,
		},
		{
			name: "a doc on a struct field still reports the ratchet",
			src:  "package p\n\ntype T struct {\n\t// F carries the estate.\n\tF int\n}\n",
			want: []string{"docstring-exported-conventional", "go-decl-comment"},
		},
		{
			name: "a trailing short label is flagged",
			src:  "package p\n\nfunc F() {\n\t_ = 1 // ports census\n}\n",
			want: []string{"short-label"},
		},
		{
			name: "change narration is flagged",
			src:  "package p\n\nfunc F() {\n\t// the worker previously owned this\n\t_ = 1\n}\n",
			want: []string{"change-narration"},
		},
		{
			name: "a TODO is flagged",
			src:  "package p\n\nfunc F() {\n\t// TODO: drop the shim\n\t_ = 1\n}\n",
			want: []string{"todo-marker"},
		},
		{
			name: "a two-line production citation is flagged",
			src:  "package p\n\nfunc F() {\n\t// ADR-0127 pins the cap\n\t// and the second line runs over\n\t_ = 1\n}\n",
			want: []string{"citation-over-one-line"},
		},
		{
			name:     "the same citation in a test file is not flagged",
			src:      "package p\n\nfunc F() {\n\t// ADR-0127 pins the cap\n\t// and the second line runs over\n\t_ = 1\n}\n",
			testFile: true,
			want:     nil,
		},
		{
			name: "step narration is never flagged",
			src:  "package p\n\nfunc F() {\n\t// the queue drains now\n\t_ = 1\n}\n",
			want: nil,
		},
		{
			name: "prose is never flagged",
			src:  "package p\n\nfunc F() {\n\t// one two three four five six seven\n\t_ = 1\n}\n",
			want: nil,
		},
		{
			name: "a directive is never flagged",
			src:  "package p\n\n//nolint:gosec\nfunc F() {}\n",
			want: nil,
		},
		{
			name: "a short own-line gosec waiver is never flagged",
			src:  "package p\n\nfunc F() {\n\t// #nosec G115 (QR version 1..40)\n\t_ = 1\n}\n",
			want: nil,
		},
		{
			name: "a short trailing gosec waiver is never flagged",
			src:  "package p\n\ntype T struct {\n\tpassword string // #nosec G101 -- dev fixture\n}\n",
			want: nil,
		},
		{
			name: "a gosec waiver hides no ratchet target beneath it",
			src:  "package p\n\nfunc F() {\n\t// #nosec G115 (QR 1..40)\n\t// TODO: drop the shim\n\t_ = 1\n}\n",
			want: []string{"todo-marker"},
		},
		{
			name: "a trailing docstring-shaped comment reports nothing",
			src:  "package p\n\nfunc F() {\n\t_ = 1 // one two three four five six seven\n}\n",
			want: nil,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := rules(t, c.src, c.testFile)
			if !slices.Equal(got, c.want) {
				t.Errorf("rules are %v, want %v", got, c.want)
			}
		})
	}
}

func TestDeleteSetNamesEverySeedClass(t *testing.T) {
	want := []Class{
		CommentedOutCode, DocstringExportedConventional, DocstringUnexported,
		SectionDivider, ShortLabel,
	}
	got := DeleteSet()
	if !slices.Equal(got, want) {
		t.Fatalf("DeleteSet is %v, want %v", got, want)
	}
	for _, c := range got {
		if !InDeleteSet(c) {
			t.Errorf("DeleteSet named %q, and InDeleteSet denies it", c)
		}
	}
}

func TestRuleIDsCarryNoDoclintPrefix(t *testing.T) {
	ids := []string{
		string(SectionDivider), string(CommentedOutCode), string(ShortLabel),
		string(DocstringExportedConventional), string(DocstringUnexported),
		RuleGoDeclComment, RuleChangeNarration, RuleTodoMarker, RuleCitationOverOneLine,
		RuleColumnOverCap,
	}
	for _, id := range ids {
		if strings.HasPrefix(id, "no-") {
			t.Errorf("rule id %q carries doclint's no- prefix", id)
		}
	}
}

func TestCapBindsEveryClassTheToolDoesNotOwn(t *testing.T) {
	exempt := []Class{GeneratedHeader, Directive}
	bound := []Class{
		Todo, CommentedOutCode, SectionDivider, PackageDoc,
		DocstringExportedConventional, DocstringExportedOther, DocstringUnexported,
		Citation, ExternalSpec, WhyNote, ChangeNarration, StepNarration,
		ShortLabel, DTSFieldProse, ProseOther,
	}
	for _, c := range exempt {
		if CapBinds(c) {
			t.Errorf("the cap binds %q, and the tool owns its columns (SPEC §4.4)", c)
		}
	}
	for _, c := range bound {
		// §4.3's carve-out withholds the delete ruling, not the cap (§4.4, #1481).
		if !CapBinds(c) {
			t.Errorf("the cap skips %q, and SPEC §4.4 binds it", c)
		}
	}
}

func padTo(t *testing.T, prefix string, cols int) string {
	t.Helper()
	width := 0
	for _, r := range prefix {
		if r == '\t' {
			width += surface.TabColumns
			continue
		}
		width++
	}
	if width > cols {
		t.Fatalf("the prefix already measures %d columns, over the %d wanted", width, cols)
	}
	return prefix + strings.Repeat("x", cols-width)
}

func TestColumnOverCapEscapesTheJudgmentGate(t *testing.T) {
	body := func(line string) string {
		return "package p\n\nfunc F() {\n" + line + "\n\t_ = 1\n}\n"
	}
	prose := "\t// the estate table is rebuilt here and the pager follows it "
	step := "\t// the queue drains now and the pager follows it "
	why := "\t// the read sits here because the guard runs first "
	directive := "//go:generate stringer -type=Kind -output=kind_string.go -tags="
	header := "// Code generated by sqlc. DO NOT EDIT. "
	doc := "// F reports the estate because the guard runs first "
	cases := []struct {
		name string
		src  string
		want []string
	}{
		{
			name: "an own-line block over the cap is flagged",
			src:  body(padTo(t, prose, 101)),
			want: []string{"column-over-cap"},
		},
		{
			name: "a block at exactly the cap is not flagged",
			src:  body(padTo(t, prose, 100)),
			want: nil,
		},
		{
			name: "step narration over the cap is flagged",
			src:  body(padTo(t, step, 101)),
			want: []string{"column-over-cap"},
		},
		{
			name: "a judged class reports the cap beside its own rule",
			src:  "package p\n\n" + padTo(t, doc, 101) + "\nfunc F() {}\n",
			want: []string{"column-over-cap", "docstring-exported-conventional", "go-decl-comment"},
		},
		{
			name: "a directive over the cap is not flagged",
			src:  "package p\n\n" + padTo(t, directive, 130) + "\ntype Kind int\n",
			want: nil,
		},
		{
			name: "a generated header over the cap is not flagged",
			src:  padTo(t, header, 130) + "\npackage p\n",
			want: nil,
		},
		{
			name: "a why-note under the cap is not flagged",
			src:  body(padTo(t, why, 99)),
			want: nil,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := rules(t, c.src, false)
			if !slices.Equal(got, c.want) {
				t.Errorf("rules are %v, want %v", got, c.want)
			}
		})
	}
}

func TestColumnOverCapReadsTheWholeTrailingLine(t *testing.T) {
	comment := " // the estate pager holds the cursor and the caller reads it"
	code := "\t_ = \"" + strings.Repeat("y", 45) + "\""
	src := "package p\n\nfunc F() {\n" + code + comment + "\n}\n"
	if len(comment) > ColumnCap {
		t.Fatalf("the comment alone measures %d columns, so the code prefix proves nothing", len(comment))
	}
	got := rules(t, src, false)
	want := []string{"column-over-cap"}
	if !slices.Equal(got, want) {
		t.Errorf("rules are %v, want %v: the code prefix shares the physical line", got, want)
	}
}
