// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTOTP = `-- name: ConfirmTOTP :exec
UPDATE account SET totp_enabled = true WHERE id = $1 AND totp_secret IS NOT NULL
`

func (q *Queries) ConfirmTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmTOTP, id)
	return err
}

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM account
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (username, role, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, role, password_hash, totp_secret, totp_enabled, created_at
`

type CreateAccountParams struct {
	Username     string `json:"username"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.Role, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, role, password_hash, totp_secret, totp_enabled, created_at
FROM account
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, role, password_hash, totp_secret, totp_enabled, created_at
FROM account
WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE account SET totp_secret = $2, totp_enabled = false WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID         int64       `json:"id"`
	TotpSecret pgtype.Text `json:"totp_secret"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}
