// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTOTP = `-- name: ConfirmTOTP :exec
UPDATE account SET totp_enabled = true WHERE id = $1 AND totp_secret IS NOT NULL
`

func (q *Queries) ConfirmTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmTOTP, id)
	return err
}

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM account
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM account WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (username, role, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, role, password_hash, totp_secret, totp_enabled, created_at, totp_last_step
`

type CreateAccountParams struct {
	Username     string `json:"username"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.Role, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, role, password_hash, totp_secret, totp_enabled, created_at, totp_last_step
FROM account
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, role, password_hash, totp_secret, totp_enabled, created_at, totp_last_step
FROM account
WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.TotpLastStep,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, role, totp_enabled, created_at
FROM account
ORDER BY created_at ASC, id ASC
`

type ListAccountsRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	Role        string             `json:"role"`
	TotpEnabled bool               `json:"totp_enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.TotpEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAccountTOTP = `-- name: ResetAccountTOTP :exec
UPDATE account SET totp_secret = NULL, totp_enabled = false WHERE id = $1
`

func (q *Queries) ResetAccountTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetAccountTOTP, id)
	return err
}

const setTOTPLastStep = `-- name: SetTOTPLastStep :execrows
UPDATE account SET totp_last_step = $2
WHERE id = $1 AND (totp_last_step IS NULL OR totp_last_step < $2)
`

type SetTOTPLastStepParams struct {
	ID           int64       `json:"id"`
	TotpLastStep pgtype.Int8 `json:"totp_last_step"`
}

func (q *Queries) SetTOTPLastStep(ctx context.Context, arg SetTOTPLastStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTOTPLastStep, arg.ID, arg.TotpLastStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE account SET totp_secret = $2, totp_enabled = false WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID         int64       `json:"id"`
	TotpSecret pgtype.Text `json:"totp_secret"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const updateAccountRole = `-- name: UpdateAccountRole :exec
UPDATE account SET role = $2 WHERE id = $1
`

type UpdateAccountRoleParams struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateAccountRole(ctx context.Context, arg UpdateAccountRoleParams) error {
	_, err := q.db.Exec(ctx, updateAccountRole, arg.ID, arg.Role)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE account SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
