// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: act.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAct = `-- name: InsertAct :exec
INSERT INTO act (actor_kind, actor, action, subject)
VALUES ($1, $2, $3, $4)
`

type InsertActParams struct {
	ActorKind string `json:"actor_kind"`
	Actor     []byte `json:"actor"`
	Action    string `json:"action"`
	Subject   []byte `json:"subject"`
}

// id and created_at are defaulted: the caller cannot forge the time (spec §4.1).
func (q *Queries) InsertAct(ctx context.Context, arg InsertActParams) error {
	_, err := q.db.Exec(ctx, insertAct,
		arg.ActorKind,
		arg.Actor,
		arg.Action,
		arg.Subject,
	)
	return err
}

const listActsInRange = `-- name: ListActsInRange :many
SELECT id, created_at, actor_kind, actor, action, subject
FROM act
WHERE created_at >= $1 AND created_at < $2
ORDER BY created_at DESC, id DESC
`

type ListActsInRangeParams struct {
	FromTime  pgtype.Timestamptz `json:"from_time"`
	UntilTime pgtype.Timestamptz `json:"until_time"`
}

// A client-side scope reaches only the rows sent, and the corpus is unbounded (ADR-0158 §6.2).
func (q *Queries) ListActsInRange(ctx context.Context, arg ListActsInRangeParams) ([]Act, error) {
	rows, err := q.db.Query(ctx, listActsInRange, arg.FromTime, arg.UntilTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Act{}
	for rows.Next() {
		var i Act
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorKind,
			&i.Actor,
			&i.Action,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
