// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations.sql

package db

import (
	"context"
)

const createAnnotation = `-- name: CreateAnnotation :one
INSERT INTO annotation (subject_key, signal_name, reason)
VALUES ($1, $2, $3)
RETURNING id, subject_key, signal_name, reason, declared_at
`

type CreateAnnotationParams struct {
	SubjectKey string `json:"subject_key"`
	SignalName string `json:"signal_name"`
	Reason     string `json:"reason"`
}

func (q *Queries) CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, createAnnotation, arg.SubjectKey, arg.SignalName, arg.Reason)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.SubjectKey,
		&i.SignalName,
		&i.Reason,
		&i.DeclaredAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :exec
DELETE FROM annotation WHERE id = $1
`

func (q *Queries) DeleteAnnotation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnnotation, id)
	return err
}

const listAnnotations = `-- name: ListAnnotations :many
SELECT id, subject_key, signal_name, reason, declared_at
FROM annotation
ORDER BY signal_name, subject_key
`

// A dial is not ranked: no staleness sort and no per-rule count (ADR-0073 §3, §4).
func (q *Queries) ListAnnotations(ctx context.Context) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listAnnotations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKey,
			&i.SignalName,
			&i.Reason,
			&i.DeclaredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
