// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_material.sql

package db

import (
	"context"
)

const countCertificateMaterial = `-- name: CountCertificateMaterial :one
SELECT count(*)::bigint AS captured FROM certificate_material
`

// How many leaf certificates the handshake capture has stored (#881, spec §5, §6.2). The
// More-CT-capabilities card states verification's readout: this is the pool of leaves the
// point-check verifies against CT. Verification keeps no durable result — its logged /
// NOT-logged findings are ephemeral events (#878) — so this captured count is the truthful
// measure of verification's reach. One scalar row always returns.
func (q *Queries) CountCertificateMaterial(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificateMaterial)
	var captured int64
	err := row.Scan(&captured)
	return captured, err
}

const getCertificateMaterial = `-- name: GetCertificateMaterial :one
SELECT fingerprint, der, scts, issuer_spki
FROM certificate_material
WHERE fingerprint = $1
`

// Read one leaf's captured CT inputs back for an on-demand verification re-check (spec §5.4,
// #878): the leaf DER (embedded SCTs ride inside it), the out-of-cert SCT material, and the
// issuer SubjectPublicKeyInfo the precert leaf hash needs. Keyed by the leaf fingerprint.
// Errors with pgx.ErrNoRows when the certificate was never captured — a verification the
// caller reports as unverifiable rather than as not-logged.
func (q *Queries) GetCertificateMaterial(ctx context.Context, fingerprint string) (CertificateMaterial, error) {
	row := q.db.QueryRow(ctx, getCertificateMaterial, fingerprint)
	var i CertificateMaterial
	err := row.Scan(
		&i.Fingerprint,
		&i.Der,
		&i.Scts,
		&i.IssuerSpki,
	)
	return i, err
}

const insertCertificateMaterial = `-- name: InsertCertificateMaterial :exec
INSERT INTO certificate_material (fingerprint, der, scts, issuer_spki)
VALUES ($1, $2, $3, $4)
ON CONFLICT (fingerprint) DO NOTHING
`

type InsertCertificateMaterialParams struct {
	Fingerprint string `json:"fingerprint"`
	Der         []byte `json:"der"`
	Scts        []byte `json:"scts"`
	IssuerSpki  []byte `json:"issuer_spki"`
}

// Capture one leaf certificate's raw CT inputs into the immutable side store (spec
// §5.3): the leaf DER, the out-of-cert SCT material, and the issuer SubjectPublicKeyInfo,
// keyed by the leaf fingerprint. Deduped and immutable — many Endpoints present the same
// certificate, so ON CONFLICT DO NOTHING keeps the first capture and never rewrites a row.
// This writes no facet value; the `certificate` observation still records only the
// fingerprint (ADR-0027).
func (q *Queries) InsertCertificateMaterial(ctx context.Context, arg InsertCertificateMaterialParams) error {
	_, err := q.db.Exec(ctx, insertCertificateMaterial,
		arg.Fingerprint,
		arg.Der,
		arg.Scts,
		arg.IssuerSpki,
	)
	return err
}
