// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_material.sql

package db

import (
	"context"
)

const countCertificateMaterial = `-- name: CountCertificateMaterial :one
SELECT count(*)::bigint AS captured FROM certificate_material
`

func (q *Queries) CountCertificateMaterial(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificateMaterial)
	var captured int64
	err := row.Scan(&captured)
	return captured, err
}

const getCertificateMaterial = `-- name: GetCertificateMaterial :one
SELECT fingerprint, der, scts, issuer_spki
FROM certificate_material
WHERE fingerprint = $1
`

func (q *Queries) GetCertificateMaterial(ctx context.Context, fingerprint string) (CertificateMaterial, error) {
	row := q.db.QueryRow(ctx, getCertificateMaterial, fingerprint)
	var i CertificateMaterial
	err := row.Scan(
		&i.Fingerprint,
		&i.Der,
		&i.Scts,
		&i.IssuerSpki,
	)
	return i, err
}

const insertCertificateMaterial = `-- name: InsertCertificateMaterial :exec
INSERT INTO certificate_material (fingerprint, der, scts, issuer_spki)
VALUES ($1, $2, $3, $4)
ON CONFLICT (fingerprint) DO NOTHING
`

type InsertCertificateMaterialParams struct {
	Fingerprint string `json:"fingerprint"`
	Der         []byte `json:"der"`
	Scts        []byte `json:"scts"`
	IssuerSpki  []byte `json:"issuer_spki"`
}

func (q *Queries) InsertCertificateMaterial(ctx context.Context, arg InsertCertificateMaterialParams) error {
	_, err := q.db.Exec(ctx, insertCertificateMaterial,
		arg.Fingerprint,
		arg.Der,
		arg.Scts,
		arg.IssuerSpki,
	)
	return err
}

const listCertificateMaterialDER = `-- name: ListCertificateMaterialDER :many
SELECT fingerprint, der
FROM certificate_material
WHERE fingerprint = ANY($1::text[])
`

type ListCertificateMaterialDERRow struct {
	Fingerprint string `json:"fingerprint"`
	Der         []byte `json:"der"`
}

func (q *Queries) ListCertificateMaterialDER(ctx context.Context, fingerprints []string) ([]ListCertificateMaterialDERRow, error) {
	rows, err := q.db.Query(ctx, listCertificateMaterialDER, fingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificateMaterialDERRow{}
	for rows.Next() {
		var i ListCertificateMaterialDERRow
		if err := rows.Scan(&i.Fingerprint, &i.Der); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
