// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cold.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const listColdScopeSeedIds = `-- name: ListColdScopeSeedIds :many
SELECT seed_id FROM cold_scan_scope ORDER BY seed_id
`

func (q *Queries) ListColdScopeSeedIds(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listColdScopeSeedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var seed_id int64
		if err := rows.Scan(&seed_id); err != nil {
			return nil, err
		}
		items = append(items, seed_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColdScopeSeeds = `-- name: ListColdScopeSeeds :many
SELECT s.id, s.kind, s.name_domain, s.address_cidr
FROM cold_scan_scope c
JOIN seed s ON s.id = c.seed_id
ORDER BY s.id
`

type ListColdScopeSeedsRow struct {
	ID          int64         `json:"id"`
	Kind        string        `json:"kind"`
	NameDomain  pgtype.Text   `json:"name_domain"`
	AddressCidr *netip.Prefix `json:"address_cidr"`
}

func (q *Queries) ListColdScopeSeeds(ctx context.Context) ([]ListColdScopeSeedsRow, error) {
	rows, err := q.db.Query(ctx, listColdScopeSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListColdScopeSeedsRow{}
	for rows.Next() {
		var i ListColdScopeSeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.NameDomain,
			&i.AddressCidr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optInColdScope = `-- name: OptInColdScope :one
WITH enrolled AS (
    INSERT INTO cold_scan_scope (seed_id, created_by)
    VALUES ($1, $2)
    ON CONFLICT (seed_id) DO NOTHING
    RETURNING seed_id
)
SELECT s.address_cidr, s.name_domain
FROM enrolled e
JOIN seed s ON s.id = e.seed_id
`

type OptInColdScopeParams struct {
	SeedID    int64 `json:"seed_id"`
	CreatedBy int64 `json:"created_by"`
}

type OptInColdScopeRow struct {
	AddressCidr *netip.Prefix `json:"address_cidr"`
	NameDomain  pgtype.Text   `json:"name_domain"`
}

// A data-modifying CTE fires on its own, so the SELECT need only read the scope back.
// The scope rides the enrolment's own RETURNING, so a repeat opt-in returns nothing.
func (q *Queries) OptInColdScope(ctx context.Context, arg OptInColdScopeParams) (OptInColdScopeRow, error) {
	row := q.db.QueryRow(ctx, optInColdScope, arg.SeedID, arg.CreatedBy)
	var i OptInColdScopeRow
	err := row.Scan(&i.AddressCidr, &i.NameDomain)
	return i, err
}

const optOutColdScope = `-- name: OptOutColdScope :one
WITH withdrawn AS (
    DELETE FROM cold_scan_scope WHERE seed_id = $1
    RETURNING seed_id
)
SELECT s.address_cidr, s.name_domain
FROM withdrawn w
JOIN seed s ON s.id = w.seed_id
`

type OptOutColdScopeRow struct {
	AddressCidr *netip.Prefix `json:"address_cidr"`
	NameDomain  pgtype.Text   `json:"name_domain"`
}

// The scope rides the withdrawal's own RETURNING, so an unenrolled scope returns nothing.
func (q *Queries) OptOutColdScope(ctx context.Context, seedID int64) (OptOutColdScopeRow, error) {
	row := q.db.QueryRow(ctx, optOutColdScope, seedID)
	var i OptOutColdScopeRow
	err := row.Scan(&i.AddressCidr, &i.NameDomain)
	return i, err
}

const syncColdScanEnabled = `-- name: SyncColdScanEnabled :exec
UPDATE scan
SET enabled = EXISTS (SELECT 1 FROM cold_scan_scope)
WHERE kind = 'cold'
`

func (q *Queries) SyncColdScanEnabled(ctx context.Context) error {
	_, err := q.db.Exec(ctx, syncColdScanEnabled)
	return err
}
