// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crtsh.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cTLastBatchAdmitCount = `-- name: CTLastBatchAdmitCount :one
SELECT COALESCE((
    SELECT count(*)
    FROM admitted_name an
    WHERE an.batch_id = (
        SELECT b.id FROM batch b
        WHERE b.kind = 'ct'
        ORDER BY b.created_at DESC, b.id DESC
        LIMIT 1
    )
), 0)::bigint AS names
`

func (q *Queries) CTLastBatchAdmitCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, cTLastBatchAdmitCount)
	var names int64
	err := row.Scan(&names)
	return names, err
}

const insertAdmittedName = `-- name: InsertAdmittedName :exec
INSERT INTO admitted_name (name, source, seed_id, batch_id)
VALUES ($1, $2, $3, $4)
`

type InsertAdmittedNameParams struct {
	Name    string `json:"name"`
	Source  string `json:"source"`
	SeedID  int64  `json:"seed_id"`
	BatchID int64  `json:"batch_id"`
}

func (q *Queries) InsertAdmittedName(ctx context.Context, arg InsertAdmittedNameParams) error {
	_, err := q.db.Exec(ctx, insertAdmittedName,
		arg.Name,
		arg.Source,
		arg.SeedID,
		arg.BatchID,
	)
	return err
}

const listAdmittedNames = `-- name: ListAdmittedNames :many
SELECT DISTINCT name
FROM admitted_name
ORDER BY name
`

// An append-only source re-admits the same names on every poll.
func (q *Queries) ListAdmittedNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdmittedNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmittedNamesOutsideSeed = `-- name: ListAdmittedNamesOutsideSeed :many
SELECT DISTINCT name
FROM admitted_name
WHERE seed_id <> $1
ORDER BY name
`

func (q *Queries) ListAdmittedNamesOutsideSeed(ctx context.Context, seedID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdmittedNamesOutsideSeed, seedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameSeeds = `-- name: ListNameSeeds :many
SELECT id, name_domain
FROM seed
WHERE kind = 'name' AND name_domain IS NOT NULL
ORDER BY id
`

type ListNameSeedsRow struct {
	ID         int64       `json:"id"`
	NameDomain pgtype.Text `json:"name_domain"`
}

func (q *Queries) ListNameSeeds(ctx context.Context) ([]ListNameSeedsRow, error) {
	rows, err := q.db.Query(ctx, listNameSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNameSeedsRow{}
	for rows.Next() {
		var i ListNameSeedsRow
		if err := rows.Scan(&i.ID, &i.NameDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveCTSlot = `-- name: ReserveCTSlot :one
WITH reserved AS (
    UPDATE ct_throttle
    SET next_free_at = GREATEST(next_free_at, now())
        + make_interval(secs => $1::double precision)
    WHERE source = $2
    RETURNING next_free_at
)
SELECT (next_free_at
    - make_interval(secs => $1::double precision))::timestamptz AS slot_at
FROM reserved
`

type ReserveCTSlotParams struct {
	IntervalSeconds float64 `json:"interval_seconds"`
	Source          string  `json:"source"`
}

func (q *Queries) ReserveCTSlot(ctx context.Context, arg ReserveCTSlotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, reserveCTSlot, arg.IntervalSeconds, arg.Source)
	var slot_at pgtype.Timestamptz
	err := row.Scan(&slot_at)
	return slot_at, err
}
