// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crtsh.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdmittedName = `-- name: InsertAdmittedName :exec
INSERT INTO admitted_name (name, source, seed_id, batch_id)
VALUES ($1, $2, $3, $4)
`

type InsertAdmittedNameParams struct {
	Name    string `json:"name"`
	Source  string `json:"source"`
	SeedID  int64  `json:"seed_id"`
	BatchID int64  `json:"batch_id"`
}

// One CT admission (ADR-0027, ADR-0106): a Name a crt.sh Batch admitted, carrying
// the Batch that admitted it (the Citation hop) and the covering name-scope Seed
// the chain terminates at. No observation, no facet, no timeline — admission is
// not membership (ADR-0096 §5).
func (q *Queries) InsertAdmittedName(ctx context.Context, arg InsertAdmittedNameParams) error {
	_, err := q.db.Exec(ctx, insertAdmittedName,
		arg.Name,
		arg.Source,
		arg.SeedID,
		arg.BatchID,
	)
	return err
}

const listAdmittedNames = `-- name: ListAdmittedNames :many
SELECT DISTINCT name
FROM admitted_name
ORDER BY name
`

// The distinct CT-admitted names the dns Scan also resolves (ADR-0107, wave-1).
// A source that admits without observing leaves an admitted_name row per Name it
// named; unioned into the dns Scan's resolution set, each acquires a resolution
// timeline from our own resolver and becomes a measured member or leaves by Name
// Error (ADR-0027, ADR-0096 §1). DISTINCT because an append-only source re-admits
// the same names on every poll; unconditional of the source's current enablement,
// since resolution is the dns Scan's act and a Name leaves only by measurement.
func (q *Queries) ListAdmittedNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdmittedNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameSeeds = `-- name: ListNameSeeds :many
SELECT id, name_domain
FROM seed
WHERE kind = 'name' AND name_domain IS NOT NULL
ORDER BY id
`

type ListNameSeedsRow struct {
	ID         int64       `json:"id"`
	NameDomain pgtype.Text `json:"name_domain"`
}

// The name-scope Seeds the CT Scan queries — id and registrable domain, one
// crt.sh query per row (ADR-0106). Distinct from ListNameSeedDomains (domains
// only, for the dns Scan): a CT admission's Citation chain terminates at the Seed,
// so its id travels with the domain (ADR-0027).
func (q *Queries) ListNameSeeds(ctx context.Context) ([]ListNameSeedsRow, error) {
	rows, err := q.db.Query(ctx, listNameSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNameSeedsRow{}
	for rows.Next() {
		var i ListNameSeedsRow
		if err := rows.Scan(&i.ID, &i.NameDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveCTSlot = `-- name: ReserveCTSlot :one
WITH reserved AS (
    UPDATE crtsh_throttle
    SET next_free_at = GREATEST(next_free_at, now())
        + make_interval(secs => $1::double precision)
    WHERE id = 1
    RETURNING next_free_at
)
SELECT (next_free_at
    - make_interval(secs => $1::double precision))::timestamptz AS slot_at
FROM reserved
`

// Atomically claim the next free slot for one crt.sh fetch, instance-wide
// (ADR-0005: the 5 req/min throttle is per-source across the whole instance, in
// Postgres, not worker memory). GREATEST(next_free_at, now()) is this request's
// slot; next_free_at advances one interval past it, so concurrent workers each
// reserve a distinct, correctly-spaced slot. The caller waits until slot_at
// before going on the wire.
func (q *Queries) ReserveCTSlot(ctx context.Context, intervalSeconds float64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, reserveCTSlot, intervalSeconds)
	var slot_at pgtype.Timestamptz
	err := row.Scan(&slot_at)
	return slot_at, err
}
