// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ct_reliability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cTReliabilityWindow = `-- name: CTReliabilityWindow :one
WITH w AS (
    SELECT ok, latency_ms, empty, observed_at
    FROM ct_reliability_sample
    WHERE source = $1
    ORDER BY observed_at DESC, id DESC
    LIMIT $2
)
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (WHERE ok)::bigint AS successes,
    count(*) FILTER (WHERE ok AND empty)::bigint AS empties,
    COALESCE(percentile_disc(0.95) WITHIN GROUP (ORDER BY latency_ms), 0)::bigint AS p95_latency_ms,
    MAX(observed_at)::timestamptz AS last_at
FROM w
`

type CTReliabilityWindowParams struct {
	Source     string `json:"source"`
	SampleSize int32  `json:"sample_size"`
}

type CTReliabilityWindowRow struct {
	Total        int64              `json:"total"`
	Successes    int64              `json:"successes"`
	Empties      int64              `json:"empties"`
	P95LatencyMs int64              `json:"p95_latency_ms"`
	LastAt       pgtype.Timestamptz `json:"last_at"`
}

func (q *Queries) CTReliabilityWindow(ctx context.Context, arg CTReliabilityWindowParams) (CTReliabilityWindowRow, error) {
	row := q.db.QueryRow(ctx, cTReliabilityWindow, arg.Source, arg.SampleSize)
	var i CTReliabilityWindowRow
	err := row.Scan(
		&i.Total,
		&i.Successes,
		&i.Empties,
		&i.P95LatencyMs,
		&i.LastAt,
	)
	return i, err
}

const insertCTReliabilitySample = `-- name: InsertCTReliabilitySample :exec
INSERT INTO ct_reliability_sample (source, ok, latency_ms, empty)
VALUES ($1, $2, $3, $4)
`

type InsertCTReliabilitySampleParams struct {
	Source    string `json:"source"`
	Ok        bool   `json:"ok"`
	LatencyMs int64  `json:"latency_ms"`
	Empty     bool   `json:"empty"`
}

func (q *Queries) InsertCTReliabilitySample(ctx context.Context, arg InsertCTReliabilitySampleParams) error {
	_, err := q.db.Exec(ctx, insertCTReliabilitySample,
		arg.Source,
		arg.Ok,
		arg.LatencyMs,
		arg.Empty,
	)
	return err
}

const trimCTReliabilitySamples = `-- name: TrimCTReliabilitySamples :exec
DELETE FROM ct_reliability_sample AS s
WHERE s.source = $1
  AND s.id NOT IN (
      SELECT keep.id FROM ct_reliability_sample AS keep
      WHERE keep.source = $1
      ORDER BY keep.observed_at DESC, keep.id DESC
      LIMIT $2
  )
`

type TrimCTReliabilitySamplesParams struct {
	Source    string `json:"source"`
	KeepCount int32  `json:"keep_count"`
}

func (q *Queries) TrimCTReliabilitySamples(ctx context.Context, arg TrimCTReliabilitySamplesParams) error {
	_, err := q.db.Exec(ctx, trimCTReliabilitySamples, arg.Source, arg.KeepCount)
	return err
}
