// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custody.sql

package db

import (
	"context"
)

const setCustodyExtension = `-- name: SetCustodyExtension :exec
UPDATE seed
SET custody_extension = $2
WHERE id = $1 AND kind = 'name'
`

type SetCustodyExtensionParams struct {
	ID               int64 `json:"id"`
	CustodyExtension bool  `json:"custody_extension"`
}

// The seed CHECK rejects a true extension on an address scope, so an unguarded declare errors.
func (q *Queries) SetCustodyExtension(ctx context.Context, arg SetCustodyExtensionParams) error {
	_, err := q.db.Exec(ctx, setCustodyExtension, arg.ID, arg.CustodyExtension)
	return err
}
