// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDispatchProgress = `-- name: ListDispatchProgress :many
SELECT
    d.id       AS dispatch_id,
    d.scan_id  AS scan_id,
    s.kind     AS scan_kind,
    d.created_at,
    count(j.id)                                 AS total,
    count(*) FILTER (WHERE j.state = 'ready')   AS ready,
    count(*) FILTER (WHERE j.state = 'running') AS running,
    count(*) FILTER (WHERE j.state = 'done')    AS done,
    count(*) FILTER (WHERE j.state = 'dead')    AS dead,
    count(*) FILTER (WHERE j.state = 'retried') AS retried
FROM dispatch d
JOIN scan s ON s.id = d.scan_id
LEFT JOIN queue_job j ON j.dispatch_id = d.id
GROUP BY d.id, d.scan_id, s.kind, d.created_at
ORDER BY d.id DESC
LIMIT $1
`

type ListDispatchProgressRow struct {
	DispatchID int64              `json:"dispatch_id"`
	ScanID     int64              `json:"scan_id"`
	ScanKind   string             `json:"scan_kind"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Total      int64              `json:"total"`
	Ready      int64              `json:"ready"`
	Running    int64              `json:"running"`
	Done       int64              `json:"done"`
	Dead       int64              `json:"dead"`
	Retried    int64              `json:"retried"`
}

// The recent Dispatches with their per-state job counts, newest first — the read
// behind the Scans monitor (#245). Dispatch, queue_job and batch are Operational:
// they record what the system did, never what is true of the estate, so this read
// is barred from the comparison path by construction (CONTEXT.md, ADR-0041) and the
// drift engine never sees it. A retry enqueues a fresh job and marks the old one
// 'retried' (internal/queue/worker.go), so 'retried' rows are superseded attempts:
// the live work is total − retried, of which done + dead are complete and
// ready + running are still in flight. The LEFT JOIN keeps a Dispatch whose jobs
// were retired to NULL by the Dispatch sweep (ADR-0041) — it counts zero jobs
// rather than vanishing.
// created_at is the instant the fan-out actually happened, which is what "when did
// this scan start" means to an operator; scheduled_time is the cadence tick the
// Dispatch is idempotent on, not a wall-clock start, so it is not read here.
func (q *Queries) ListDispatchProgress(ctx context.Context, limit int32) ([]ListDispatchProgressRow, error) {
	rows, err := q.db.Query(ctx, listDispatchProgress, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDispatchProgressRow{}
	for rows.Next() {
		var i ListDispatchProgressRow
		if err := rows.Scan(
			&i.DispatchID,
			&i.ScanID,
			&i.ScanKind,
			&i.CreatedAt,
			&i.Total,
			&i.Ready,
			&i.Running,
			&i.Done,
			&i.Dead,
			&i.Retried,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForDispatch = `-- name: ListJobsForDispatch :many
SELECT
    j.id,
    j.kind,
    j.state,
    j.attempt,
    j.max_attempts,
    j.vantage_id,
    v.name    AS vantage_name,
    j.batch_id,
    b.outcome AS batch_outcome
FROM queue_job j
LEFT JOIN vantage v ON v.id = j.vantage_id
LEFT JOIN batch b ON b.id = j.batch_id
WHERE j.dispatch_id = $1
ORDER BY j.id
`

type ListJobsForDispatchRow struct {
	ID           int64       `json:"id"`
	Kind         string      `json:"kind"`
	State        string      `json:"state"`
	Attempt      int32       `json:"attempt"`
	MaxAttempts  int32       `json:"max_attempts"`
	VantageID    pgtype.Int8 `json:"vantage_id"`
	VantageName  pgtype.Text `json:"vantage_name"`
	BatchID      pgtype.Int8 `json:"batch_id"`
	BatchOutcome pgtype.Text `json:"batch_outcome"`
}

// The per-job detail for one Dispatch — the progress drill-down (#245). Ordered by
// id so a retried attempt reads immediately before the fresh job that replaced it.
// A job's Batch outcome is NULL until the job reaches a terminal state, since a
// Batch is written only at completion or dead-letter (db/migrations/18804); the
// Vantage name is NULL for the zone Scan, which has no vantage choice at all.
func (q *Queries) ListJobsForDispatch(ctx context.Context, dispatchID pgtype.Int8) ([]ListJobsForDispatchRow, error) {
	rows, err := q.db.Query(ctx, listJobsForDispatch, dispatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsForDispatchRow{}
	for rows.Next() {
		var i ListJobsForDispatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.VantageID,
			&i.VantageName,
			&i.BatchID,
			&i.BatchOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
