// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge_fanout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEdgeFanoutObservation = `-- name: InsertEdgeFanoutObservation :exec
INSERT INTO edge_fanout_observation (batch_id, address, outcome, fingerprint, measured_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEdgeFanoutObservationParams struct {
	BatchID     int64              `json:"batch_id"`
	Address     string             `json:"address"`
	Outcome     string             `json:"outcome"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
	MeasuredAt  pgtype.Timestamptz `json:"measured_at"`
}

// Record one measured candidate edge on its Batch (ADR-0129 §6, #983): the address
// measured, the leaf's closed outcome, the served certificate's fingerprint on
// `presented` alone, and the handshake instant. One row per measured address.
//
// It writes no facet value and opens no timeline — this leaf decides membership, so
// there is no subject for the `observation` table's four-part key to name. The
// certificate DER rides the same Batch into `certificate_material` under the same
// fingerprint, so the SAN set the fan-out reduction counts is derived at read (#984)
// and never copied here. An address the Scan did not measure carries no row at all:
// an absence is never a value, and the missing row is what the veto reads as
// *measurement pending* (#985).
func (q *Queries) InsertEdgeFanoutObservation(ctx context.Context, arg InsertEdgeFanoutObservationParams) error {
	_, err := q.db.Exec(ctx, insertEdgeFanoutObservation,
		arg.BatchID,
		arg.Address,
		arg.Outcome,
		arg.Fingerprint,
		arg.MeasuredAt,
	)
	return err
}
