// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge_fanout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEdgeFanoutObservation = `-- name: InsertEdgeFanoutObservation :exec
INSERT INTO edge_fanout_observation (batch_id, address, outcome, fingerprint, measured_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEdgeFanoutObservationParams struct {
	BatchID     int64              `json:"batch_id"`
	Address     string             `json:"address"`
	Outcome     string             `json:"outcome"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
	MeasuredAt  pgtype.Timestamptz `json:"measured_at"`
}

func (q *Queries) InsertEdgeFanoutObservation(ctx context.Context, arg InsertEdgeFanoutObservationParams) error {
	_, err := q.db.Exec(ctx, insertEdgeFanoutObservation,
		arg.BatchID,
		arg.Address,
		arg.Outcome,
		arg.Fingerprint,
		arg.MeasuredAt,
	)
	return err
}

const listEdgeFanoutMeasurements = `-- name: ListEdgeFanoutMeasurements :many
SELECT DISTINCT ON (o.address)
    o.address,
    o.outcome,
    o.fingerprint
FROM edge_fanout_observation o
ORDER BY o.address, o.measured_at DESC, o.id DESC
`

type ListEdgeFanoutMeasurementsRow struct {
	Address     string      `json:"address"`
	Outcome     string      `json:"outcome"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) ListEdgeFanoutMeasurements(ctx context.Context) ([]ListEdgeFanoutMeasurementsRow, error) {
	rows, err := q.db.Query(ctx, listEdgeFanoutMeasurements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEdgeFanoutMeasurementsRow{}
	for rows.Next() {
		var i ListEdgeFanoutMeasurementsRow
		if err := rows.Scan(&i.Address, &i.Outcome, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeFanoutMeasurementsOver = `-- name: ListEdgeFanoutMeasurementsOver :many
SELECT DISTINCT ON (o.address)
    o.address,
    o.outcome,
    o.fingerprint
FROM edge_fanout_observation o
WHERE o.address = ANY($1::text[])
ORDER BY o.address, o.measured_at DESC, o.id DESC
`

type ListEdgeFanoutMeasurementsOverRow struct {
	Address     string      `json:"address"`
	Outcome     string      `json:"outcome"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) ListEdgeFanoutMeasurementsOver(ctx context.Context, addresses []string) ([]ListEdgeFanoutMeasurementsOverRow, error) {
	rows, err := q.db.Query(ctx, listEdgeFanoutMeasurementsOver, addresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEdgeFanoutMeasurementsOverRow{}
	for rows.Next() {
		var i ListEdgeFanoutMeasurementsOverRow
		if err := rows.Scan(&i.Address, &i.Outcome, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
