// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exclusions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddressExclusion = `-- name: CreateAddressExclusion :one
INSERT INTO exclusion (kind, address_cidr, created_by)
VALUES ('address', $1, $2)
RETURNING id, kind, name, address_cidr, created_by, created_at, proposal_id
`

type CreateAddressExclusionParams struct {
	AddressCidr *netip.Prefix `json:"address_cidr"`
	CreatedBy   pgtype.Int8   `json:"created_by"`
}

// proposal_id stays NULL, so an undo may not lift what the operator declared (#1799).
func (q *Queries) CreateAddressExclusion(ctx context.Context, arg CreateAddressExclusionParams) (Exclusion, error) {
	row := q.db.QueryRow(ctx, createAddressExclusion, arg.AddressCidr, arg.CreatedBy)
	var i Exclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.AddressCidr,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProposalID,
	)
	return i, err
}

const createDeclinedProposalExclusion = `-- name: CreateDeclinedProposalExclusion :one
INSERT INTO exclusion (kind, address_cidr, created_by, proposal_id)
VALUES ('address', $1, $2, $3)
RETURNING id, kind, name, address_cidr, created_by, created_at, proposal_id
`

type CreateDeclinedProposalExclusionParams struct {
	AddressCidr *netip.Prefix `json:"address_cidr"`
	CreatedBy   pgtype.Int8   `json:"created_by"`
	ProposalID  pgtype.Int8   `json:"proposal_id"`
}

// The decline names the proposal it answered, which is the row the undo may lift (#1799).
func (q *Queries) CreateDeclinedProposalExclusion(ctx context.Context, arg CreateDeclinedProposalExclusionParams) (Exclusion, error) {
	row := q.db.QueryRow(ctx, createDeclinedProposalExclusion, arg.AddressCidr, arg.CreatedBy, arg.ProposalID)
	var i Exclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.AddressCidr,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProposalID,
	)
	return i, err
}

const createNameExclusion = `-- name: CreateNameExclusion :one
INSERT INTO exclusion (kind, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, kind, name, address_cidr, created_by, created_at, proposal_id
`

type CreateNameExclusionParams struct {
	Kind      string      `json:"kind"`
	Name      pgtype.Text `json:"name"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateNameExclusion(ctx context.Context, arg CreateNameExclusionParams) (Exclusion, error) {
	row := q.db.QueryRow(ctx, createNameExclusion, arg.Kind, arg.Name, arg.CreatedBy)
	var i Exclusion
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.AddressCidr,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ProposalID,
	)
	return i, err
}

const deleteExclusion = `-- name: DeleteExclusion :one
DELETE FROM exclusion WHERE id = $1
RETURNING kind, name, address_cidr
`

type DeleteExclusionRow struct {
	Kind        string        `json:"kind"`
	Name        pgtype.Text   `json:"name"`
	AddressCidr *netip.Prefix `json:"address_cidr"`
}

// The scope rides the act's own RETURNING, so a separate read cannot leave the Act blank.
func (q *Queries) DeleteExclusion(ctx context.Context, id int64) (DeleteExclusionRow, error) {
	row := q.db.QueryRow(ctx, deleteExclusion, id)
	var i DeleteExclusionRow
	err := row.Scan(&i.Kind, &i.Name, &i.AddressCidr)
	return i, err
}

const deleteUnclaimedAddressExclusion = `-- name: DeleteUnclaimedAddressExclusion :one
WITH claim AS (
    SELECT 1 FROM proposal p
    WHERE p.status = 'declined' AND p.address_cidr = $1
), kept AS (
    SELECT proposal_id FROM exclusion
    WHERE kind = 'address' AND address_cidr = $1
), lift AS (
    DELETE FROM exclusion
    WHERE kind = 'address' AND address_cidr = $1
      -- A NULL proposal_id is a standing declaration, which no decline may lift (#1799).
      AND proposal_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM claim)
    RETURNING id
)
SELECT
    EXISTS (SELECT 1 FROM kept WHERE kept.proposal_id IS NULL) AS declared_by_hand,
    -- The two reasons a row stays are independent, so the caller composes them (#1799).
    EXISTS (SELECT 1 FROM claim, kept) AS still_claimed
`

type DeleteUnclaimedAddressExclusionRow struct {
	DeclaredByHand bool `json:"declared_by_hand"`
	StillClaimed   bool `json:"still_claimed"`
}

// A data-modifying CTE fires on its own, so nothing need select from lift (#1777).
// Every arm reads one snapshot, so kept is the row as it stood before lift (#1777).
func (q *Queries) DeleteUnclaimedAddressExclusion(ctx context.Context, addressCidr netip.Prefix) (DeleteUnclaimedAddressExclusionRow, error) {
	row := q.db.QueryRow(ctx, deleteUnclaimedAddressExclusion, addressCidr)
	var i DeleteUnclaimedAddressExclusionRow
	err := row.Scan(&i.DeclaredByHand, &i.StillClaimed)
	return i, err
}

const listAddressExclusionCidrs = `-- name: ListAddressExclusionCidrs :many
SELECT address_cidr
FROM exclusion
WHERE kind = 'address' AND address_cidr IS NOT NULL
ORDER BY id
`

func (q *Queries) ListAddressExclusionCidrs(ctx context.Context) ([]*netip.Prefix, error) {
	rows, err := q.db.Query(ctx, listAddressExclusionCidrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*netip.Prefix{}
	for rows.Next() {
		var address_cidr *netip.Prefix
		if err := rows.Scan(&address_cidr); err != nil {
			return nil, err
		}
		items = append(items, address_cidr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExclusions = `-- name: ListExclusions :many
SELECT e.id, e.kind, e.name, e.address_cidr, e.created_by, e.created_at, e.proposal_id
FROM exclusion e
ORDER BY e.created_at DESC, e.id DESC
`

func (q *Queries) ListExclusions(ctx context.Context) ([]Exclusion, error) {
	rows, err := q.db.Query(ctx, listExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exclusion{}
	for rows.Next() {
		var i Exclusion
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.AddressCidr,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProposalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
