// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heartbeat.sql

package db

import (
	"context"
)

const recordHeartbeat = `-- name: RecordHeartbeat :one
INSERT INTO heartbeat DEFAULT VALUES
RETURNING id, checked_at
`

func (q *Queries) RecordHeartbeat(ctx context.Context) (Heartbeat, error) {
	row := q.db.QueryRow(ctx, recordHeartbeat)
	var i Heartbeat
	err := row.Scan(&i.ID, &i.CheckedAt)
	return i, err
}
