// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package db

import (
	"context"
)

const getInstanceHealth = `-- name: GetInstanceHealth :one
SELECT
    pg_database_size(current_database())::bigint AS db_size_bytes,
    current_setting('server_version')::text      AS server_version
`

type GetInstanceHealthRow struct {
	DbSizeBytes   int64  `json:"db_size_bytes"`
	ServerVersion string `json:"server_version"`
}

// The instance-health tab's live database facts (#633, WORK-ORDER-DOGFOOD-R1 item 3):
// the size of this deployment's database and its Postgres server version, read straight
// off the running server — pg_database_size over the current database, and the
// server_version setting. Both are Operational host facts; this touches no estate corpus.
func (q *Queries) GetInstanceHealth(ctx context.Context) (GetInstanceHealthRow, error) {
	row := q.db.QueryRow(ctx, getInstanceHealth)
	var i GetInstanceHealthRow
	err := row.Scan(&i.DbSizeBytes, &i.ServerVersion)
	return i, err
}
