// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIntegrationState = `-- name: DeleteIntegrationState :exec
DELETE FROM integration_state
WHERE slug = $1
`

func (q *Queries) DeleteIntegrationState(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteIntegrationState, slug)
	return err
}

const getIntegrationChannel = `-- name: GetIntegrationChannel :one
SELECT channel_id
FROM integration_state
WHERE slug = $1
`

func (q *Queries) GetIntegrationChannel(ctx context.Context, slug string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getIntegrationChannel, slug)
	var channel_id pgtype.Int8
	err := row.Scan(&channel_id)
	return channel_id, err
}

const listIntegrationStates = `-- name: ListIntegrationStates :many
SELECT slug, state, channel_id
FROM integration_state
`

func (q *Queries) ListIntegrationStates(ctx context.Context) ([]IntegrationState, error) {
	rows, err := q.db.Query(ctx, listIntegrationStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationState{}
	for rows.Next() {
		var i IntegrationState
		if err := rows.Scan(&i.Slug, &i.State, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntegrationChannel = `-- name: SetIntegrationChannel :exec
UPDATE integration_state
SET channel_id = $2
WHERE slug = $1
`

type SetIntegrationChannelParams struct {
	Slug      string      `json:"slug"`
	ChannelID pgtype.Int8 `json:"channel_id"`
}

func (q *Queries) SetIntegrationChannel(ctx context.Context, arg SetIntegrationChannelParams) error {
	_, err := q.db.Exec(ctx, setIntegrationChannel, arg.Slug, arg.ChannelID)
	return err
}

const upsertIntegrationState = `-- name: UpsertIntegrationState :one
INSERT INTO integration_state (slug, state)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
    SET state = EXCLUDED.state
RETURNING slug, state, channel_id
`

type UpsertIntegrationStateParams struct {
	Slug  string `json:"slug"`
	State string `json:"state"`
}

func (q *Queries) UpsertIntegrationState(ctx context.Context, arg UpsertIntegrationStateParams) (IntegrationState, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationState, arg.Slug, arg.State)
	var i IntegrationState
	err := row.Scan(&i.Slug, &i.State, &i.ChannelID)
	return i, err
}
