// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvite = `-- name: ConsumeInvite :exec
UPDATE invite SET consumed_at = $2, accepted_account_id = $3 WHERE id = $1
`

type ConsumeInviteParams struct {
	ID                int64              `json:"id"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	AcceptedAccountID pgtype.Int8        `json:"accepted_account_id"`
}

func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) error {
	_, err := q.db.Exec(ctx, consumeInvite, arg.ID, arg.ConsumedAt, arg.AcceptedAccountID)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invite (token_hash, role, invited_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, role, invited_by, created_at, expires_at, consumed_at, accepted_account_id
`

type CreateInviteParams struct {
	TokenHash string             `json:"token_hash"`
	Role      string             `json:"role"`
	InvitedBy pgtype.Int8        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TokenHash,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AcceptedAccountID,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, token_hash, role, invited_by, created_at, expires_at, consumed_at, accepted_account_id
FROM invite
WHERE token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AcceptedAccountID,
	)
	return i, err
}
