// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE queue_job SET state = 'running'
WHERE id = (
    SELECT id FROM queue_job
    WHERE state = 'ready' AND run_after <= now()
    ORDER BY run_after, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, scan_id, vantage_id, dispatch_id, kind, spec, attempted_scope,
          offers, attempt, max_attempts
`

type ClaimJobRow struct {
	ID             int64       `json:"id"`
	ScanID         int64       `json:"scan_id"`
	VantageID      pgtype.Int8 `json:"vantage_id"`
	DispatchID     pgtype.Int8 `json:"dispatch_id"`
	Kind           string      `json:"kind"`
	Spec           []byte      `json:"spec"`
	AttemptedScope []byte      `json:"attempted_scope"`
	Offers         []byte      `json:"offers"`
	Attempt        int32       `json:"attempt"`
	MaxAttempts    int32       `json:"max_attempts"`
}

// The Postgres-backed claim: FOR UPDATE SKIP LOCKED over ready jobs whose
// run_after has passed, oldest first, marking the winner running in one
// statement so two workers never claim the same job.
func (q *Queries) ClaimJob(ctx context.Context) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.VantageID,
		&i.DispatchID,
		&i.Kind,
		&i.Spec,
		&i.AttemptedScope,
		&i.Offers,
		&i.Attempt,
		&i.MaxAttempts,
	)
	return i, err
}

const countObservationsForScan = `-- name: CountObservationsForScan :one
SELECT count(*)
FROM observation o
JOIN batch b ON b.id = o.batch_id
WHERE b.scan_id = $1
`

func (q *Queries) CountObservationsForScan(ctx context.Context, scanID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countObservationsForScan, scanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO queue_job (
    scan_id, vantage_id, dispatch_id, kind, spec, attempted_scope, offers,
    attempt, max_attempts, run_after
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type EnqueueJobParams struct {
	ScanID         int64              `json:"scan_id"`
	VantageID      pgtype.Int8        `json:"vantage_id"`
	DispatchID     pgtype.Int8        `json:"dispatch_id"`
	Kind           string             `json:"kind"`
	Spec           []byte             `json:"spec"`
	AttemptedScope []byte             `json:"attempted_scope"`
	Offers         []byte             `json:"offers"`
	Attempt        int32              `json:"attempt"`
	MaxAttempts    int32              `json:"max_attempts"`
	RunAfter       pgtype.Timestamptz `json:"run_after"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ScanID,
		arg.VantageID,
		arg.DispatchID,
		arg.Kind,
		arg.Spec,
		arg.AttemptedScope,
		arg.Offers,
		arg.Attempt,
		arg.MaxAttempts,
		arg.RunAfter,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getScanByKind = `-- name: GetScanByKind :one
SELECT id, kind, enabled, cadence_seconds, created_at
FROM scan
WHERE kind = $1
`

func (q *Queries) GetScanByKind(ctx context.Context, kind string) (Scan, error) {
	row := q.db.QueryRow(ctx, getScanByKind, kind)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Enabled,
		&i.CadenceSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const insertBatch = `-- name: InsertBatch :one
INSERT INTO batch (
    scan_id, dispatch_id, vantage_id, kind, outcome, offers, recorded_scope
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertBatchParams struct {
	ScanID        int64       `json:"scan_id"`
	DispatchID    pgtype.Int8 `json:"dispatch_id"`
	VantageID     pgtype.Int8 `json:"vantage_id"`
	Kind          string      `json:"kind"`
	Outcome       string      `json:"outcome"`
	Offers        []byte      `json:"offers"`
	RecordedScope []byte      `json:"recorded_scope"`
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBatch,
		arg.ScanID,
		arg.DispatchID,
		arg.VantageID,
		arg.Kind,
		arg.Outcome,
		arg.Offers,
		arg.RecordedScope,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observation (
    batch_id, facet, subject_kind, subject_key, discriminator, vantage_id,
    source, value, observed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertObservationParams struct {
	BatchID       int64              `json:"batch_id"`
	Facet         string             `json:"facet"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.Exec(ctx, insertObservation,
		arg.BatchID,
		arg.Facet,
		arg.SubjectKind,
		arg.SubjectKey,
		arg.Discriminator,
		arg.VantageID,
		arg.Source,
		arg.Value,
		arg.ObservedAt,
	)
	return err
}

const listEnabledScans = `-- name: ListEnabledScans :many
SELECT id, kind, enabled, cadence_seconds, created_at
FROM scan
WHERE enabled = TRUE
ORDER BY id
`

func (q *Queries) ListEnabledScans(ctx context.Context) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listEnabledScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scan{}
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Enabled,
			&i.CadenceSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameSeedDomains = `-- name: ListNameSeedDomains :many
SELECT name_domain
FROM seed
WHERE kind = 'name' AND name_domain IS NOT NULL
ORDER BY name_domain
`

func (q *Queries) ListNameSeedDomains(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listNameSeedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var name_domain pgtype.Text
		if err := rows.Scan(&name_domain); err != nil {
			return nil, err
		}
		items = append(items, name_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentObservations = `-- name: ListRecentObservations :many
SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
       o.source, o.value, o.observed_at, o.batch_id
FROM observation o
ORDER BY o.id DESC
LIMIT $1
`

type ListRecentObservationsRow struct {
	ID            int64              `json:"id"`
	Facet         string             `json:"facet"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Discriminator string             `json:"discriminator"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	BatchID       int64              `json:"batch_id"`
}

func (q *Queries) ListRecentObservations(ctx context.Context, limit int32) ([]ListRecentObservationsRow, error) {
	rows, err := q.db.Query(ctx, listRecentObservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentObservationsRow{}
	for rows.Next() {
		var i ListRecentObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Facet,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Discriminator,
			&i.Source,
			&i.Value,
			&i.ObservedAt,
			&i.BatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVantages = `-- name: ListVantages :many
SELECT id, name, class, resolver, created_at
FROM vantage
ORDER BY id
`

func (q *Queries) ListVantages(ctx context.Context) ([]Vantage, error) {
	rows, err := q.db.Query(ctx, listVantages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vantage{}
	for rows.Next() {
		var i Vantage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Class,
			&i.Resolver,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDead = `-- name: MarkJobDead :exec
UPDATE queue_job SET state = 'dead', batch_id = $2 WHERE id = $1
`

type MarkJobDeadParams struct {
	ID      int64       `json:"id"`
	BatchID pgtype.Int8 `json:"batch_id"`
}

func (q *Queries) MarkJobDead(ctx context.Context, arg MarkJobDeadParams) error {
	_, err := q.db.Exec(ctx, markJobDead, arg.ID, arg.BatchID)
	return err
}

const markJobDone = `-- name: MarkJobDone :exec
UPDATE queue_job SET state = 'done', batch_id = $2 WHERE id = $1
`

type MarkJobDoneParams struct {
	ID      int64       `json:"id"`
	BatchID pgtype.Int8 `json:"batch_id"`
}

func (q *Queries) MarkJobDone(ctx context.Context, arg MarkJobDoneParams) error {
	_, err := q.db.Exec(ctx, markJobDone, arg.ID, arg.BatchID)
	return err
}

const markJobRetried = `-- name: MarkJobRetried :exec
UPDATE queue_job SET state = 'retried' WHERE id = $1
`

func (q *Queries) MarkJobRetried(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobRetried, id)
	return err
}

const tryFanOut = `-- name: TryFanOut :one
INSERT INTO dispatch (scan_id, scheduled_time, status)
VALUES ($1, $2, 'fanned-out')
ON CONFLICT ON CONSTRAINT dispatch_tick_key DO NOTHING
RETURNING id
`

type TryFanOutParams struct {
	ScanID        int64              `json:"scan_id"`
	ScheduledTime pgtype.Timestamptz `json:"scheduled_time"`
}

// Idempotent on (scan, scheduled_time): the first tick inserts a fanned-out
// Dispatch; an overlapping tick conflicts and returns no row, which the caller
// records as a skip rather than a second fan-out.
func (q *Queries) TryFanOut(ctx context.Context, arg TryFanOutParams) (int64, error) {
	row := q.db.QueryRow(ctx, tryFanOut, arg.ScanID, arg.ScheduledTime)
	var id int64
	err := row.Scan(&id)
	return id, err
}
