// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Role         string             `json:"role"`
	PasswordHash string             `json:"password_hash"`
	TotpSecret   pgtype.Text        `json:"totp_secret"`
	TotpEnabled  bool               `json:"totp_enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Batch struct {
	ID            int64              `json:"id"`
	ScanID        int64              `json:"scan_id"`
	DispatchID    pgtype.Int8        `json:"dispatch_id"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Kind          string             `json:"kind"`
	Outcome       string             `json:"outcome"`
	Offers        []byte             `json:"offers"`
	RecordedScope []byte             `json:"recorded_scope"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID            int64              `json:"id"`
	Url           string             `json:"url"`
	Secret        pgtype.Text        `json:"secret"`
	RouteDrift    bool               `json:"route_drift"`
	RouteCoverage bool               `json:"route_coverage"`
	RouteClock    bool               `json:"route_clock"`
	Enabled       bool               `json:"enabled"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Dispatch struct {
	ID            int64              `json:"id"`
	ScanID        int64              `json:"scan_id"`
	ScheduledTime pgtype.Timestamptz `json:"scheduled_time"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Exclusion struct {
	ID          int64              `json:"id"`
	Kind        string             `json:"kind"`
	Name        pgtype.Text        `json:"name"`
	AddressCidr *netip.Prefix      `json:"address_cidr"`
	CreatedBy   int64              `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Heartbeat struct {
	ID        int64              `json:"id"`
	CheckedAt pgtype.Timestamptz `json:"checked_at"`
}

type Observation struct {
	ID            int64              `json:"id"`
	BatchID       int64              `json:"batch_id"`
	Facet         string             `json:"facet"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Proposal struct {
	ID              int64              `json:"id"`
	LookupID        int64              `json:"lookup_id"`
	SourceSlug      string             `json:"source_slug"`
	RecordKind      string             `json:"record_kind"`
	AddressCidr     netip.Prefix       `json:"address_cidr"`
	OrgName         string             `json:"org_name"`
	Status          string             `json:"status"`
	ConfirmedSeedID pgtype.Int8        `json:"confirmed_seed_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProposerLookup struct {
	ID        int64              `json:"id"`
	Query     string             `json:"query"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QueueJob struct {
	ID             int64              `json:"id"`
	ScanID         int64              `json:"scan_id"`
	VantageID      pgtype.Int8        `json:"vantage_id"`
	DispatchID     pgtype.Int8        `json:"dispatch_id"`
	Kind           string             `json:"kind"`
	Spec           []byte             `json:"spec"`
	AttemptedScope []byte             `json:"attempted_scope"`
	Offers         []byte             `json:"offers"`
	State          string             `json:"state"`
	Attempt        int32              `json:"attempt"`
	MaxAttempts    int32              `json:"max_attempts"`
	BatchID        pgtype.Int8        `json:"batch_id"`
	RunAfter       pgtype.Timestamptz `json:"run_after"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RetentionSetting struct {
	ID                      bool               `json:"id"`
	ObservationCurrencyDays int64              `json:"observation_currency_days"`
	DispatchCadenceMultiple int64              `json:"dispatch_cadence_multiple"`
	UpdatedBy               pgtype.Int8        `json:"updated_by"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Scan struct {
	ID             int64              `json:"id"`
	Kind           string             `json:"kind"`
	Enabled        bool               `json:"enabled"`
	CadenceSeconds int64              `json:"cadence_seconds"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Seed struct {
	ID               int64              `json:"id"`
	Kind             string             `json:"kind"`
	NameDomain       pgtype.Text        `json:"name_domain"`
	AddressCidr      *netip.Prefix      `json:"address_cidr"`
	CreatedBy        int64              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CustodyExtension bool               `json:"custody_extension"`
}

type SourceState struct {
	Slug      string             `json:"slug"`
	Enabled   bool               `json:"enabled"`
	ToggledBy int64              `json:"toggled_by"`
	ToggledAt pgtype.Timestamptz `json:"toggled_at"`
}

type Span struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Vantage struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Class        string             `json:"class"`
	Resolver     string             `json:"resolver"`
	Host         pgtype.Text        `json:"host"`
	Port         pgtype.Int4        `json:"port"`
	Username     pgtype.Text        `json:"username"`
	Availability pgtype.Text        `json:"availability"`
	PublicKey    pgtype.Text        `json:"public_key"`
	HostKey      pgtype.Text        `json:"host_key"`
	CreatedBy    pgtype.Int8        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VergeCoreFrequencyEdit struct {
	ID        int64              `json:"id"`
	Port      int32              `json:"port"`
	Action    string             `json:"action"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ZoneFile struct {
	ID         int64              `json:"id"`
	SeedID     int64              `json:"seed_id"`
	SuppliedAt pgtype.Timestamptz `json:"supplied_at"`
	Content    string             `json:"content"`
	UploadedBy int64              `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
