// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :exec
UPDATE password_reset SET consumed_at = $2 WHERE id = $1
`

type ConsumePasswordResetParams struct {
	ID         int64              `json:"id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

// Spend a reset grant: stamp consumed_at with the instant the caller passes, which
// makes it single-use. A second present of the same token then reads a non-NULL
// consumed_at and is refused.
func (q *Queries) ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) error {
	_, err := q.db.Exec(ctx, consumePasswordReset, arg.ID, arg.ConsumedAt)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_reset (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, created_at, expires_at, consumed_at
`

type CreatePasswordResetParams struct {
	AccountID int64              `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Mint a single-use password-reset grant for one account. Only the token hash is
// stored; the plaintext rides one URL handed to the operator out of band. The
// caller sets expires_at from the server clock, so the window is bounded by the
// same injectable clock every other auth read uses.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getPasswordResetByHash = `-- name: GetPasswordResetByHash :one
SELECT id, account_id, token_hash, created_at, expires_at, consumed_at
FROM password_reset
WHERE token_hash = $1
`

// Resolve a presented reset token to its row by hash. Validity (unconsumed,
// unexpired) is checked in the handler against the server clock rather than SQL
// now(), so a fixed-clock test and production agree on the same boundary.
func (q *Queries) GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
