// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalToken = `-- name: CreatePersonalToken :one
INSERT INTO personal_token (account_id, name, prefix, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, name, prefix, token_hash, created_at, last_used_at
`

type CreatePersonalTokenParams struct {
	AccountID int64  `json:"account_id"`
	Name      string `json:"name"`
	Prefix    string `json:"prefix"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) CreatePersonalToken(ctx context.Context, arg CreatePersonalTokenParams) (PersonalToken, error) {
	row := q.db.QueryRow(ctx, createPersonalToken,
		arg.AccountID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
	)
	var i PersonalToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePersonalToken = `-- name: DeletePersonalToken :exec
DELETE FROM personal_token
WHERE id = $1 AND account_id = $2
`

type DeletePersonalTokenParams struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) DeletePersonalToken(ctx context.Context, arg DeletePersonalTokenParams) error {
	_, err := q.db.Exec(ctx, deletePersonalToken, arg.ID, arg.AccountID)
	return err
}

const getPersonalTokenByHash = `-- name: GetPersonalTokenByHash :one
SELECT id, account_id, name, prefix, token_hash, created_at, last_used_at
FROM personal_token
WHERE token_hash = $1
`

func (q *Queries) GetPersonalTokenByHash(ctx context.Context, tokenHash string) (PersonalToken, error) {
	row := q.db.QueryRow(ctx, getPersonalTokenByHash, tokenHash)
	var i PersonalToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT id, account_id, name, prefix, created_at, last_used_at
FROM personal_token
WHERE account_id = $1
ORDER BY created_at DESC, id DESC
`

type ListPersonalTokensRow struct {
	ID         int64              `json:"id"`
	AccountID  int64              `json:"account_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListPersonalTokens(ctx context.Context, accountID int64) ([]ListPersonalTokensRow, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalTokensRow{}
	for rows.Next() {
		var i ListPersonalTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonalTokenLastUsed = `-- name: UpdatePersonalTokenLastUsed :exec
UPDATE personal_token
SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 hour')
`

func (q *Queries) UpdatePersonalTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updatePersonalTokenLastUsed, id)
	return err
}
