// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalToken = `-- name: CreatePersonalToken :one
INSERT INTO personal_token (account_id, name, prefix, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, name, prefix, token_hash, created_at, last_used_at
`

type CreatePersonalTokenParams struct {
	AccountID int64  `json:"account_id"`
	Name      string `json:"name"`
	Prefix    string `json:"prefix"`
	TokenHash string `json:"token_hash"`
}

// Mint a personal API token for one account. Only the hash and the non-secret
// prefix are stored; the plaintext is shown once at the call site and never
// persisted. A duplicate (account_id, name) is a unique violation, surfaced to the
// operator as a name-already-taken message rather than a second silent row.
func (q *Queries) CreatePersonalToken(ctx context.Context, arg CreatePersonalTokenParams) (PersonalToken, error) {
	row := q.db.QueryRow(ctx, createPersonalToken,
		arg.AccountID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
	)
	var i PersonalToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePersonalToken = `-- name: DeletePersonalToken :exec
DELETE FROM personal_token
WHERE id = $1 AND account_id = $2
`

type DeletePersonalTokenParams struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
}

// Revoke a token, scoped to its owner: the account_id predicate means an operator
// can only revoke their own tokens, never another account's by guessing an id.
// Revocation is a hard delete — a revoked token holds no history worth reading.
func (q *Queries) DeletePersonalToken(ctx context.Context, arg DeletePersonalTokenParams) error {
	_, err := q.db.Exec(ctx, deletePersonalToken, arg.ID, arg.AccountID)
	return err
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT id, account_id, name, prefix, created_at, last_used_at
FROM personal_token
WHERE account_id = $1
ORDER BY created_at DESC, id DESC
`

type ListPersonalTokensRow struct {
	ID         int64              `json:"id"`
	AccountID  int64              `json:"account_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// One account's tokens, newest first. token_hash is omitted from the read: listing
// tokens never needs it, so the secret material stays out of the render path — only
// the label, the non-secret prefix, and the timestamps are surfaced.
func (q *Queries) ListPersonalTokens(ctx context.Context, accountID int64) ([]ListPersonalTokensRow, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalTokensRow{}
	for rows.Next() {
		var i ListPersonalTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
