// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposals.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmProposal = `-- name: ConfirmProposal :execrows
UPDATE proposal
SET status = 'confirmed', confirmed_seed_id = $2
WHERE id = $1 AND status = 'pending'
`

type ConfirmProposalParams struct {
	ID              int64       `json:"id"`
	ConfirmedSeedID pgtype.Int8 `json:"confirmed_seed_id"`
}

func (q *Queries) ConfirmProposal(ctx context.Context, arg ConfirmProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmProposal, arg.ID, arg.ConfirmedSeedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProposal = `-- name: CreateProposal :one
INSERT INTO proposal (lookup_id, source_slug, record_kind, address_cidr, org_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, lookup_id, source_slug, record_kind, address_cidr, org_name, status, confirmed_seed_id, created_at
`

type CreateProposalParams struct {
	LookupID    int64        `json:"lookup_id"`
	SourceSlug  string       `json:"source_slug"`
	RecordKind  string       `json:"record_kind"`
	AddressCidr netip.Prefix `json:"address_cidr"`
	OrgName     string       `json:"org_name"`
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.LookupID,
		arg.SourceSlug,
		arg.RecordKind,
		arg.AddressCidr,
		arg.OrgName,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.SourceSlug,
		&i.RecordKind,
		&i.AddressCidr,
		&i.OrgName,
		&i.Status,
		&i.ConfirmedSeedID,
		&i.CreatedAt,
	)
	return i, err
}

const createProposerLookup = `-- name: CreateProposerLookup :one
INSERT INTO proposer_lookup (query, created_by)
VALUES ($1, $2)
RETURNING id, query, created_by, created_at
`

type CreateProposerLookupParams struct {
	Query     string `json:"query"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateProposerLookup(ctx context.Context, arg CreateProposerLookupParams) (ProposerLookup, error) {
	row := q.db.QueryRow(ctx, createProposerLookup, arg.Query, arg.CreatedBy)
	var i ProposerLookup
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const declineLookup = `-- name: DeclineLookup :execrows
UPDATE proposal
SET status = 'declined'
WHERE lookup_id = $1 AND status = 'pending'
`

func (q *Queries) DeclineLookup(ctx context.Context, lookupID int64) (int64, error) {
	result, err := q.db.Exec(ctx, declineLookup, lookupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const declineProposal = `-- name: DeclineProposal :execrows
UPDATE proposal
SET status = 'declined'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeclineProposal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, declineProposal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingProposal = `-- name: GetPendingProposal :one
SELECT id, lookup_id, source_slug, record_kind, address_cidr, org_name, status, confirmed_seed_id, created_at
FROM proposal
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingProposal(ctx context.Context, id int64) (Proposal, error) {
	row := q.db.QueryRow(ctx, getPendingProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.SourceSlug,
		&i.RecordKind,
		&i.AddressCidr,
		&i.OrgName,
		&i.Status,
		&i.ConfirmedSeedID,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingProposals = `-- name: ListPendingProposals :many
SELECT p.id, p.lookup_id, p.source_slug, p.record_kind, p.address_cidr, p.org_name,
       l.query AS lookup_query, l.created_at AS lookup_at, a.username AS lookup_by
FROM proposal p
JOIN proposer_lookup l ON l.id = p.lookup_id
JOIN account a ON a.id = l.created_by
WHERE p.status = 'pending'
ORDER BY l.created_at DESC, l.id DESC, p.id ASC
`

type ListPendingProposalsRow struct {
	ID          int64              `json:"id"`
	LookupID    int64              `json:"lookup_id"`
	SourceSlug  string             `json:"source_slug"`
	RecordKind  string             `json:"record_kind"`
	AddressCidr netip.Prefix       `json:"address_cidr"`
	OrgName     string             `json:"org_name"`
	LookupQuery string             `json:"lookup_query"`
	LookupAt    pgtype.Timestamptz `json:"lookup_at"`
	LookupBy    string             `json:"lookup_by"`
}

func (q *Queries) ListPendingProposals(ctx context.Context) ([]ListPendingProposalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingProposalsRow{}
	for rows.Next() {
		var i ListPendingProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.LookupID,
			&i.SourceSlug,
			&i.RecordKind,
			&i.AddressCidr,
			&i.OrgName,
			&i.LookupQuery,
			&i.LookupAt,
			&i.LookupBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
