// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceCTLogCursor(ctx context.Context, arg AdvanceCTLogCursorParams) error
	CTLastBatchAdmitCount(ctx context.Context) (int64, error)
	CTReliabilityWindow(ctx context.Context, arg CTReliabilityWindowParams) (CTReliabilityWindowRow, error)
	CTTailLastBatch(ctx context.Context) (CTTailLastBatchRow, error)
	CancelActiveJobsForDispatch(ctx context.Context, dispatchID pgtype.Int8) (int64, error)
	CancelReadyJobsForDispatch(ctx context.Context, dispatchID pgtype.Int8) (int64, error)
	ClaimDelivery(ctx context.Context) (ClaimDeliveryRow, error)
	ClaimJob(ctx context.Context) (ClaimJobRow, error)
	ClaimReportNotification(ctx context.Context) (ClaimReportNotificationRow, error)
	CloseSpan(ctx context.Context, arg CloseSpanParams) error
	ConfirmProposal(ctx context.Context, arg ConfirmProposalParams) (int64, error)
	ConfirmTOTP(ctx context.Context, id int64) error
	ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) error
	ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) error
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) error
	CountAccounts(ctx context.Context) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountCertificateMaterial(ctx context.Context) (int64, error)
	CountObservationsForScan(ctx context.Context, scanID int64) (int64, error)
	CountUnreadMessages(ctx context.Context, accountID int64) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAddressExclusion(ctx context.Context, arg CreateAddressExclusionParams) (Exclusion, error)
	CreateAddressSeed(ctx context.Context, arg CreateAddressSeedParams) (Seed, error)
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) (Annotation, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (int64, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateNameExclusion(ctx context.Context, arg CreateNameExclusionParams) (Exclusion, error)
	CreateNameSeed(ctx context.Context, arg CreateNameSeedParams) (Seed, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreatePersonalToken(ctx context.Context, arg CreatePersonalTokenParams) (PersonalToken, error)
	CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error)
	CreateProposerLookup(ctx context.Context, arg CreateProposerLookupParams) (ProposerLookup, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateVantage(ctx context.Context, arg CreateVantageParams) (Vantage, error)
	CreateZoneFile(ctx context.Context, arg CreateZoneFileParams) (CreateZoneFileRow, error)
	DeclineLookup(ctx context.Context, lookupID int64) (int64, error)
	DeclineProposal(ctx context.Context, id int64) (int64, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteAnnotation(ctx context.Context, id int64) error
	DeleteChannel(ctx context.Context, id int64) error
	DeleteExclusion(ctx context.Context, id int64) error
	DeleteExpiredDispatches(ctx context.Context, scheduledTime pgtype.Timestamptz) (int64, error)
	DeleteExpiredObservations(ctx context.Context, arg DeleteExpiredObservationsParams) (int64, error)
	DeleteExpiredTranscripts(ctx context.Context, capturedAt pgtype.Timestamptz) (int64, error)
	DeleteIntegrationState(ctx context.Context, slug string) error
	DeletePersonalToken(ctx context.Context, arg DeletePersonalTokenParams) error
	DeleteRecoveryCodesForAccount(ctx context.Context, accountID int64) error
	DeleteReportSchedule(ctx context.Context, id int64) error
	DeleteSSOIdentity(ctx context.Context, id int64) error
	DeleteSSOIdentityForAccount(ctx context.Context, arg DeleteSSOIdentityForAccountParams) (int64, error)
	DeleteSSOProvider(ctx context.Context, id int64) error
	DeleteVergeCoreFrequencyEdit(ctx context.Context, port int32) error
	EarliestBatchTime(ctx context.Context) (pgtype.Timestamptz, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error)
	FindCoveringAddressSeed(ctx context.Context, address netip.Addr) (FindCoveringAddressSeedRow, error)
	FindCoveringNameSeed(ctx context.Context, name string) (FindCoveringNameSeedRow, error)
	FindNameCitingAddress(ctx context.Context, arg FindNameCitingAddressParams) (FindNameCitingAddressRow, error)
	FindNameSeedByID(ctx context.Context, seedID int64) (FindNameSeedByIDRow, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAccountBySSOIdentity(ctx context.Context, arg GetAccountBySSOIdentityParams) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetCTLogCursor(ctx context.Context, logID string) (GetCTLogCursorRow, error)
	GetCertificateMaterial(ctx context.Context, fingerprint string) (CertificateMaterial, error)
	GetChannel(ctx context.Context, id int64) (GetChannelRow, error)
	GetChannelForDelivery(ctx context.Context, id int64) (GetChannelForDeliveryRow, error)
	GetEndpointSubject(ctx context.Context, arg GetEndpointSubjectParams) (GetEndpointSubjectRow, error)
	// The migration seeds this row, so no-rows is not a reachable state.
	GetInstanceConfig(ctx context.Context) (GetInstanceConfigRow, error)
	GetInstanceHealth(ctx context.Context) (GetInstanceHealthRow, error)
	GetIntegrationChannel(ctx context.Context, slug string) (pgtype.Int8, error)
	GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error)
	GetLatestReportDelivery(ctx context.Context, scheduleID int64) (ReportDelivery, error)
	GetMessageForDelivery(ctx context.Context, id int64) (GetMessageForDeliveryRow, error)
	// A Citation never ages, so the admission hop reads under no live-tier clock (ADR-0096).
	GetNameCitation(ctx context.Context, arg GetNameCitationParams) (GetNameCitationRow, error)
	GetNameSubject(ctx context.Context, arg GetNameSubjectParams) (GetNameSubjectRow, error)
	// An as-of bound here would hide settled history rather than protect a derivation (ADR-0105).
	GetOpenSpan(ctx context.Context, arg GetOpenSpanParams) (GetOpenSpanRow, error)
	GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetPendingProposal(ctx context.Context, id int64) (Proposal, error)
	GetPersonalTokenByHash(ctx context.Context, tokenHash string) (PersonalToken, error)
	GetReportSchedule(ctx context.Context, id int64) (ReportSchedule, error)
	// The migration seeds the one global row, so a missing row is a fault and not an empty state.
	GetRetentionSettings(ctx context.Context) (GetRetentionSettingsRow, error)
	GetSSOIdentityBySub(ctx context.Context, arg GetSSOIdentityBySubParams) (GetSSOIdentityBySubRow, error)
	GetSSOProvider(ctx context.Context, id int64) (GetSSOProviderRow, error)
	GetSSOProviderForAuth(ctx context.Context, slug string) (GetSSOProviderForAuthRow, error)
	GetScanByKind(ctx context.Context, kind string) (Scan, error)
	GetServiceSubject(ctx context.Context, arg GetServiceSubjectParams) (GetServiceSubjectRow, error)
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	GetTranscriptByJob(ctx context.Context, queueJobID int64) (Transcript, error)
	GetVantage(ctx context.Context, id int64) (Vantage, error)
	GetZoneCadenceSeconds(ctx context.Context) (int64, error)
	InsertAdmittedName(ctx context.Context, arg InsertAdmittedNameParams) error
	InsertBatch(ctx context.Context, arg InsertBatchParams) (int64, error)
	InsertCTReliabilitySample(ctx context.Context, arg InsertCTReliabilitySampleParams) error
	InsertCertificateMaterial(ctx context.Context, arg InsertCertificateMaterialParams) error
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error
	InsertEdgeFanoutObservation(ctx context.Context, arg InsertEdgeFanoutObservationParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	InsertObservation(ctx context.Context, arg InsertObservationParams) error
	InsertReportDelivery(ctx context.Context, arg InsertReportDeliveryParams) (ReportDelivery, error)
	InsertReportNotification(ctx context.Context, arg InsertReportNotificationParams) error
	InsertReportSchedule(ctx context.Context, arg InsertReportScheduleParams) (ReportSchedule, error)
	InsertSSOIdentity(ctx context.Context, arg InsertSSOIdentityParams) error
	// A render read takes presence, never the value; the token exchange is the exception (ADR-0112).
	InsertSSOProvider(ctx context.Context, arg InsertSSOProviderParams) (int64, error)
	InsertTranscript(ctx context.Context, arg InsertTranscriptParams) error
	LatestZoneFilesForDispatch(ctx context.Context) ([]LatestZoneFilesForDispatchRow, error)
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	ListActiveDispatchProgress(ctx context.Context) ([]ListActiveDispatchProgressRow, error)
	ListAddressExclusionCidrs(ctx context.Context) ([]*netip.Prefix, error)
	ListAddressExclusionWithdrawals(ctx context.Context) ([]ListAddressExclusionWithdrawalsRow, error)
	ListAddressScopeCidrs(ctx context.Context) ([]*netip.Prefix, error)
	// An append-only source re-admits the same names on every poll.
	ListAdmittedNames(ctx context.Context) ([]string, error)
	ListAdmittedNamesOutsideSeed(ctx context.Context, seedID int64) ([]string, error)
	ListAllActiveSessions(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListAllActiveSessionsRow, error)
	ListAllOpenSpans(ctx context.Context) ([]ListAllOpenSpansRow, error)
	// A dial is not ranked: no staleness sort and no per-rule count (ADR-0073 §3, §4).
	ListAnnotations(ctx context.Context) ([]Annotation, error)
	ListBlanketedReachServices(ctx context.Context) ([]string, error)
	ListCertificateMaterialDER(ctx context.Context, fingerprints []string) ([]ListCertificateMaterialDERRow, error)
	ListChannels(ctx context.Context) ([]ListChannelsRow, error)
	ListColdScopeSeedIds(ctx context.Context) ([]int64, error)
	ListColdScopeSeeds(ctx context.Context) ([]ListColdScopeSeedsRow, error)
	ListConcludedDispatchProgress(ctx context.Context, limit int32) ([]ListConcludedDispatchProgressRow, error)
	ListCurrentEndpointSubjects(ctx context.Context, arg ListCurrentEndpointSubjectsParams) ([]ListCurrentEndpointSubjectsRow, error)
	// The gate carries the read instant, so no parameterless VIEW holds it and it inlines per read.
	ListCurrentNameSubjects(ctx context.Context, arg ListCurrentNameSubjectsParams) ([]ListCurrentNameSubjectsRow, error)
	ListCurrentServiceSubjects(ctx context.Context, arg ListCurrentServiceSubjectsParams) ([]ListCurrentServiceSubjectsRow, error)
	ListDeliveriesForMessage(ctx context.Context, messageID int64) ([]ListDeliveriesForMessageRow, error)
	ListDeliveryOutcomes(ctx context.Context) ([]ListDeliveryOutcomesRow, error)
	ListDispatchProgress(ctx context.Context, limit int32) ([]ListDispatchProgressRow, error)
	ListEdgeFanoutMeasurements(ctx context.Context) ([]ListEdgeFanoutMeasurementsRow, error)
	ListEdgeFanoutMeasurementsOver(ctx context.Context, addresses []string) ([]ListEdgeFanoutMeasurementsOverRow, error)
	ListEnabledSSOProviders(ctx context.Context) ([]ListEnabledSSOProvidersRow, error)
	ListEnabledScans(ctx context.Context) ([]Scan, error)
	ListEndpointCertificates(ctx context.Context, arg ListEndpointCertificatesParams) ([]ListEndpointCertificatesRow, error)
	ListExclusions(ctx context.Context) ([]ListExclusionsRow, error)
	ListExtendedZoneDomains(ctx context.Context) ([]pgtype.Text, error)
	ListIntegrationStates(ctx context.Context) ([]IntegrationState, error)
	ListJobsForDispatch(ctx context.Context, dispatchID pgtype.Int8) ([]ListJobsForDispatchRow, error)
	// Every derivation read of observation inlines this gate, never the raw table (#237, ADR-0041).
	ListLiveObservationsForDerivation(ctx context.Context, arg ListLiveObservationsForDerivationParams) ([]ListLiveObservationsForDerivationRow, error)
	ListMessages(ctx context.Context) ([]Message, error)
	ListNameDNSRecords(ctx context.Context, arg ListNameDNSRecordsParams) ([]ListNameDNSRecordsRow, error)
	ListNameResolutionsByClass(ctx context.Context, arg ListNameResolutionsByClassParams) ([]ListNameResolutionsByClassRow, error)
	ListNameSeedDomains(ctx context.Context) ([]pgtype.Text, error)
	ListNameSeedWithdrawalCandidates(ctx context.Context, domains []string) ([]ListNameSeedWithdrawalCandidatesRow, error)
	ListNameSeeds(ctx context.Context) ([]ListNameSeedsRow, error)
	ListOpenSpansForSubject(ctx context.Context, arg ListOpenSpansForSubjectParams) ([]ListOpenSpansForSubjectRow, error)
	ListPendingNameSeedWithdrawals(ctx context.Context) ([]ListPendingNameSeedWithdrawalsRow, error)
	ListPendingProposals(ctx context.Context) ([]ListPendingProposalsRow, error)
	ListPendingSeedWithdrawals(ctx context.Context) ([]ListPendingSeedWithdrawalsRow, error)
	ListPersonalTokens(ctx context.Context, accountID int64) ([]ListPersonalTokensRow, error)
	ListReachedServices(ctx context.Context) ([]ListReachedServicesRow, error)
	ListReadMessageIDs(ctx context.Context, accountID int64) ([]int64, error)
	ListRecentDriftEvents(ctx context.Context, arg ListRecentDriftEventsParams) ([]ListRecentDriftEventsRow, error)
	ListRecentObservations(ctx context.Context, limit int32) ([]ListRecentObservationsRow, error)
	ListReportDeliveries(ctx context.Context, scheduleID int64) ([]ReportDelivery, error)
	ListReportSchedules(ctx context.Context) ([]ReportSchedule, error)
	ListSSOBindings(ctx context.Context) ([]ListSSOBindingsRow, error)
	ListSSOIdentitiesForAccount(ctx context.Context, accountID int64) ([]ListSSOIdentitiesForAccountRow, error)
	ListSSOProviders(ctx context.Context) ([]ListSSOProvidersRow, error)
	ListScans(ctx context.Context) ([]Scan, error)
	ListSeedWithdrawalCandidates(ctx context.Context, cidrs []string) ([]ListSeedWithdrawalCandidatesRow, error)
	ListSeeds(ctx context.Context) ([]ListSeedsRow, error)
	// The span corpus is already derived, so an as_of bound would hide settled state (ADR-0105).
	ListServiceReachabilitySpansByClass(ctx context.Context) ([]ListServiceReachabilitySpansByClassRow, error)
	ListServiceReachabilitySpansByClassAt(ctx context.Context, at pgtype.Timestamptz) ([]ListServiceReachabilitySpansByClassAtRow, error)
	ListServiceTLSAcceptance(ctx context.Context, arg ListServiceTLSAcceptanceParams) ([]ListServiceTLSAcceptanceRow, error)
	ListSessionsForAccount(ctx context.Context, arg ListSessionsForAccountParams) ([]ListSessionsForAccountRow, error)
	ListSignalInstances(ctx context.Context) ([]SignalInstance, error)
	ListSourceStates(ctx context.Context) ([]SourceState, error)
	ListSpansForSubject(ctx context.Context, arg ListSpansForSubjectParams) ([]ListSpansForSubjectRow, error)
	ListSpansOpenSince(ctx context.Context, since pgtype.Timestamptz) ([]ListSpansOpenSinceRow, error)
	ListSubjectFirstAppearances(ctx context.Context, since pgtype.Timestamptz) ([]ListSubjectFirstAppearancesRow, error)
	ListUnavailableVantages(ctx context.Context) ([]ListUnavailableVantagesRow, error)
	ListUnusedRecoveryCodeHashes(ctx context.Context, accountID int64) ([]ListUnusedRecoveryCodeHashesRow, error)
	ListVantages(ctx context.Context) ([]ListVantagesRow, error)
	ListVantagesForDispatch(ctx context.Context) ([]ListVantagesForDispatchRow, error)
	ListVantagesNeedingKey(ctx context.Context) ([]Vantage, error)
	ListVantagesNeedingLatency(ctx context.Context) ([]Vantage, error)
	ListVergeCoreFrequencyEdits(ctx context.Context) ([]ListVergeCoreFrequencyEditsRow, error)
	ListVergeCoreFrequencyEditsWithAuthor(ctx context.Context) ([]ListVergeCoreFrequencyEditsWithAuthorRow, error)
	ListWithdrawalLifespans(ctx context.Context, since pgtype.Timestamptz) ([]ListWithdrawalLifespansRow, error)
	ListZoneDeclarations(ctx context.Context) ([]ListZoneDeclarationsRow, error)
	ListZoneFileStatus(ctx context.Context) ([]ListZoneFileStatusRow, error)
	MarkAllMessagesRead(ctx context.Context, arg MarkAllMessagesReadParams) error
	MarkDeliveryDelivered(ctx context.Context, arg MarkDeliveryDeliveredParams) error
	MarkDeliveryUndelivered(ctx context.Context, arg MarkDeliveryUndeliveredParams) error
	MarkJobDead(ctx context.Context, arg MarkJobDeadParams) (int64, error)
	MarkJobDone(ctx context.Context, arg MarkJobDoneParams) (int64, error)
	MarkJobRetried(ctx context.Context, id int64) (int64, error)
	// A re-read is not a new fact, so the first read instant stands.
	MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error
	MarkMessageUnread(ctx context.Context, arg MarkMessageUnreadParams) error
	MarkReportDeliveryDelivered(ctx context.Context, arg MarkReportDeliveryDeliveredParams) error
	MarkReportNotificationDelivered(ctx context.Context, id int64) error
	MarkReportNotificationUndelivered(ctx context.Context, arg MarkReportNotificationUndeliveredParams) error
	MarkVantageAvailable(ctx context.Context, id int64) error
	MarkVantageUnavailable(ctx context.Context, id int64) error
	MintSignalInstances(ctx context.Context, arg MintSignalInstancesParams) error
	NameCitedAddresses(ctx context.Context, arg NameCitedAddressesParams) ([]NameCitedAddressesRow, error)
	NextReportDeliveryNo(ctx context.Context, scheduleID int64) (int32, error)
	NotifyJobProgress(ctx context.Context, payload string) error
	OpenSpan(ctx context.Context, arg OpenSpanParams) (int64, error)
	OptInColdScope(ctx context.Context, arg OptInColdScopeParams) error
	OptOutColdScope(ctx context.Context, seedID int64) error
	PinVantageHostKey(ctx context.Context, arg PinVantageHostKeyParams) error
	// IPv4 subject keys only, so an IPv6 exclusion previews and withdraws nothing.
	// A substring resolution test, so a resolution citing 10.0.0.10 also holds 10.0.0.1.
	// Both bound this smaller than the model asks, never larger; widening either moves every copy.
	PreviewExclusionWithdrawal(ctx context.Context, arg PreviewExclusionWithdrawalParams) (PreviewExclusionWithdrawalRow, error)
	PreviousBatchTime(ctx context.Context) (pgtype.Timestamptz, error)
	// A dead worker is failure, not evidence, so a reap writes no Batch and moves no Availability.
	ReapStaleRunningJobs(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	RecordHeartbeat(ctx context.Context) (Heartbeat, error)
	ReserveCTSlot(ctx context.Context, arg ReserveCTSlotParams) (pgtype.Timestamptz, error)
	ResetAccountTOTP(ctx context.Context, id int64) error
	RetryDelivery(ctx context.Context, arg RetryDeliveryParams) error
	RetryReportNotification(ctx context.Context, arg RetryReportNotificationParams) error
	RevokeAllSessionsForAccount(ctx context.Context, arg RevokeAllSessionsForAccountParams) error
	RevokeOtherSessionsForAccount(ctx context.Context, arg RevokeOtherSessionsForAccountParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeSessionByIDForAdmin(ctx context.Context, arg RevokeSessionByIDForAdminParams) error
	ScanHasCompletedBatch(ctx context.Context, kind string) (bool, error)
	ScanHasNonTerminalJobs(ctx context.Context, arg ScanHasNonTerminalJobsParams) (bool, error)
	SetAPIEnabled(ctx context.Context, arg SetAPIEnabledParams) error
	SetChannelSecret(ctx context.Context, arg SetChannelSecretParams) error
	// The seed CHECK rejects a true extension on an address scope, so an unguarded declare errors.
	SetCustodyExtension(ctx context.Context, arg SetCustodyExtensionParams) error
	SetDispatchStatus(ctx context.Context, arg SetDispatchStatusParams) error
	SetIntegrationChannel(ctx context.Context, arg SetIntegrationChannelParams) error
	SetLastBackup(ctx context.Context, lastBackupSize pgtype.Int8) error
	SetReleaseCache(ctx context.Context, arg SetReleaseCacheParams) error
	SetSSOProviderSecret(ctx context.Context, arg SetSSOProviderSecretParams) error
	// The operator cap has no upper bound; a large scope is priced at policy time (ADR-0127).
	SetSeedAddressCap(ctx context.Context, arg SetSeedAddressCapParams) error
	SetTOTPLastStep(ctx context.Context, arg SetTOTPLastStepParams) (int64, error)
	SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error
	SetUpdateCheckEnabled(ctx context.Context, arg SetUpdateCheckEnabledParams) error
	SetVantageLatency(ctx context.Context, arg SetVantageLatencyParams) error
	SetVantageProbeFacts(ctx context.Context, arg SetVantageProbeFactsParams) error
	SetVantagePublicKey(ctx context.Context, arg SetVantagePublicKeyParams) error
	// A non-positive interval is refused by the table's CHECK, not by this statement.
	SetZoneCadenceSeconds(ctx context.Context, cadenceSeconds int64) error
	SlowestEnabledScanCadenceSeconds(ctx context.Context) (int64, error)
	// Every dns job waits, not only older ones: a retry re-enqueues the frozen spec (ADR-0135 §5).
	SpendNameSeedWithdrawals(ctx context.Context, arg SpendNameSeedWithdrawalsParams) error
	SpendSeedWithdrawals(ctx context.Context, arg SpendSeedWithdrawalsParams) error
	SyncColdScanEnabled(ctx context.Context) error
	TightestEnabledScanCadenceSeconds(ctx context.Context) (int64, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TrimCTReliabilitySamples(ctx context.Context, arg TrimCTReliabilitySamplesParams) error
	TryFanOut(ctx context.Context, arg TryFanOutParams) (int64, error)
	TryInsertScheduledDelivery(ctx context.Context, arg TryInsertScheduledDeliveryParams) (TryInsertScheduledDeliveryRow, error)
	UpdateAccountRole(ctx context.Context, arg UpdateAccountRoleParams) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePersonalTokenLastUsed(ctx context.Context, id int64) error
	UpdateReportSchedule(ctx context.Context, arg UpdateReportScheduleParams) (ReportSchedule, error)
	UpdateRetentionSettings(ctx context.Context, arg UpdateRetentionSettingsParams) error
	UpdateSSOProvider(ctx context.Context, arg UpdateSSOProviderParams) (int64, error)
	UpsertIntegrationState(ctx context.Context, arg UpsertIntegrationStateParams) (IntegrationState, error)
	UpsertSourceState(ctx context.Context, arg UpsertSourceStateParams) (SourceState, error)
	UpsertVergeCoreFrequencyEdit(ctx context.Context, arg UpsertVergeCoreFrequencyEditParams) error
	// A data-modifying CTE fires on its own, so dropping its count from the SELECT keeps the write.
	WithdrawSeed(ctx context.Context, arg WithdrawSeedParams) (WithdrawSeedRow, error)
}

var _ Querier = (*Queries)(nil)
