// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_code.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :exec
UPDATE recovery_code SET used_at = $2 WHERE id = $1
`

type ConsumeRecoveryCodeParams struct {
	ID     int64              `json:"id"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

// Spend one recovery code: stamp used_at with the instant the caller passes. A
// second present of the same code then reads a non-NULL used_at and is no longer
// listed as redeemable.
func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, consumeRecoveryCode, arg.ID, arg.UsedAt)
	return err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_code (account_id, code_hash) VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	AccountID int64  `json:"account_id"`
	CodeHash  string `json:"code_hash"`
}

// Store one recovery code's hash for an account. The plaintext is shown once at the
// call site and never persisted; only the hash is kept, so it cannot be shown again.
func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.AccountID, arg.CodeHash)
	return err
}

const deleteRecoveryCodesForAccount = `-- name: DeleteRecoveryCodesForAccount :exec
DELETE FROM recovery_code WHERE account_id = $1
`

// Clear an account's recovery codes before re-issuing a set, so enrolling (or
// re-enrolling) two-factor replaces the old codes wholesale rather than
// accumulating stale sets that would each still redeem.
func (q *Queries) DeleteRecoveryCodesForAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesForAccount, accountID)
	return err
}

const listUnusedRecoveryCodeHashes = `-- name: ListUnusedRecoveryCodeHashes :many
SELECT id, code_hash FROM recovery_code
WHERE account_id = $1 AND used_at IS NULL
ORDER BY id ASC
`

type ListUnusedRecoveryCodeHashesRow struct {
	ID       int64  `json:"id"`
	CodeHash string `json:"code_hash"`
}

// The account's still-redeemable codes, by id and hash, for the login fallback: the
// handler hashes the presented code and matches it here. Used codes are excluded so
// each redeems exactly once.
func (q *Queries) ListUnusedRecoveryCodeHashes(ctx context.Context, accountID int64) ([]ListUnusedRecoveryCodeHashesRow, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodeHashes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedRecoveryCodeHashesRow{}
	for rows.Next() {
		var i ListUnusedRecoveryCodeHashesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
