// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_delivery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReportDelivery = `-- name: GetLatestReportDelivery :one
SELECT id, schedule_id, period_start, period_end, delivery_no, generated_at, delivered_at, state, scheduled_tick
FROM report_delivery
WHERE schedule_id = $1 AND state <> 'failed'
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestReportDelivery(ctx context.Context, scheduleID int64) (ReportDelivery, error) {
	row := q.db.QueryRow(ctx, getLatestReportDelivery, scheduleID)
	var i ReportDelivery
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DeliveryNo,
		&i.GeneratedAt,
		&i.DeliveredAt,
		&i.State,
		&i.ScheduledTick,
	)
	return i, err
}

const insertReportDelivery = `-- name: InsertReportDelivery :one
INSERT INTO report_delivery (schedule_id, period_start, period_end, delivery_no, state, delivered_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, schedule_id, period_start, period_end, delivery_no, generated_at, delivered_at, state, scheduled_tick
`

type InsertReportDeliveryParams struct {
	ScheduleID  int64              `json:"schedule_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	DeliveryNo  int32              `json:"delivery_no"`
	State       string             `json:"state"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) InsertReportDelivery(ctx context.Context, arg InsertReportDeliveryParams) (ReportDelivery, error) {
	row := q.db.QueryRow(ctx, insertReportDelivery,
		arg.ScheduleID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DeliveryNo,
		arg.State,
		arg.DeliveredAt,
	)
	var i ReportDelivery
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DeliveryNo,
		&i.GeneratedAt,
		&i.DeliveredAt,
		&i.State,
		&i.ScheduledTick,
	)
	return i, err
}

const listReportDeliveries = `-- name: ListReportDeliveries :many
SELECT id, schedule_id, period_start, period_end, delivery_no, generated_at, delivered_at, state, scheduled_tick
FROM report_delivery
WHERE schedule_id = $1
ORDER BY id DESC
`

func (q *Queries) ListReportDeliveries(ctx context.Context, scheduleID int64) ([]ReportDelivery, error) {
	rows, err := q.db.Query(ctx, listReportDeliveries, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDelivery{}
	for rows.Next() {
		var i ReportDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DeliveryNo,
			&i.GeneratedAt,
			&i.DeliveredAt,
			&i.State,
			&i.ScheduledTick,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportDeliveryDelivered = `-- name: MarkReportDeliveryDelivered :exec
UPDATE report_delivery
SET state = 'delivered', delivered_at = $2
WHERE id = $1
`

type MarkReportDeliveryDeliveredParams struct {
	ID          int64              `json:"id"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) MarkReportDeliveryDelivered(ctx context.Context, arg MarkReportDeliveryDeliveredParams) error {
	_, err := q.db.Exec(ctx, markReportDeliveryDelivered, arg.ID, arg.DeliveredAt)
	return err
}

const nextReportDeliveryNo = `-- name: NextReportDeliveryNo :one
SELECT COALESCE(MAX(delivery_no), 0) + 1 AS next_no
FROM report_delivery
WHERE schedule_id = $1
`

func (q *Queries) NextReportDeliveryNo(ctx context.Context, scheduleID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextReportDeliveryNo, scheduleID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const tryInsertScheduledDelivery = `-- name: TryInsertScheduledDelivery :one
INSERT INTO report_delivery (schedule_id, period_start, period_end, delivery_no, state, delivered_at, scheduled_tick)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (schedule_id, scheduled_tick) WHERE scheduled_tick IS NOT NULL DO NOTHING
RETURNING id, schedule_id, period_start, period_end, delivery_no, generated_at, delivered_at, state
`

type TryInsertScheduledDeliveryParams struct {
	ScheduleID    int64              `json:"schedule_id"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
	DeliveryNo    int32              `json:"delivery_no"`
	State         string             `json:"state"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	ScheduledTick pgtype.Timestamptz `json:"scheduled_tick"`
}

type TryInsertScheduledDeliveryRow struct {
	ID          int64              `json:"id"`
	ScheduleID  int64              `json:"schedule_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	DeliveryNo  int32              `json:"delivery_no"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	State       string             `json:"state"`
}

func (q *Queries) TryInsertScheduledDelivery(ctx context.Context, arg TryInsertScheduledDeliveryParams) (TryInsertScheduledDeliveryRow, error) {
	row := q.db.QueryRow(ctx, tryInsertScheduledDelivery,
		arg.ScheduleID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DeliveryNo,
		arg.State,
		arg.DeliveredAt,
		arg.ScheduledTick,
	)
	var i TryInsertScheduledDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DeliveryNo,
		&i.GeneratedAt,
		&i.DeliveredAt,
		&i.State,
	)
	return i, err
}
