// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReportSchedule = `-- name: DeleteReportSchedule :exec
DELETE FROM report_schedule WHERE id = $1
`

func (q *Queries) DeleteReportSchedule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReportSchedule, id)
	return err
}

const getReportSchedule = `-- name: GetReportSchedule :one
SELECT id, name, sections, cadence, format, delivery_target, created_by, created_at, channel_id
FROM report_schedule
WHERE id = $1
`

func (q *Queries) GetReportSchedule(ctx context.Context, id int64) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, getReportSchedule, id)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sections,
		&i.Cadence,
		&i.Format,
		&i.DeliveryTarget,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ChannelID,
	)
	return i, err
}

const insertReportSchedule = `-- name: InsertReportSchedule :one
INSERT INTO report_schedule (name, sections, cadence, format, delivery_target, channel_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, sections, cadence, format, delivery_target, created_by, created_at, channel_id
`

type InsertReportScheduleParams struct {
	Name           string      `json:"name"`
	Sections       []byte      `json:"sections"`
	Cadence        string      `json:"cadence"`
	Format         string      `json:"format"`
	DeliveryTarget string      `json:"delivery_target"`
	ChannelID      pgtype.Int8 `json:"channel_id"`
	CreatedBy      int64       `json:"created_by"`
}

func (q *Queries) InsertReportSchedule(ctx context.Context, arg InsertReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, insertReportSchedule,
		arg.Name,
		arg.Sections,
		arg.Cadence,
		arg.Format,
		arg.DeliveryTarget,
		arg.ChannelID,
		arg.CreatedBy,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sections,
		&i.Cadence,
		&i.Format,
		&i.DeliveryTarget,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ChannelID,
	)
	return i, err
}

const listReportSchedules = `-- name: ListReportSchedules :many
SELECT id, name, sections, cadence, format, delivery_target, created_by, created_at, channel_id
FROM report_schedule
ORDER BY id DESC
`

func (q *Queries) ListReportSchedules(ctx context.Context) ([]ReportSchedule, error) {
	rows, err := q.db.Query(ctx, listReportSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSchedule{}
	for rows.Next() {
		var i ReportSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sections,
			&i.Cadence,
			&i.Format,
			&i.DeliveryTarget,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportSchedule = `-- name: UpdateReportSchedule :one
UPDATE report_schedule
SET name = $2, sections = $3, cadence = $4, format = $5, delivery_target = $6, channel_id = $7
WHERE id = $1
RETURNING id, name, sections, cadence, format, delivery_target, created_by, created_at, channel_id
`

type UpdateReportScheduleParams struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Sections       []byte      `json:"sections"`
	Cadence        string      `json:"cadence"`
	Format         string      `json:"format"`
	DeliveryTarget string      `json:"delivery_target"`
	ChannelID      pgtype.Int8 `json:"channel_id"`
}

func (q *Queries) UpdateReportSchedule(ctx context.Context, arg UpdateReportScheduleParams) (ReportSchedule, error) {
	row := q.db.QueryRow(ctx, updateReportSchedule,
		arg.ID,
		arg.Name,
		arg.Sections,
		arg.Cadence,
		arg.Format,
		arg.DeliveryTarget,
		arg.ChannelID,
	)
	var i ReportSchedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sections,
		&i.Cadence,
		&i.Format,
		&i.DeliveryTarget,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ChannelID,
	)
	return i, err
}
