// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredDispatches = `-- name: DeleteExpiredDispatches :execrows
DELETE FROM dispatch
WHERE scheduled_time < $1
`

// The one and only path that deletes Dispatch rows (v1 spec §4.6, ADR-0041). It
// touches the dispatch table and nothing else: no Observation, Span, Batch or
// queue_job row is read or written here, so retiring Dispatch can move no value
// on any timeline. The FK change in migration 20900 lets the delete null the
// operational back-references rather than cascade into measured data.
func (q *Queries) DeleteExpiredDispatches(ctx context.Context, scheduledTime pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDispatches, scheduledTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredObservations = `-- name: DeleteExpiredObservations :execrows
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
),
withdrawn AS (
    -- A withdrawn subject's timelines are all closed: it has spans and no open one.
    SELECT subject_key
    FROM span
    GROUP BY subject_key
    HAVING bool_and(closed_at IS NOT NULL)
)
DELETE FROM observation obs
WHERE obs.id IN (
    SELECT o.id
    FROM observation o
    LEFT JOIN cover c
        ON  c.subject_key   = o.subject_key
        AND c.facet         = o.facet
        AND c.discriminator = o.discriminator
        AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
        AND c.source        = o.source
    LEFT JOIN withdrawn w ON w.subject_key = o.subject_key
    WHERE $1::bigint > 0
      AND EXTRACT(EPOCH FROM ($2::timestamptz - o.observed_at)) > $1::bigint
      AND (
            -- Withdrawn: no floor, the dial alone governs (the guard above is the
            -- whole test).
            w.subject_key IS NOT NULL
            -- Defined bound, not withdrawn: also past its own live bound. A row
            -- inside k cadences of its covering Scan is live and never reached here.
         OR (c.tightest_cadence IS NOT NULL
             AND EXTRACT(EPOCH FROM ($2::timestamptz - o.observed_at))
                 > $3::bigint * c.tightest_cadence)
            -- c.tightest_cadence IS NULL and not withdrawn => undefined bound =>
            -- never retired (neither branch fires).
          )
)
`

type DeleteExpiredObservationsParams struct {
	DialSeconds   int64              `json:"dial_seconds"`
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

// Retire the evidential observations the operator's dial no longer keeps (v1 spec
// §4.6, ADR-0041, ADR-0094). This is the ONLY path that deletes Observation rows,
// and it deletes Observation rows and NOTHING else: batch, scan and span are read
// to resolve each row's own bound and its subject's membership, never written — so
// a Batch travels with any observation it produced (it is not retired per row) and
// a Span is never compacted.
//
// The query evaluates EACH ROW'S OWN bound, never a collapsed one: `cover` groups
// observations by their full timeline key (subject, facet, discriminator, vantage,
// source) and takes the tightest ENABLED covering Scan's cadence, so a zone-sourced
// row ages on the zone cadence and a resolver-sourced row on the resolver's. A row
// survives while its age is inside EITHER k cadences of that bound OR the dial,
// whichever is longer — the control collapses to one number, the query never does.
// Two populations fall opposite ways: a timeline no enabled Scan covers has an
// undefined bound and is NEVER retired (the `cover` LEFT JOIN misses, so the guard
// excludes it); a withdrawn subject (every span closed) carries NO floor, so the
// dial alone governs it.
//
// @dial_seconds is the operator's observation dial in seconds (0 == unbounded, the
// v1 default — the caller does not run the sweep then); @floor_cadences is k; @as_of
// is the sweep instant, injected so a sweep is reproducible.
func (q *Queries) DeleteExpiredObservations(ctx context.Context, arg DeleteExpiredObservationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredObservations, arg.DialSeconds, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredTranscripts = `-- name: DeleteExpiredTranscripts :execrows
DELETE FROM transcript
WHERE captured_at < $1
`

// The one and only path that deletes Transcript rows (raw-job-output spec §4,
// ADR-0126 amending ADR-0041). It touches the transcript table and nothing else:
// no derivation reads a Transcript (the §1 fence), so a wall clock retiring it by
// captured_at moves no value on any timeline — the same legality the Dispatch
// sweep rests on. The caller passes the floored cutoff (now minus the
// transcript_currency_days window); this deletes every captured row older than it.
func (q *Queries) DeleteExpiredTranscripts(ctx context.Context, capturedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTranscripts, capturedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRetentionSettings = `-- name: GetRetentionSettings :one
SELECT observation_currency_days, dispatch_cadence_multiple,
       transcript_currency_days, updated_by, updated_at
FROM retention_settings
WHERE id = true
`

type GetRetentionSettingsRow struct {
	ObservationCurrencyDays int64              `json:"observation_currency_days"`
	DispatchCadenceMultiple int64              `json:"dispatch_cadence_multiple"`
	TranscriptCurrencyDays  int64              `json:"transcript_currency_days"`
	UpdatedBy               pgtype.Int8        `json:"updated_by"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

// The single operator-global row seeded by the migration; it always exists.
func (q *Queries) GetRetentionSettings(ctx context.Context) (GetRetentionSettingsRow, error) {
	row := q.db.QueryRow(ctx, getRetentionSettings)
	var i GetRetentionSettingsRow
	err := row.Scan(
		&i.ObservationCurrencyDays,
		&i.DispatchCadenceMultiple,
		&i.TranscriptCurrencyDays,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveObservationsForDerivation = `-- name: ListLiveObservationsForDerivation :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
)
SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
       o.vantage_id, o.source, o.value, o.observed_at, o.batch_id
FROM observation o
JOIN cover c
    ON  c.subject_key   = o.subject_key
    AND c.facet         = o.facet
    AND c.discriminator = o.discriminator
    AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
    AND c.source        = o.source
WHERE EXTRACT(EPOCH FROM ($1::timestamptz - o.observed_at))
      <= $2::bigint * c.tightest_cadence
ORDER BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source, o.observed_at
`

type ListLiveObservationsForDerivationParams struct {
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListLiveObservationsForDerivationRow struct {
	ID            int64              `json:"id"`
	Facet         string             `json:"facet"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	BatchID       int64              `json:"batch_id"`
}

// The read-side live-tier gate a derivation reads observations through (v1 spec
// §4.6, ADR-0041): it returns ONLY live-tier rows — those within k cadences of the
// tightest ENABLED Scan covering their timeline — so a derivation reading through
// it cannot re-derive history from a stale observation. Every production
// derivation read of the observation corpus inlines this gate's `cover` CTE and
// per-timeline age bound, evaluated against the caller's read instant (#237): the
// subjects, signals and Custody reads (db/queries/subjects.sql,
// db/queries/signals.sql, NameCitedAddresses in db/queries/measurement.sql) read
// through the gate, not the raw table, so an evidential row is structurally
// unreadable by a derivation the instant it crosses its bound — not merely absent
// after the Retirer's next sweep (which DeleteExpiredObservations below still runs
// to reclaim storage). This query is the shared, standalone form of that boundary.
// The bound is evaluated PER TIMELINE and never collapsed:
// `cover` groups by the full timeline key (subject, facet, discriminator, vantage,
// source) and takes the tightest covering cadence, so a zone-sourced row's live
// window is the zone cadence and a resolver-sourced row's is the resolver's. A
// timeline no enabled Scan covers has an undefined bound: the INNER JOIN drops it,
// so it yields no live row (it is retained as evidence, not read). @floor_cadences
// is k; @as_of is the read instant.
func (q *Queries) ListLiveObservationsForDerivation(ctx context.Context, arg ListLiveObservationsForDerivationParams) ([]ListLiveObservationsForDerivationRow, error) {
	rows, err := q.db.Query(ctx, listLiveObservationsForDerivation, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveObservationsForDerivationRow{}
	for rows.Next() {
		var i ListLiveObservationsForDerivationRow
		if err := rows.Scan(
			&i.ID,
			&i.Facet,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Discriminator,
			&i.VantageID,
			&i.Source,
			&i.Value,
			&i.ObservedAt,
			&i.BatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slowestEnabledScanCadenceSeconds = `-- name: SlowestEnabledScanCadenceSeconds :one
SELECT COALESCE(MAX(cadence_seconds), 0)::bigint AS cadence_seconds
FROM scan
WHERE enabled = TRUE
`

// The slowest enabled Scan's cadence — the largest cadence_seconds among enabled
// Scans — which the Dispatch dial is a multiple of and the floor k multiples of
// (v1 spec §4.6). COALESCE to 0 when no Scan is enabled: with no cadence the
// multiple has no meaning, so the sweep treats it as unbounded and retires
// nothing. It reads only the scan table and never the operational or measured
// corpora.
func (q *Queries) SlowestEnabledScanCadenceSeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, slowestEnabledScanCadenceSeconds)
	var cadence_seconds int64
	err := row.Scan(&cadence_seconds)
	return cadence_seconds, err
}

const tightestEnabledScanCadenceSeconds = `-- name: TightestEnabledScanCadenceSeconds :one
SELECT COALESCE(MIN(cadence_seconds), 0)::bigint AS cadence_seconds
FROM scan
WHERE enabled = TRUE
`

// The tightest enabled Scan's cadence — the smallest cadence_seconds among enabled
// Scans — which is k cadences of the smallest per-timeline observation bound any
// in-force timeline can carry, and therefore the observation dial's floor (v1 spec
// §4.6, ADR-0094). Symmetric to the Dispatch floor's SlowestEnabledScanCadence
// (which takes MAX): Dispatch floors at the slowest Scan, observations at the
// tightest. COALESCE to 0 when no Scan is enabled: with no bound in force there is
// nothing to floor against and the dial is unconstrained. Reads only the scan
// table, never the measured corpora.
func (q *Queries) TightestEnabledScanCadenceSeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, tightestEnabledScanCadenceSeconds)
	var cadence_seconds int64
	err := row.Scan(&cadence_seconds)
	return cadence_seconds, err
}

const updateRetentionSettings = `-- name: UpdateRetentionSettings :exec
UPDATE retention_settings
SET observation_currency_days = $1, dispatch_cadence_multiple = $2,
    updated_by = $3, updated_at = now()
WHERE id = true
`

type UpdateRetentionSettingsParams struct {
	ObservationCurrencyDays int64       `json:"observation_currency_days"`
	DispatchCadenceMultiple int64       `json:"dispatch_cadence_multiple"`
	UpdatedBy               pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpdateRetentionSettings(ctx context.Context, arg UpdateRetentionSettingsParams) error {
	_, err := q.db.Exec(ctx, updateRetentionSettings, arg.ObservationCurrencyDays, arg.DispatchCadenceMultiple, arg.UpdatedBy)
	return err
}
