// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seeds.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddressSeed = `-- name: CreateAddressSeed :one
INSERT INTO seed (kind, address_cidr, created_by)
VALUES ('address', $1, $2)
RETURNING id, kind, name_domain, address_cidr, created_by, created_at, custody_extension
`

type CreateAddressSeedParams struct {
	AddressCidr *netip.Prefix `json:"address_cidr"`
	CreatedBy   int64         `json:"created_by"`
}

func (q *Queries) CreateAddressSeed(ctx context.Context, arg CreateAddressSeedParams) (Seed, error) {
	row := q.db.QueryRow(ctx, createAddressSeed, arg.AddressCidr, arg.CreatedBy)
	var i Seed
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.NameDomain,
		&i.AddressCidr,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CustodyExtension,
	)
	return i, err
}

const createNameSeed = `-- name: CreateNameSeed :one
INSERT INTO seed (kind, name_domain, created_by)
VALUES ('name', $1, $2)
RETURNING id, kind, name_domain, address_cidr, created_by, created_at, custody_extension
`

type CreateNameSeedParams struct {
	NameDomain pgtype.Text `json:"name_domain"`
	CreatedBy  int64       `json:"created_by"`
}

func (q *Queries) CreateNameSeed(ctx context.Context, arg CreateNameSeedParams) (Seed, error) {
	row := q.db.QueryRow(ctx, createNameSeed, arg.NameDomain, arg.CreatedBy)
	var i Seed
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.NameDomain,
		&i.AddressCidr,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CustodyExtension,
	)
	return i, err
}

const deleteSeed = `-- name: DeleteSeed :execrows
DELETE FROM seed WHERE id = $1
`

// Withdraws a declared Seed by id (#21a: the Scope chip-remove act). A viewer
// never reaches it (requireAdmin). Idempotent: deleting a row already gone
// affects zero rows and is not an error, so a stale chip submit is a no-op.
func (q *Queries) DeleteSeed(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSeeds = `-- name: ListSeeds :many
SELECT s.id, s.kind, s.name_domain, s.address_cidr, s.custody_extension,
       s.created_by, s.created_at, a.username AS created_by_username
FROM seed s
JOIN account a ON a.id = s.created_by
ORDER BY s.created_at DESC, s.id DESC
`

type ListSeedsRow struct {
	ID                int64              `json:"id"`
	Kind              string             `json:"kind"`
	NameDomain        pgtype.Text        `json:"name_domain"`
	AddressCidr       *netip.Prefix      `json:"address_cidr"`
	CustodyExtension  bool               `json:"custody_extension"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUsername string             `json:"created_by_username"`
}

func (q *Queries) ListSeeds(ctx context.Context) ([]ListSeedsRow, error) {
	rows, err := q.db.Query(ctx, listSeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeedsRow{}
	for rows.Next() {
		var i ListSeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.NameDomain,
			&i.AddressCidr,
			&i.CustodyExtension,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
