// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBlanketedReachServices = `-- name: ListBlanketedReachServices :many
SELECT DISTINCT sp.subject_key AS subject_key
FROM span sp
WHERE sp.subject_kind = 'service'
  AND sp.facet = 'reachability'
  AND sp.closed_at IS NULL
  AND sp.is_gap = TRUE
ORDER BY sp.subject_key
`

func (q *Queries) ListBlanketedReachServices(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listBlanketedReachServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subject_key string
		if err := rows.Scan(&subject_key); err != nil {
			return nil, err
		}
		items = append(items, subject_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointCertificates = `-- name: ListEndpointCertificates :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
),
live AS (
    SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
           o.vantage_id, o.source, o.value, o.observed_at, o.batch_id
    FROM observation o
    JOIN cover c
        ON  c.subject_key   = o.subject_key
        AND c.facet         = o.facet
        AND c.discriminator = o.discriminator
        AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
        AND c.source        = o.source
    WHERE EXTRACT(EPOCH FROM ($1::timestamptz - o.observed_at))
          <= $2::bigint * c.tightest_cadence
),
latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value
    FROM live o
    WHERE o.subject_kind = 'endpoint' AND o.facet = 'certificate'
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value
FROM latest
ORDER BY subject_key
`

type ListEndpointCertificatesParams struct {
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListEndpointCertificatesRow struct {
	SubjectKey string `json:"subject_key"`
	Value      []byte `json:"value"`
}

func (q *Queries) ListEndpointCertificates(ctx context.Context, arg ListEndpointCertificatesParams) ([]ListEndpointCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listEndpointCertificates, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEndpointCertificatesRow{}
	for rows.Next() {
		var i ListEndpointCertificatesRow
		if err := rows.Scan(&i.SubjectKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameDNSRecords = `-- name: ListNameDNSRecords :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
),
live AS (
    SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
           o.vantage_id, o.source, o.value, o.observed_at, o.batch_id
    FROM observation o
    JOIN cover c
        ON  c.subject_key   = o.subject_key
        AND c.facet         = o.facet
        AND c.discriminator = o.discriminator
        AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
        AND c.source        = o.source
    WHERE EXTRACT(EPOCH FROM ($1::timestamptz - o.observed_at))
          <= $2::bigint * c.tightest_cadence
),
latest AS (
    SELECT DISTINCT ON (o.subject_key, o.discriminator)
        o.subject_key   AS subject_key,
        o.discriminator AS discriminator,
        o.value         AS value
    FROM live o
    WHERE o.facet = 'dns-record' AND o.subject_kind = 'name'
    ORDER BY o.subject_key, o.discriminator, o.observed_at DESC, o.id DESC
)
SELECT subject_key, discriminator, value
FROM latest
ORDER BY subject_key, discriminator
`

type ListNameDNSRecordsParams struct {
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListNameDNSRecordsRow struct {
	SubjectKey    string `json:"subject_key"`
	Discriminator string `json:"discriminator"`
	Value         []byte `json:"value"`
}

func (q *Queries) ListNameDNSRecords(ctx context.Context, arg ListNameDNSRecordsParams) ([]ListNameDNSRecordsRow, error) {
	rows, err := q.db.Query(ctx, listNameDNSRecords, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNameDNSRecordsRow{}
	for rows.Next() {
		var i ListNameDNSRecordsRow
		if err := rows.Scan(&i.SubjectKey, &i.Discriminator, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameResolutionsByClass = `-- name: ListNameResolutionsByClass :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
),
live AS (
    SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
           o.vantage_id, o.source, o.value, o.observed_at, o.batch_id
    FROM observation o
    JOIN cover c
        ON  c.subject_key   = o.subject_key
        AND c.facet         = o.facet
        AND c.discriminator = o.discriminator
        AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
        AND c.source        = o.source
    WHERE EXTRACT(EPOCH FROM ($1::timestamptz - o.observed_at))
          <= $2::bigint * c.tightest_cadence
),
latest AS (
    SELECT DISTINCT ON (o.subject_key, o.vantage_id)
        o.subject_key  AS subject_key,
        o.vantage_id   AS vantage_id,
        o.value        AS value,
        o.observed_at  AS observed_at,
        o.id           AS id,
        v.host         AS host,
        v.egress       AS egress,
        v.dialled_addr AS dialled_addr
    FROM live o
    JOIN vantage v ON v.id = o.vantage_id
    WHERE o.facet = 'resolution' AND o.subject_kind = 'name'
    ORDER BY o.subject_key, o.vantage_id, o.observed_at DESC, o.id DESC
)
SELECT subject_key, vantage_id, value, observed_at, id, host, egress, dialled_addr
FROM latest
ORDER BY subject_key, vantage_id
`

type ListNameResolutionsByClassParams struct {
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListNameResolutionsByClassRow struct {
	SubjectKey  string             `json:"subject_key"`
	VantageID   pgtype.Int8        `json:"vantage_id"`
	Value       []byte             `json:"value"`
	ObservedAt  pgtype.Timestamptz `json:"observed_at"`
	ID          int64              `json:"id"`
	Host        pgtype.Text        `json:"host"`
	Egress      pgtype.Text        `json:"egress"`
	DialledAddr pgtype.Text        `json:"dialled_addr"`
}

func (q *Queries) ListNameResolutionsByClass(ctx context.Context, arg ListNameResolutionsByClassParams) ([]ListNameResolutionsByClassRow, error) {
	rows, err := q.db.Query(ctx, listNameResolutionsByClass, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNameResolutionsByClassRow{}
	for rows.Next() {
		var i ListNameResolutionsByClassRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.VantageID,
			&i.Value,
			&i.ObservedAt,
			&i.ID,
			&i.Host,
			&i.Egress,
			&i.DialledAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceReachabilitySpansByClass = `-- name: ListServiceReachabilitySpansByClass :many
SELECT DISTINCT ON (sp.subject_key, sp.vantage_id)
    sp.subject_key AS subject_key,
    sp.vantage_id  AS vantage_id,
    sp.value       AS value,
    sp.is_gap      AS is_gap,
    sp.opened_at   AS opened_at,
    sp.id          AS id,
    v.host         AS host,
    v.egress       AS egress,
    v.dialled_addr AS dialled_addr
FROM span sp
JOIN vantage v ON v.id = sp.vantage_id
WHERE sp.subject_kind = 'service'
  AND sp.facet = 'reachability'
  AND sp.closed_at IS NULL
ORDER BY sp.subject_key, sp.vantage_id, sp.opened_at DESC, sp.id DESC
`

type ListServiceReachabilitySpansByClassRow struct {
	SubjectKey  string             `json:"subject_key"`
	VantageID   pgtype.Int8        `json:"vantage_id"`
	Value       []byte             `json:"value"`
	IsGap       bool               `json:"is_gap"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	ID          int64              `json:"id"`
	Host        pgtype.Text        `json:"host"`
	Egress      pgtype.Text        `json:"egress"`
	DialledAddr pgtype.Text        `json:"dialled_addr"`
}

// The span corpus is already derived, so an as_of bound would hide settled state (ADR-0105).
func (q *Queries) ListServiceReachabilitySpansByClass(ctx context.Context) ([]ListServiceReachabilitySpansByClassRow, error) {
	rows, err := q.db.Query(ctx, listServiceReachabilitySpansByClass)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceReachabilitySpansByClassRow{}
	for rows.Next() {
		var i ListServiceReachabilitySpansByClassRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.VantageID,
			&i.Value,
			&i.IsGap,
			&i.OpenedAt,
			&i.ID,
			&i.Host,
			&i.Egress,
			&i.DialledAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTLSAcceptance = `-- name: ListServiceTLSAcceptance :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
),
live AS (
    SELECT o.id, o.facet, o.subject_kind, o.subject_key, o.discriminator,
           o.vantage_id, o.source, o.value, o.observed_at, o.batch_id
    FROM observation o
    JOIN cover c
        ON  c.subject_key   = o.subject_key
        AND c.facet         = o.facet
        AND c.discriminator = o.discriminator
        AND c.vantage_id IS NOT DISTINCT FROM o.vantage_id
        AND c.source        = o.source
    WHERE EXTRACT(EPOCH FROM ($1::timestamptz - o.observed_at))
          <= $2::bigint * c.tightest_cadence
),
latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value
    FROM live o
    WHERE o.subject_kind = 'service' AND o.facet = 'tls-acceptance'
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value
FROM latest
ORDER BY subject_key
`

type ListServiceTLSAcceptanceParams struct {
	AsOf          pgtype.Timestamptz `json:"as_of"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListServiceTLSAcceptanceRow struct {
	SubjectKey string `json:"subject_key"`
	Value      []byte `json:"value"`
}

func (q *Queries) ListServiceTLSAcceptance(ctx context.Context, arg ListServiceTLSAcceptanceParams) ([]ListServiceTLSAcceptanceRow, error) {
	rows, err := q.db.Query(ctx, listServiceTLSAcceptance, arg.AsOf, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTLSAcceptanceRow{}
	for rows.Next() {
		var i ListServiceTLSAcceptanceRow
		if err := rows.Scan(&i.SubjectKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalInstances = `-- name: ListSignalInstances :many
SELECT id, signal_name, subject_key, first_seen
FROM signal_instance
ORDER BY signal_name, subject_key
`

func (q *Queries) ListSignalInstances(ctx context.Context) ([]SignalInstance, error) {
	rows, err := q.db.Query(ctx, listSignalInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignalInstance{}
	for rows.Next() {
		var i SignalInstance
		if err := rows.Scan(
			&i.ID,
			&i.SignalName,
			&i.SubjectKey,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneDeclarations = `-- name: ListZoneDeclarations :many
SELECT DISTINCT ON (z.seed_id)
    s.name_domain AS name_domain,
    z.content     AS content
FROM zone_file z
JOIN seed s ON s.id = z.seed_id
WHERE s.kind = 'name' AND s.name_domain IS NOT NULL
ORDER BY z.seed_id, z.supplied_at DESC, z.id DESC
`

type ListZoneDeclarationsRow struct {
	NameDomain pgtype.Text `json:"name_domain"`
	Content    string      `json:"content"`
}

func (q *Queries) ListZoneDeclarations(ctx context.Context) ([]ListZoneDeclarationsRow, error) {
	rows, err := q.db.Query(ctx, listZoneDeclarations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZoneDeclarationsRow{}
	for rows.Next() {
		var i ListZoneDeclarationsRow
		if err := rows.Scan(&i.NameDomain, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mintSignalInstances = `-- name: MintSignalInstances :exec
INSERT INTO signal_instance (signal_name, subject_key)
SELECT unnest($1::text[]), unnest($2::text[])
ON CONFLICT (signal_name, subject_key) DO NOTHING
`

type MintSignalInstancesParams struct {
	SignalNames []string `json:"signal_names"`
	SubjectKeys []string `json:"subject_keys"`
}

func (q *Queries) MintSignalInstances(ctx context.Context, arg MintSignalInstancesParams) error {
	_, err := q.db.Exec(ctx, mintSignalInstances, arg.SignalNames, arg.SubjectKeys)
	return err
}
