// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSourceHealth = `-- name: ListSourceHealth :many
SELECT slug, last_outcome, last_attempt_at, consecutive_failures
FROM source_health
`

func (q *Queries) ListSourceHealth(ctx context.Context) ([]SourceHealth, error) {
	rows, err := q.db.Query(ctx, listSourceHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceHealth{}
	for rows.Next() {
		var i SourceHealth
		if err := rows.Scan(
			&i.Slug,
			&i.LastOutcome,
			&i.LastAttemptAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSourceAttempt = `-- name: RecordSourceAttempt :one
INSERT INTO source_health (slug, last_outcome, last_attempt_at, consecutive_failures)
VALUES (
    $1,
    $2,
    $3,
    CASE WHEN $2::text = 'error' THEN 1 ELSE 0 END
)
ON CONFLICT (slug) DO UPDATE
    SET last_outcome = EXCLUDED.last_outcome,
        last_attempt_at = EXCLUDED.last_attempt_at,
        -- The count runs in the database, so two lookups at once cannot both read the same total.
        consecutive_failures = CASE
            WHEN EXCLUDED.last_outcome = 'error' THEN source_health.consecutive_failures + 1
            ELSE 0
        END
RETURNING slug, last_outcome, last_attempt_at, consecutive_failures
`

type RecordSourceAttemptParams struct {
	Slug          string             `json:"slug"`
	LastOutcome   string             `json:"last_outcome"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
}

func (q *Queries) RecordSourceAttempt(ctx context.Context, arg RecordSourceAttemptParams) (SourceHealth, error) {
	row := q.db.QueryRow(ctx, recordSourceAttempt, arg.Slug, arg.LastOutcome, arg.LastAttemptAt)
	var i SourceHealth
	err := row.Scan(
		&i.Slug,
		&i.LastOutcome,
		&i.LastAttemptAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}
