// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
)

const listSourceStates = `-- name: ListSourceStates :many
SELECT slug, enabled
FROM source_state
`

// The operator's overrides of the authored ship defaults. The handler merges
// these onto the in-binary catalogue: a source's effective state is its override
// where one exists and its shipped default otherwise.
func (q *Queries) ListSourceStates(ctx context.Context) ([]SourceState, error) {
	rows, err := q.db.Query(ctx, listSourceStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceState{}
	for rows.Next() {
		var i SourceState
		if err := rows.Scan(&i.Slug, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSourceState = `-- name: UpsertSourceState :one
INSERT INTO source_state (slug, enabled)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE
    SET enabled = EXCLUDED.enabled
RETURNING slug, enabled
`

type UpsertSourceStateParams struct {
	Slug    string `json:"slug"`
	Enabled bool   `json:"enabled"`
}

// Record the operator's on/off choice for one source. A toggle is a Declared act
// with no timeline, no actor, and no instant of its own (ADR-0073, ADR-0093), so
// re-toggling overwrites the single current value and the row holds only the
// overridden state.
func (q *Queries) UpsertSourceState(ctx context.Context, arg UpsertSourceStateParams) (SourceState, error) {
	row := q.db.QueryRow(ctx, upsertSourceState, arg.Slug, arg.Enabled)
	var i SourceState
	err := row.Scan(&i.Slug, &i.Enabled)
	return i, err
}
