// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: span.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSpan = `-- name: CloseSpan :exec
UPDATE span
SET closed_at = $1,
    closure_reason = $2,
    closed_batch_id = $3::bigint
WHERE id = $4 AND closed_at IS NULL
`

type CloseSpanParams struct {
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
	ClosedBatchID pgtype.Int8        `json:"closed_batch_id"`
	ID            int64              `json:"id"`
}

func (q *Queries) CloseSpan(ctx context.Context, arg CloseSpanParams) error {
	_, err := q.db.Exec(ctx, closeSpan,
		arg.ClosedAt,
		arg.ClosureReason,
		arg.ClosedBatchID,
		arg.ID,
	)
	return err
}

const getOpenSpan = `-- name: GetOpenSpan :one

SELECT id, subject_kind, subject_key, facet, discriminator, vantage_id, source,
       value, is_gap, derivation, opened_at, closed_at, closure_reason
FROM span
WHERE closed_at IS NULL
  AND subject_key = $1
  AND facet = $2
  AND discriminator = $3
  AND vantage_id IS NOT DISTINCT FROM $4::bigint
  AND source = $5
`

type GetOpenSpanParams struct {
	SubjectKey    string      `json:"subject_key"`
	Facet         string      `json:"facet"`
	Discriminator string      `json:"discriminator"`
	VantageID     pgtype.Int8 `json:"vantage_id"`
	Source        string      `json:"source"`
}

type GetOpenSpanRow struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
}

// An as-of bound here would hide settled history rather than protect a derivation (ADR-0105).
func (q *Queries) GetOpenSpan(ctx context.Context, arg GetOpenSpanParams) (GetOpenSpanRow, error) {
	row := q.db.QueryRow(ctx, getOpenSpan,
		arg.SubjectKey,
		arg.Facet,
		arg.Discriminator,
		arg.VantageID,
		arg.Source,
	)
	var i GetOpenSpanRow
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectKey,
		&i.Facet,
		&i.Discriminator,
		&i.VantageID,
		&i.Source,
		&i.Value,
		&i.IsGap,
		&i.Derivation,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosureReason,
	)
	return i, err
}

const listAllOpenSpans = `-- name: ListAllOpenSpans :many
SELECT id, subject_kind, subject_key, facet, discriminator, vantage_id, source,
       value, is_gap, derivation, opened_at, closed_at, closure_reason
FROM span
WHERE closed_at IS NULL
ORDER BY subject_kind, subject_key, facet, discriminator, vantage_id, source
`

type ListAllOpenSpansRow struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
}

func (q *Queries) ListAllOpenSpans(ctx context.Context) ([]ListAllOpenSpansRow, error) {
	rows, err := q.db.Query(ctx, listAllOpenSpans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOpenSpansRow{}
	for rows.Next() {
		var i ListAllOpenSpansRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Facet,
			&i.Discriminator,
			&i.VantageID,
			&i.Source,
			&i.Value,
			&i.IsGap,
			&i.Derivation,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitedAddressSpansForNames = `-- name: ListCitedAddressSpansForNames :many
WITH cited AS (
    SELECT DISTINCT a.addr
    FROM span n
    CROSS JOIN LATERAL jsonb_array_elements_text(
        CASE WHEN jsonb_typeof(n.value -> 'addresses') = 'array' THEN n.value -> 'addresses' END
    ) AS a(addr)
    WHERE n.subject_kind = 'name'
      AND n.facet = 'resolution'
      AND n.subject_key = ANY($1::text[])
)
SELECT s.id, s.subject_key,
       COALESCE((
           SELECT array_agg(DISTINCT r.subject_key)
           FROM span r
           WHERE r.closed_at IS NULL
             AND r.subject_kind = 'name'
             AND r.facet = 'resolution'
             AND r.is_gap = FALSE
             AND jsonb_typeof(r.value -> 'addresses') = 'array'
             AND r.value -> 'addresses' @> to_jsonb(s.subject_key)
       ), '{}'::text[])::text[] AS citers
FROM span s
JOIN cited c ON c.addr = s.subject_key
WHERE s.closed_at IS NULL
  AND s.subject_kind = 'address'
ORDER BY s.subject_key, s.id
`

type ListCitedAddressSpansForNamesRow struct {
	ID         int64    `json:"id"`
	SubjectKey string   `json:"subject_key"`
	Citers     []string `json:"citers"`
}

// The candidate set is what the departed Names ever cited, never every Address (ADR-0198 §1).
func (q *Queries) ListCitedAddressSpansForNames(ctx context.Context, names []string) ([]ListCitedAddressSpansForNamesRow, error) {
	rows, err := q.db.Query(ctx, listCitedAddressSpansForNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitedAddressSpansForNamesRow{}
	for rows.Next() {
		var i ListCitedAddressSpansForNamesRow
		if err := rows.Scan(&i.ID, &i.SubjectKey, &i.Citers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNameCitationSpansWithinCurrency = `-- name: ListNameCitationSpansWithinCurrency :many
WITH cover AS (
    SELECT o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source,
           MIN(s.cadence_seconds) AS tightest_cadence
    FROM observation o
    JOIN batch b ON b.id = o.batch_id
    JOIN scan  s ON s.id = b.scan_id AND s.enabled = TRUE
    WHERE o.subject_kind = 'name' AND o.facet IN ('resolution', 'dns-record')
    GROUP BY o.subject_key, o.facet, o.discriminator, o.vantage_id, o.source
)
SELECT sp.subject_key, sp.vantage_id, sp.facet, sp.value, sp.opened_at, sp.closed_at
FROM span sp
JOIN cover c
    ON  c.subject_key   = sp.subject_key
    AND c.facet         = sp.facet
    AND c.discriminator = sp.discriminator
    AND c.vantage_id IS NOT DISTINCT FROM sp.vantage_id
    AND c.source        = sp.source
WHERE sp.subject_kind = 'name'
  AND sp.facet IN ('resolution', 'dns-record')
  AND NOT sp.is_gap
  AND sp.opened_at <= $1::timestamptz
  AND (sp.closed_at IS NULL
       OR EXTRACT(EPOCH FROM ($1::timestamptz - sp.closed_at))
          <= $2::bigint * c.tightest_cadence)
ORDER BY sp.subject_key, sp.vantage_id, sp.facet, sp.opened_at, sp.id
`

type ListNameCitationSpansWithinCurrencyParams struct {
	At            pgtype.Timestamptz `json:"at"`
	FloorCadences int64              `json:"floor_cadences"`
}

type ListNameCitationSpansWithinCurrencyRow struct {
	SubjectKey string             `json:"subject_key"`
	VantageID  pgtype.Int8        `json:"vantage_id"`
	Facet      string             `json:"facet"`
	Value      []byte             `json:"value"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
}

// The window is each timeline's own currency bound, the one NameCitedAddresses reads (ADR-0044).
func (q *Queries) ListNameCitationSpansWithinCurrency(ctx context.Context, arg ListNameCitationSpansWithinCurrencyParams) ([]ListNameCitationSpansWithinCurrencyRow, error) {
	rows, err := q.db.Query(ctx, listNameCitationSpansWithinCurrency, arg.At, arg.FloorCadences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNameCitationSpansWithinCurrencyRow{}
	for rows.Next() {
		var i ListNameCitationSpansWithinCurrencyRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.VantageID,
			&i.Facet,
			&i.Value,
			&i.OpenedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSpansBeneathAddresses = `-- name: ListOpenSpansBeneathAddresses :many
SELECT s.id, s.subject_kind, s.subject_key
FROM span s
WHERE s.closed_at IS NULL
  AND s.subject_kind IN ('service', 'endpoint')
  AND EXISTS (
      SELECT 1 FROM unnest($1::text[]) AS a(addr)
      WHERE s.subject_key LIKE a.addr || ':%'
         OR s.subject_key LIKE '[' || a.addr || ']:%'
         OR s.subject_key LIKE '%@' || a.addr || ':%'
         OR s.subject_key LIKE '%@[' || a.addr || ']:%'
  )
ORDER BY s.subject_kind, s.subject_key, s.id
`

type ListOpenSpansBeneathAddressesRow struct {
	ID          int64  `json:"id"`
	SubjectKind string `json:"subject_kind"`
	SubjectKey  string `json:"subject_key"`
}

// LIKE only prefilters; Go re-parses each key, so a loose pattern closes no stranger (#1689).
func (q *Queries) ListOpenSpansBeneathAddresses(ctx context.Context, addresses []string) ([]ListOpenSpansBeneathAddressesRow, error) {
	rows, err := q.db.Query(ctx, listOpenSpansBeneathAddresses, addresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenSpansBeneathAddressesRow{}
	for rows.Next() {
		var i ListOpenSpansBeneathAddressesRow
		if err := rows.Scan(&i.ID, &i.SubjectKind, &i.SubjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSpansForSubject = `-- name: ListOpenSpansForSubject :many
SELECT id, subject_kind, subject_key, facet, discriminator, vantage_id, source,
       value, is_gap, derivation, opened_at, closed_at, closure_reason
FROM span
WHERE subject_kind = $1 AND subject_key = $2 AND closed_at IS NULL
ORDER BY facet, discriminator, vantage_id, source
`

type ListOpenSpansForSubjectParams struct {
	SubjectKind string `json:"subject_kind"`
	SubjectKey  string `json:"subject_key"`
}

type ListOpenSpansForSubjectRow struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
}

func (q *Queries) ListOpenSpansForSubject(ctx context.Context, arg ListOpenSpansForSubjectParams) ([]ListOpenSpansForSubjectRow, error) {
	rows, err := q.db.Query(ctx, listOpenSpansForSubject, arg.SubjectKind, arg.SubjectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenSpansForSubjectRow{}
	for rows.Next() {
		var i ListOpenSpansForSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Facet,
			&i.Discriminator,
			&i.VantageID,
			&i.Source,
			&i.Value,
			&i.IsGap,
			&i.Derivation,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReachedServices = `-- name: ListReachedServices :many
SELECT sp.subject_key AS service_key, sp.vantage_id AS vantage_id
FROM span sp
WHERE sp.subject_kind = 'service'
  AND sp.facet = 'reachability'
  AND sp.closed_at IS NULL
  AND sp.is_gap = FALSE
  AND (sp.value ->> 'outcome') = 'reached'
ORDER BY sp.vantage_id, sp.subject_key
`

type ListReachedServicesRow struct {
	ServiceKey string      `json:"service_key"`
	VantageID  pgtype.Int8 `json:"vantage_id"`
}

func (q *Queries) ListReachedServices(ctx context.Context) ([]ListReachedServicesRow, error) {
	rows, err := q.db.Query(ctx, listReachedServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReachedServicesRow{}
	for rows.Next() {
		var i ListReachedServicesRow
		if err := rows.Scan(&i.ServiceKey, &i.VantageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDriftEvents = `-- name: ListRecentDriftEvents :many
SELECT
    'opened'::text   AS role,
    b.id             AS batch_id,
    b.kind           AS batch_kind,
    b.created_at     AS batch_at,
    b.recorded_scope AS recorded_scope,
    sp.subject_kind, sp.subject_key, sp.facet, sp.discriminator,
    sp.value, sp.is_gap, sp.derivation,
    sp.opened_at, sp.closed_at, sp.closure_reason,
    sp.opened_aperture  AS opened_aperture,
    pred.value          AS prev_value,
    pred.derivation     AS prev_derivation,
    pred.closed_at      AS prev_closed_at,
    pred.closure_reason AS prev_closure_reason,
    -- A Break on any resolution witness open at this instant voids returned (ADR-0097).
    EXISTS (
        SELECT 1
        FROM span w
        WHERE w.subject_kind = sp.subject_kind
          AND w.subject_key = sp.subject_key
          AND w.facet = 'resolution'
          AND w.opened_at <= sp.opened_at
          AND (w.closed_at IS NULL OR w.closed_at > sp.opened_at)
          AND w.derivation <> (
              SELECT wp.derivation
              FROM span wp
              WHERE wp.subject_kind = w.subject_kind
                AND wp.subject_key = w.subject_key
                AND wp.facet = w.facet
                AND wp.discriminator = w.discriminator
                AND wp.vantage_id IS NOT DISTINCT FROM w.vantage_id
                AND wp.source = w.source
                AND (wp.opened_at < w.opened_at OR (wp.opened_at = w.opened_at AND wp.id < w.id))
              ORDER BY wp.opened_at DESC, wp.id DESC
              LIMIT 1
          )
    )::boolean AS witness_broke
FROM span sp
JOIN batch b ON b.id = sp.opened_batch_id
LEFT JOIN LATERAL (
    SELECT p.value, p.derivation, p.closed_at, p.closure_reason
    FROM span p
    WHERE p.subject_kind = sp.subject_kind
      AND p.subject_key = sp.subject_key
      AND p.facet = sp.facet
      AND p.discriminator = sp.discriminator
      AND p.vantage_id IS NOT DISTINCT FROM sp.vantage_id
      AND p.source = sp.source
      AND (p.opened_at < sp.opened_at OR (p.opened_at = sp.opened_at AND p.id < sp.id))
    ORDER BY p.opened_at DESC, p.id DESC
    LIMIT 1
) pred ON true
WHERE b.created_at >= $2
  AND ($3::timestamptz IS NULL OR b.created_at < $3::timestamptz)

UNION ALL

SELECT
    'closed'::text   AS role,
    b.id             AS batch_id,
    b.kind           AS batch_kind,
    b.created_at     AS batch_at,
    b.recorded_scope AS recorded_scope,
    sp.subject_kind, sp.subject_key, sp.facet, sp.discriminator,
    sp.value, sp.is_gap, sp.derivation,
    sp.opened_at, sp.closed_at, sp.closure_reason,
    FALSE              AS opened_aperture,
    NULL::jsonb        AS prev_value,
    NULL::jsonb        AS prev_derivation,
    NULL::timestamptz  AS prev_closed_at,
    NULL::text         AS prev_closure_reason,
    FALSE              AS witness_broke
FROM span sp
JOIN batch b ON b.id = sp.closed_batch_id
WHERE b.created_at >= $2
  AND ($3::timestamptz IS NULL OR b.created_at < $3::timestamptz)
  -- A value-move close rides its successor's opened row, so counting it doubles the transition.
  AND sp.closure_reason IS NOT NULL

ORDER BY batch_at DESC, batch_id DESC, subject_kind, subject_key, facet, discriminator, opened_at
LIMIT $1
`

type ListRecentDriftEventsParams struct {
	MaxEvents int32              `json:"max_events"`
	Since     pgtype.Timestamptz `json:"since"`
	Until     pgtype.Timestamptz `json:"until"`
}

type ListRecentDriftEventsRow struct {
	Role              string             `json:"role"`
	BatchID           int64              `json:"batch_id"`
	BatchKind         string             `json:"batch_kind"`
	BatchAt           pgtype.Timestamptz `json:"batch_at"`
	RecordedScope     []byte             `json:"recorded_scope"`
	SubjectKind       string             `json:"subject_kind"`
	SubjectKey        string             `json:"subject_key"`
	Facet             string             `json:"facet"`
	Discriminator     string             `json:"discriminator"`
	Value             []byte             `json:"value"`
	IsGap             bool               `json:"is_gap"`
	Derivation        []byte             `json:"derivation"`
	OpenedAt          pgtype.Timestamptz `json:"opened_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	ClosureReason     pgtype.Text        `json:"closure_reason"`
	OpenedAperture    bool               `json:"opened_aperture"`
	PrevValue         []byte             `json:"prev_value"`
	PrevDerivation    []byte             `json:"prev_derivation"`
	PrevClosedAt      pgtype.Timestamptz `json:"prev_closed_at"`
	PrevClosureReason pgtype.Text        `json:"prev_closure_reason"`
	WitnessBroke      bool               `json:"witness_broke"`
}

func (q *Queries) ListRecentDriftEvents(ctx context.Context, arg ListRecentDriftEventsParams) ([]ListRecentDriftEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentDriftEvents, arg.MaxEvents, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDriftEventsRow{}
	for rows.Next() {
		var i ListRecentDriftEventsRow
		if err := rows.Scan(
			&i.Role,
			&i.BatchID,
			&i.BatchKind,
			&i.BatchAt,
			&i.RecordedScope,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Facet,
			&i.Discriminator,
			&i.Value,
			&i.IsGap,
			&i.Derivation,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosureReason,
			&i.OpenedAperture,
			&i.PrevValue,
			&i.PrevDerivation,
			&i.PrevClosedAt,
			&i.PrevClosureReason,
			&i.WitnessBroke,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceReachabilitySpansByClassAt = `-- name: ListServiceReachabilitySpansByClassAt :many
SELECT DISTINCT ON (sp.subject_key, sp.vantage_id)
    sp.subject_key AS subject_key,
    sp.vantage_id  AS vantage_id,
    sp.value       AS value,
    sp.is_gap      AS is_gap,
    sp.opened_at   AS opened_at,
    sp.id          AS id,
    v.host         AS host,
    v.egress       AS egress,
    v.dialled_addr AS dialled_addr
FROM span sp
JOIN vantage v ON v.id = sp.vantage_id
WHERE sp.subject_kind = 'service'
  AND sp.facet = 'reachability'
  AND sp.opened_at <= $1
  AND (sp.closed_at IS NULL OR sp.closed_at > $1)
ORDER BY sp.subject_key, sp.vantage_id, sp.opened_at DESC, sp.id DESC
`

type ListServiceReachabilitySpansByClassAtRow struct {
	SubjectKey  string             `json:"subject_key"`
	VantageID   pgtype.Int8        `json:"vantage_id"`
	Value       []byte             `json:"value"`
	IsGap       bool               `json:"is_gap"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	ID          int64              `json:"id"`
	Host        pgtype.Text        `json:"host"`
	Egress      pgtype.Text        `json:"egress"`
	DialledAddr pgtype.Text        `json:"dialled_addr"`
}

func (q *Queries) ListServiceReachabilitySpansByClassAt(ctx context.Context, at pgtype.Timestamptz) ([]ListServiceReachabilitySpansByClassAtRow, error) {
	rows, err := q.db.Query(ctx, listServiceReachabilitySpansByClassAt, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceReachabilitySpansByClassAtRow{}
	for rows.Next() {
		var i ListServiceReachabilitySpansByClassAtRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.VantageID,
			&i.Value,
			&i.IsGap,
			&i.OpenedAt,
			&i.ID,
			&i.Host,
			&i.Egress,
			&i.DialledAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceReachabilitySpansByClassAtForServices = `-- name: ListServiceReachabilitySpansByClassAtForServices :many
SELECT DISTINCT ON (sp.subject_key, sp.vantage_id)
    sp.subject_key AS subject_key,
    sp.vantage_id  AS vantage_id,
    sp.value       AS value,
    sp.is_gap      AS is_gap,
    sp.opened_at   AS opened_at,
    sp.id          AS id,
    v.host         AS host,
    v.egress       AS egress,
    v.dialled_addr AS dialled_addr
FROM span sp
JOIN vantage v ON v.id = sp.vantage_id
WHERE sp.subject_kind = 'service'
  AND sp.facet = 'reachability'
  AND sp.subject_key = ANY($1::text[])
  AND sp.opened_at <= $2
  AND (sp.closed_at IS NULL OR sp.closed_at > $2)
ORDER BY sp.subject_key, sp.vantage_id, sp.opened_at DESC, sp.id DESC
`

type ListServiceReachabilitySpansByClassAtForServicesParams struct {
	ServiceKeys []string           `json:"service_keys"`
	At          pgtype.Timestamptz `json:"at"`
}

type ListServiceReachabilitySpansByClassAtForServicesRow struct {
	SubjectKey  string             `json:"subject_key"`
	VantageID   pgtype.Int8        `json:"vantage_id"`
	Value       []byte             `json:"value"`
	IsGap       bool               `json:"is_gap"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	ID          int64              `json:"id"`
	Host        pgtype.Text        `json:"host"`
	Egress      pgtype.Text        `json:"egress"`
	DialledAddr pgtype.Text        `json:"dialled_addr"`
}

// The bound limits the per-job read to the batch's Services, not the corpus (ADR-0226 §1, #1609).
func (q *Queries) ListServiceReachabilitySpansByClassAtForServices(ctx context.Context, arg ListServiceReachabilitySpansByClassAtForServicesParams) ([]ListServiceReachabilitySpansByClassAtForServicesRow, error) {
	rows, err := q.db.Query(ctx, listServiceReachabilitySpansByClassAtForServices, arg.ServiceKeys, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceReachabilitySpansByClassAtForServicesRow{}
	for rows.Next() {
		var i ListServiceReachabilitySpansByClassAtForServicesRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.VantageID,
			&i.Value,
			&i.IsGap,
			&i.OpenedAt,
			&i.ID,
			&i.Host,
			&i.Egress,
			&i.DialledAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansForSubject = `-- name: ListSpansForSubject :many
SELECT s.id, s.subject_kind, s.subject_key, s.facet, s.discriminator, s.vantage_id, s.source,
       s.value, s.is_gap, s.derivation, s.opened_at, s.closed_at, s.closure_reason,
       v.name AS vantage_name
FROM span s
LEFT JOIN vantage v ON v.id = s.vantage_id
WHERE s.subject_kind = $1 AND s.subject_key = $2
ORDER BY s.facet, s.discriminator, s.vantage_id, s.source, s.opened_at, s.id
`

type ListSpansForSubjectParams struct {
	SubjectKind string `json:"subject_kind"`
	SubjectKey  string `json:"subject_key"`
}

type ListSpansForSubjectRow struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
	VantageName   pgtype.Text        `json:"vantage_name"`
}

func (q *Queries) ListSpansForSubject(ctx context.Context, arg ListSpansForSubjectParams) ([]ListSpansForSubjectRow, error) {
	rows, err := q.db.Query(ctx, listSpansForSubject, arg.SubjectKind, arg.SubjectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpansForSubjectRow{}
	for rows.Next() {
		var i ListSpansForSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Facet,
			&i.Discriminator,
			&i.VantageID,
			&i.Source,
			&i.Value,
			&i.IsGap,
			&i.Derivation,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosureReason,
			&i.VantageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansOpenSince = `-- name: ListSpansOpenSince :many
SELECT id, subject_kind, subject_key, facet, discriminator, vantage_id, source,
       value, is_gap, derivation, opened_at, closed_at, closure_reason
FROM span
WHERE closed_at IS NULL OR closed_at > $1
ORDER BY subject_kind, subject_key, facet, discriminator, vantage_id, source, opened_at
`

type ListSpansOpenSinceRow struct {
	ID            int64              `json:"id"`
	SubjectKind   string             `json:"subject_kind"`
	SubjectKey    string             `json:"subject_key"`
	Facet         string             `json:"facet"`
	Discriminator string             `json:"discriminator"`
	VantageID     pgtype.Int8        `json:"vantage_id"`
	Source        string             `json:"source"`
	Value         []byte             `json:"value"`
	IsGap         bool               `json:"is_gap"`
	Derivation    []byte             `json:"derivation"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	ClosureReason pgtype.Text        `json:"closure_reason"`
}

func (q *Queries) ListSpansOpenSince(ctx context.Context, since pgtype.Timestamptz) ([]ListSpansOpenSinceRow, error) {
	rows, err := q.db.Query(ctx, listSpansOpenSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpansOpenSinceRow{}
	for rows.Next() {
		var i ListSpansOpenSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Facet,
			&i.Discriminator,
			&i.VantageID,
			&i.Source,
			&i.Value,
			&i.IsGap,
			&i.Derivation,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectFirstAppearances = `-- name: ListSubjectFirstAppearances :many
SELECT
    sp.subject_kind AS subject_kind,
    sp.subject_key  AS subject_key,
    MIN(sp.opened_at)::timestamptz AS first_opened
FROM span sp
WHERE sp.subject_kind IN ('name', 'service')
GROUP BY sp.subject_kind, sp.subject_key
HAVING MIN(sp.opened_at) >= $1
ORDER BY first_opened, sp.subject_kind, sp.subject_key
`

type ListSubjectFirstAppearancesRow struct {
	SubjectKind string             `json:"subject_kind"`
	SubjectKey  string             `json:"subject_key"`
	FirstOpened pgtype.Timestamptz `json:"first_opened"`
}

func (q *Queries) ListSubjectFirstAppearances(ctx context.Context, since pgtype.Timestamptz) ([]ListSubjectFirstAppearancesRow, error) {
	rows, err := q.db.Query(ctx, listSubjectFirstAppearances, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectFirstAppearancesRow{}
	for rows.Next() {
		var i ListSubjectFirstAppearancesRow
		if err := rows.Scan(&i.SubjectKind, &i.SubjectKey, &i.FirstOpened); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalLifespans = `-- name: ListWithdrawalLifespans :many
SELECT DISTINCT ON (w.subject_kind, w.subject_key, w.closed_at)
    w.subject_kind AS subject_kind,
    w.subject_key  AS subject_key,
    w.closed_at    AS withdrawn_at,
    fa.first_opened AS first_opened
FROM span w
JOIN LATERAL (
    SELECT MIN(p.opened_at)::timestamptz AS first_opened
    FROM span p
    WHERE p.subject_kind = w.subject_kind
      AND p.subject_key = w.subject_key
) fa ON TRUE
WHERE w.closure_reason IS NOT NULL
  AND w.closed_at IS NOT NULL
  AND w.closed_at >= $1
ORDER BY w.subject_kind, w.subject_key, w.closed_at, w.id
`

type ListWithdrawalLifespansRow struct {
	SubjectKind string             `json:"subject_kind"`
	SubjectKey  string             `json:"subject_key"`
	WithdrawnAt pgtype.Timestamptz `json:"withdrawn_at"`
	FirstOpened pgtype.Timestamptz `json:"first_opened"`
}

func (q *Queries) ListWithdrawalLifespans(ctx context.Context, since pgtype.Timestamptz) ([]ListWithdrawalLifespansRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawalLifespans, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWithdrawalLifespansRow{}
	for rows.Next() {
		var i ListWithdrawalLifespansRow
		if err := rows.Scan(
			&i.SubjectKind,
			&i.SubjectKey,
			&i.WithdrawnAt,
			&i.FirstOpened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openSpan = `-- name: OpenSpan :one
INSERT INTO span (
    subject_kind, subject_key, facet, discriminator, vantage_id, source,
    value, is_gap, derivation, opened_at, opened_batch_id, opened_aperture
) VALUES (
    $1, $2, $3, $4, $5::bigint,
    $6, $7, $8, $9, $10, $11::bigint,
    $12
)
RETURNING id
`

type OpenSpanParams struct {
	SubjectKind    string             `json:"subject_kind"`
	SubjectKey     string             `json:"subject_key"`
	Facet          string             `json:"facet"`
	Discriminator  string             `json:"discriminator"`
	VantageID      pgtype.Int8        `json:"vantage_id"`
	Source         string             `json:"source"`
	Value          []byte             `json:"value"`
	IsGap          bool               `json:"is_gap"`
	Derivation     []byte             `json:"derivation"`
	OpenedAt       pgtype.Timestamptz `json:"opened_at"`
	OpenedBatchID  pgtype.Int8        `json:"opened_batch_id"`
	OpenedAperture bool               `json:"opened_aperture"`
}

func (q *Queries) OpenSpan(ctx context.Context, arg OpenSpanParams) (int64, error) {
	row := q.db.QueryRow(ctx, openSpan,
		arg.SubjectKind,
		arg.SubjectKey,
		arg.Facet,
		arg.Discriminator,
		arg.VantageID,
		arg.Source,
		arg.Value,
		arg.IsGap,
		arg.Derivation,
		arg.OpenedAt,
		arg.OpenedBatchID,
		arg.OpenedAperture,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
