// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSSOProvider = `-- name: DeleteSSOProvider :exec
DELETE FROM sso_provider WHERE id = $1
`

func (q *Queries) DeleteSSOProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSSOProvider, id)
	return err
}

const getSSOProvider = `-- name: GetSSOProvider :one
SELECT id, slug, name, issuer, client_id, username_claim, enabled,
       (client_secret IS NOT NULL)::boolean AS has_secret, created_by, created_at, updated_at
FROM sso_provider
WHERE id = $1
`

type GetSSOProviderRow struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Issuer        string             `json:"issuer"`
	ClientID      string             `json:"client_id"`
	UsernameClaim string             `json:"username_claim"`
	Enabled       bool               `json:"enabled"`
	HasSecret     bool               `json:"has_secret"`
	CreatedBy     int64              `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// One provider for the Settings edit form. Omits the secret; a caller reads presence,
// never the value.
func (q *Queries) GetSSOProvider(ctx context.Context, id int64) (GetSSOProviderRow, error) {
	row := q.db.QueryRow(ctx, getSSOProvider, id)
	var i GetSSOProviderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.UsernameClaim,
		&i.Enabled,
		&i.HasSecret,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOProviderForAuth = `-- name: GetSSOProviderForAuth :one
SELECT id, slug, name, issuer, client_id, client_secret, username_claim
FROM sso_provider
WHERE slug = $1 AND enabled = TRUE
`

type GetSSOProviderForAuthRow struct {
	ID            int64       `json:"id"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	Issuer        string      `json:"issuer"`
	ClientID      string      `json:"client_id"`
	ClientSecret  pgtype.Text `json:"client_secret"`
	UsernameClaim string      `json:"username_claim"`
}

// The ONE read path that selects the secret: the server-side OIDC flow needs the
// issuer, client id and client secret to complete the confidential-client token
// exchange, plus the username claim to map the verified identity to a local account.
// Keyed by slug (the flow route) and gated on enabled, so a disabled provider's flow
// resolves no row and is refused.
func (q *Queries) GetSSOProviderForAuth(ctx context.Context, slug string) (GetSSOProviderForAuthRow, error) {
	row := q.db.QueryRow(ctx, getSSOProviderForAuth, slug)
	var i GetSSOProviderForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.UsernameClaim,
	)
	return i, err
}

const insertSSOProvider = `-- name: InsertSSOProvider :one

INSERT INTO sso_provider (slug, name, issuer, client_id, client_secret, username_claim, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertSSOProviderParams struct {
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	Issuer        string      `json:"issuer"`
	ClientID      string      `json:"client_id"`
	ClientSecret  pgtype.Text `json:"client_secret"`
	UsernameClaim string      `json:"username_claim"`
	Enabled       bool        `json:"enabled"`
	CreatedBy     int64       `json:"created_by"`
}

// Reads and writes behind the OIDC single-sign-on config (#293, ADR-0112): the
// SignIn buttons, the Settings → single-sign-on tab, and the server-side flow. The
// client secret is write-only at the interface, mirroring the channel secret
// (ADR-0053): the list/get reads expose only whether one is set, and exactly one
// read path (GetSSOProviderForAuth) hands the secret to the token exchange.
// Declare one OIDC provider. Returns the id only; the secret is write-only and no
// read query hands it back. A public (PKCE-only) client passes a NULL secret.
func (q *Queries) InsertSSOProvider(ctx context.Context, arg InsertSSOProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSSOProvider,
		arg.Slug,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.UsernameClaim,
		arg.Enabled,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEnabledSSOProviders = `-- name: ListEnabledSSOProviders :many
SELECT id, slug, name
FROM sso_provider
WHERE enabled = TRUE
ORDER BY id DESC
`

type ListEnabledSSOProvidersRow struct {
	ID   int64  `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// The enabled providers the SignIn screen renders a button for, newest-first. No
// secret, and no created-by join — SignIn is pre-auth and needs only what a button
// carries: the slug (its route) and the display name.
func (q *Queries) ListEnabledSSOProviders(ctx context.Context) ([]ListEnabledSSOProvidersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledSSOProvidersRow{}
	for rows.Next() {
		var i ListEnabledSSOProvidersRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOProviders = `-- name: ListSSOProviders :many
SELECT p.id, p.slug, p.name, p.issuer, p.client_id, p.username_claim, p.enabled,
       (p.client_secret IS NOT NULL)::boolean AS has_secret,
       p.created_by, p.created_at, p.updated_at,
       a.username AS created_by_username
FROM sso_provider p
JOIN account a ON a.id = p.created_by
ORDER BY p.id DESC
`

type ListSSOProvidersRow struct {
	ID                int64              `json:"id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Issuer            string             `json:"issuer"`
	ClientID          string             `json:"client_id"`
	UsernameClaim     string             `json:"username_claim"`
	Enabled           bool               `json:"enabled"`
	HasSecret         bool               `json:"has_secret"`
	CreatedBy         int64              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername string             `json:"created_by_username"`
}

// Every configured provider, newest-first, for the Settings tab. Never selects the
// secret: it exposes only whether one is set, so the render path cannot leak it.
func (q *Queries) ListSSOProviders(ctx context.Context) ([]ListSSOProvidersRow, error) {
	rows, err := q.db.Query(ctx, listSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSOProvidersRow{}
	for rows.Next() {
		var i ListSSOProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Issuer,
			&i.ClientID,
			&i.UsernameClaim,
			&i.Enabled,
			&i.HasSecret,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSSOProviderSecret = `-- name: SetSSOProviderSecret :exec
UPDATE sso_provider SET client_secret = $2, updated_at = now() WHERE id = $1
`

type SetSSOProviderSecretParams struct {
	ID           int64       `json:"id"`
	ClientSecret pgtype.Text `json:"client_secret"`
}

// Set, replace or clear the secret. A NULL clears it (a public PKCE-only client); the
// value is written and never read back through any interface query.
func (q *Queries) SetSSOProviderSecret(ctx context.Context, arg SetSSOProviderSecretParams) error {
	_, err := q.db.Exec(ctx, setSSOProviderSecret, arg.ID, arg.ClientSecret)
	return err
}

const updateSSOProvider = `-- name: UpdateSSOProvider :exec
UPDATE sso_provider
SET slug = $2, name = $3, issuer = $4, client_id = $5, username_claim = $6,
    enabled = $7, updated_at = now()
WHERE id = $1
`

type UpdateSSOProviderParams struct {
	ID            int64  `json:"id"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	Issuer        string `json:"issuer"`
	ClientID      string `json:"client_id"`
	UsernameClaim string `json:"username_claim"`
	Enabled       bool   `json:"enabled"`
}

// Updates everything but the secret; the secret has its own write path, so an edit
// that leaves it blank keeps the existing one untouched (exactly the channel pattern).
func (q *Queries) UpdateSSOProvider(ctx context.Context, arg UpdateSSOProviderParams) error {
	_, err := q.db.Exec(ctx, updateSSOProvider,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Issuer,
		arg.ClientID,
		arg.UsernameClaim,
		arg.Enabled,
	)
	return err
}
