// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const findCoveringAddressSeed = `-- name: FindCoveringAddressSeed :one
SELECT s.id, s.address_cidr, s.created_at, a.username AS created_by_username
FROM seed s
JOIN account a ON a.id = s.created_by
WHERE s.kind = 'address' AND s.address_cidr IS NOT NULL
  AND s.address_cidr >>= $1::inet
ORDER BY masklen(s.address_cidr) DESC
LIMIT 1
`

type FindCoveringAddressSeedRow struct {
	ID                int64              `json:"id"`
	AddressCidr       *netip.Prefix      `json:"address_cidr"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUsername string             `json:"created_by_username"`
}

// The address-scope Seed a Service's Address falls inside (#195) — the other
// limb of Address membership, and where the Citation chain terminates when no
// resolution cites the Address. Native CIDR containment (`>>=`) is a test over
// the address and never its spelling, so the gate cannot turn on a rendering
// (CONTEXT.md `Seed`). The most specific covering scope wins where scopes nest.
func (q *Queries) FindCoveringAddressSeed(ctx context.Context, address netip.Addr) (FindCoveringAddressSeedRow, error) {
	row := q.db.QueryRow(ctx, findCoveringAddressSeed, address)
	var i FindCoveringAddressSeedRow
	err := row.Scan(
		&i.ID,
		&i.AddressCidr,
		&i.CreatedAt,
		&i.CreatedByUsername,
	)
	return i, err
}

const findCoveringNameSeed = `-- name: FindCoveringNameSeed :one
SELECT s.id, s.name_domain, s.created_at, a.username AS created_by_username
FROM seed s
JOIN account a ON a.id = s.created_by
WHERE s.kind = 'name' AND s.name_domain IS NOT NULL
  AND ($1::text = s.name_domain OR $1::text LIKE '%.' || s.name_domain)
ORDER BY length(s.name_domain) DESC
LIMIT 1
`

type FindCoveringNameSeedRow struct {
	ID                int64              `json:"id"`
	NameDomain        pgtype.Text        `json:"name_domain"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUsername string             `json:"created_by_username"`
}

// The Seed a Name's Citation chain terminates at: the name scope whose query set
// the dns Scan was drawn from (CONTEXT.md `Citation` — every chain bottoms out at
// a Seed or a declared source). Wave-0 measures the seed domains themselves; the
// label-wise suffix match also carries a later enumerated subdomain to its scope,
// and the longest matching domain wins when scopes nest.
func (q *Queries) FindCoveringNameSeed(ctx context.Context, name string) (FindCoveringNameSeedRow, error) {
	row := q.db.QueryRow(ctx, findCoveringNameSeed, name)
	var i FindCoveringNameSeedRow
	err := row.Scan(
		&i.ID,
		&i.NameDomain,
		&i.CreatedAt,
		&i.CreatedByUsername,
	)
	return i, err
}

const findNameCitingAddress = `-- name: FindNameCitingAddress :one
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key, o.vantage_id)
        o.subject_key AS subject_key,
        o.value->>'outcome' AS outcome,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.facet = 'resolution' AND o.subject_kind = 'name'
    ORDER BY o.subject_key, o.vantage_id, o.observed_at DESC
)
SELECT subject_key, observed_at
FROM latest
WHERE outcome = 'Resolved'
  AND value->'addresses' ? $1::text
ORDER BY observed_at ASC, subject_key ASC
LIMIT 1
`

type FindNameCitingAddressRow struct {
	SubjectKey string             `json:"subject_key"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// A Name whose current resolution cites the given Address (#195) — the Citation
// hop that answers why a Service's Address is in the estate. An Address has no
// lifecycle of its own, so its membership is grounded in evidence about ANOTHER
// subject: the Name whose Resolved answer names it. Where a resolution stops
// citing the Address this returns no row, which is exactly the `uncited` ground a
// departure records. Best-effort: the longest-lived citing Name, one hop.
func (q *Queries) FindNameCitingAddress(ctx context.Context, address string) (FindNameCitingAddressRow, error) {
	row := q.db.QueryRow(ctx, findNameCitingAddress, address)
	var i FindNameCitingAddressRow
	err := row.Scan(&i.SubjectKey, &i.ObservedAt)
	return i, err
}

const getEndpointSubject = `-- name: GetEndpointSubject :one
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'endpoint' AND o.facet = 'http-identity' AND o.subject_key = $1
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
`

type GetEndpointSubjectRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Resolve an Endpoint key to at most one subject (#198). An Endpoint drill-down
// reaches a subject by its own key — including one whose Service has left the
// estate, which is a population of no current member rather than a false "no
// record" (ADR-0072). The caller reads the latest http-identity value to render
// the current HTTP identity and split the key into its Name and Service legs.
func (q *Queries) GetEndpointSubject(ctx context.Context, subjectKey string) (GetEndpointSubjectRow, error) {
	row := q.db.QueryRow(ctx, getEndpointSubject, subjectKey)
	var i GetEndpointSubjectRow
	err := row.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt)
	return i, err
}

const getNameCitation = `-- name: GetNameCitation :one
SELECT o.id, o.observed_at, o.source, o.vantage_id, o.batch_id,
       b.scan_id, sc.kind AS scan_kind
FROM observation o
JOIN batch b ON b.id = o.batch_id
JOIN scan sc ON sc.id = b.scan_id
WHERE o.subject_kind = 'name' AND o.facet = 'resolution' AND o.subject_key = $1
ORDER BY o.observed_at ASC, o.id ASC
LIMIT 1
`

type GetNameCitationRow struct {
	ID         int64              `json:"id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Source     string             `json:"source"`
	VantageID  pgtype.Int8        `json:"vantage_id"`
	BatchID    int64              `json:"batch_id"`
	ScanID     int64              `json:"scan_id"`
	ScanKind   string             `json:"scan_kind"`
}

// The Citation chain's load-bearing hop: the observation that introduced a Name
// — its earliest resolution observation — plus the Batch and Scan it rode in on
// (CONTEXT.md `Citation`; ADR-0027). Answers "why is this here" by naming the
// measurement that first admitted the subject; the chain terminates one hop
// further at the covering Seed (FindCoveringNameSeed).
func (q *Queries) GetNameCitation(ctx context.Context, subjectKey string) (GetNameCitationRow, error) {
	row := q.db.QueryRow(ctx, getNameCitation, subjectKey)
	var i GetNameCitationRow
	err := row.Scan(
		&i.ID,
		&i.ObservedAt,
		&i.Source,
		&i.VantageID,
		&i.BatchID,
		&i.ScanID,
		&i.ScanKind,
	)
	return i, err
}

const getNameSubject = `-- name: GetNameSubject :one
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'name' AND o.facet = 'resolution' AND o.subject_key = $1
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
`

type GetNameSubjectRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Resolve a Name key to at most one subject, withdrawn or not. Search is a
// lookup and not a listing (ADR-0072 decision 3): the drill-down reaches a
// measured-gone Name by its own key rather than manufacturing a false "no
// record" at the URL. The caller reads the latest resolution value to decide
// whether the subject names a population of no current member.
func (q *Queries) GetNameSubject(ctx context.Context, subjectKey string) (GetNameSubjectRow, error) {
	row := q.db.QueryRow(ctx, getNameSubject, subjectKey)
	var i GetNameSubjectRow
	err := row.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt)
	return i, err
}

const getServiceSubject = `-- name: GetServiceSubject :one
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'service' AND o.facet = 'reachability' AND o.subject_key = $1
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
`

type GetServiceSubjectRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Resolve a Service key to at most one subject (#195). A Service drill-down
// reaches a subject by its own key — including one whose Address has left the
// estate, which is not a false "no record" but a population of no current member
// (ADR-0072). The caller reads the latest reachability value to render the
// current verdict and the Address the triple sits on.
func (q *Queries) GetServiceSubject(ctx context.Context, subjectKey string) (GetServiceSubjectRow, error) {
	row := q.db.QueryRow(ctx, getServiceSubject, subjectKey)
	var i GetServiceSubjectRow
	err := row.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt)
	return i, err
}

const listCurrentEndpointSubjects = `-- name: ListCurrentEndpointSubjects :many
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'endpoint' AND o.facet = 'http-identity'
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
WHERE ($1::text = '' OR subject_key ILIKE '%' || $1::text || '%')
ORDER BY subject_key
`

type ListCurrentEndpointSubjectsRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Every Endpoint currently in the estate, with optional search (#198). An Endpoint
// is a (Name, Service) pair — keyed `name@service`, or `@service` for the nameless
// endpoint — the only key under which HTTP identity is single-valued (CONTEXT.md
// `Endpoint`). Its membership rides its Service's (the Address's membership
// restated), so this is the thin "current Endpoints" read the drill-down lists.
// Like the Name and Service listings it carries no denominator (ADR-0072). The
// value shown is the latest http-identity the http-exchange leaf recorded.
func (q *Queries) ListCurrentEndpointSubjects(ctx context.Context, search string) ([]ListCurrentEndpointSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentEndpointSubjects, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentEndpointSubjectsRow{}
	for rows.Next() {
		var i ListCurrentEndpointSubjectsRow
		if err := rows.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentNameSubjects = `-- name: ListCurrentNameSubjects :many

WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'name' AND o.facet = 'resolution'
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
WHERE value->>'outcome' <> 'NameError'
  AND ($1::text = '' OR subject_key ILIKE '%' || $1::text || '%')
ORDER BY subject_key
`

type ListCurrentNameSubjectsRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Reads behind the Subjects screen (#189). All four are additive read queries
// over the wave-0 measurement corpus (observation / batch / scan) and the seed
// table — no new schema. `ListCurrentNameSubjects` is the thin "current Names"
// membership read the seam note (#189 → #192) asks for: it is the one place a
// caller decides which Names are in the estate, so a later refinement of
// membership (Shadowed suppression, #192; the cross-class withdrawal quorum,
// ADR-0006/ADR-0080) narrows this predicate here rather than growing a second
// computation elsewhere.
// Every Name currently in the estate, with optional search. A Name is a member
// while its latest resolution observation is not a measured Name Error — the
// only route a Name leaves is our resolver measuring NameError (ADR-0006). No
// count is selected: the estate can carry no honest denominator (ADR-0072), so
// there is nothing here to total. A withdrawn Name (latest resolution =
// NameError) is filtered out and reached only by key (GetNameSubject).
func (q *Queries) ListCurrentNameSubjects(ctx context.Context, search string) ([]ListCurrentNameSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentNameSubjects, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentNameSubjectsRow{}
	for rows.Next() {
		var i ListCurrentNameSubjectsRow
		if err := rows.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentServiceSubjects = `-- name: ListCurrentServiceSubjects :many
WITH latest AS (
    SELECT DISTINCT ON (o.subject_key)
        o.subject_key AS subject_key,
        o.value       AS value,
        o.observed_at AS observed_at
    FROM observation o
    WHERE o.subject_kind = 'service' AND o.facet = 'reachability'
    ORDER BY o.subject_key, o.observed_at DESC, o.id DESC
)
SELECT subject_key, value, observed_at
FROM latest
WHERE ($1::text = '' OR subject_key ILIKE '%' || $1::text || '%')
ORDER BY subject_key
`

type ListCurrentServiceSubjectsRow struct {
	SubjectKey string             `json:"subject_key"`
	Value      []byte             `json:"value"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

// Every Service currently in the estate, with optional search (#195). A Service
// is an (Address, port, transport) triple whose membership is its Address's
// membership restated — an Address is in the estate exactly while a current
// resolution cites it or a Seed covers it — so this is the thin "current
// Services" read the drill-down lists. Like the Name listing it carries no
// denominator (ADR-0072). A Service that has fallen out of the estate (its
// Address de-cited) is reached only by its own key; the value shown is the latest
// reachability verdict, reached or not-reached, both measured values.
func (q *Queries) ListCurrentServiceSubjects(ctx context.Context, search string) ([]ListCurrentServiceSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentServiceSubjects, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentServiceSubjectsRow{}
	for rows.Next() {
		var i ListCurrentServiceSubjectsRow
		if err := rows.Scan(&i.SubjectKey, &i.Value, &i.ObservedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
