// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTranscriptByJob = `-- name: GetTranscriptByJob :one
SELECT queue_job_id, kind, duration_ns, captured_at, variant, outcome,
       stdout, stderr, sent_scope, truncation, created_at
FROM transcript
WHERE queue_job_id = $1
`

// The single transcript for a queue_job id — the §6 read handler's source for
// `?job={id}`. One row per attempt (spec §1.1), so this addresses a transcript
// directly. Returns no row when the job produced no capture (a legible absence,
// which the handler renders distinctly from a captured-but-empty stream).
func (q *Queries) GetTranscriptByJob(ctx context.Context, queueJobID int64) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptByJob, queueJobID)
	var i Transcript
	err := row.Scan(
		&i.QueueJobID,
		&i.Kind,
		&i.DurationNs,
		&i.CapturedAt,
		&i.Variant,
		&i.Outcome,
		&i.Stdout,
		&i.Stderr,
		&i.SentScope,
		&i.Truncation,
		&i.CreatedAt,
	)
	return i, err
}

const insertTranscript = `-- name: InsertTranscript :exec
INSERT INTO transcript (
    queue_job_id, kind, duration_ns, captured_at, variant, outcome,
    stdout, stderr, sent_scope, truncation
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTranscriptParams struct {
	QueueJobID int64              `json:"queue_job_id"`
	Kind       string             `json:"kind"`
	DurationNs int64              `json:"duration_ns"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
	Variant    string             `json:"variant"`
	Outcome    []byte             `json:"outcome"`
	Stdout     []byte             `json:"stdout"`
	Stderr     []byte             `json:"stderr"`
	SentScope  []byte             `json:"sent_scope"`
	Truncation []byte             `json:"truncation"`
}

// Persist one job's verbatim transcript (raw-job-output spec §1.4), mirroring
// InsertObservation. The producer calls it once per captured job inside the
// worker's terminal transaction (§2.4), so a job cancelled mid-flight rolls its
// transcript back with the rest of its work. A job with no capture inserts no
// row — the absence is legible, distinct from a captured-but-empty stream.
func (q *Queries) InsertTranscript(ctx context.Context, arg InsertTranscriptParams) error {
	_, err := q.db.Exec(ctx, insertTranscript,
		arg.QueueJobID,
		arg.Kind,
		arg.DurationNs,
		arg.CapturedAt,
		arg.Variant,
		arg.Outcome,
		arg.Stdout,
		arg.Stderr,
		arg.SentScope,
		arg.Truncation,
	)
	return err
}
