// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verge_core.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVergeCoreFrequencyEdit = `-- name: DeleteVergeCoreFrequencyEdit :exec
DELETE FROM verge_core_frequency_edit WHERE port = $1
`

func (q *Queries) DeleteVergeCoreFrequencyEdit(ctx context.Context, port int32) error {
	_, err := q.db.Exec(ctx, deleteVergeCoreFrequencyEdit, port)
	return err
}

const listVergeCoreFrequencyEditsWithAuthor = `-- name: ListVergeCoreFrequencyEditsWithAuthor :many
SELECT e.id, e.port, e.action, e.created_at, a.username AS created_by_username
FROM verge_core_frequency_edit e
JOIN account a ON a.id = e.created_by
ORDER BY e.port
`

type ListVergeCoreFrequencyEditsWithAuthorRow struct {
	ID                int64              `json:"id"`
	Port              int32              `json:"port"`
	Action            string             `json:"action"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedByUsername string             `json:"created_by_username"`
}

func (q *Queries) ListVergeCoreFrequencyEditsWithAuthor(ctx context.Context) ([]ListVergeCoreFrequencyEditsWithAuthorRow, error) {
	rows, err := q.db.Query(ctx, listVergeCoreFrequencyEditsWithAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVergeCoreFrequencyEditsWithAuthorRow{}
	for rows.Next() {
		var i ListVergeCoreFrequencyEditsWithAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Port,
			&i.Action,
			&i.CreatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVergeCoreFrequencyEdit = `-- name: UpsertVergeCoreFrequencyEdit :exec
INSERT INTO verge_core_frequency_edit (port, action, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (port) DO UPDATE SET action = EXCLUDED.action, created_by = EXCLUDED.created_by, created_at = now()
`

type UpsertVergeCoreFrequencyEditParams struct {
	Port      int32  `json:"port"`
	Action    string `json:"action"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) UpsertVergeCoreFrequencyEdit(ctx context.Context, arg UpsertVergeCoreFrequencyEditParams) error {
	_, err := q.db.Exec(ctx, upsertVergeCoreFrequencyEdit, arg.Port, arg.Action, arg.CreatedBy)
	return err
}
